import { h, s, drag, localPos, clamp, copy, toast, sleep, rng, pick, blip, audio, fitCanvas } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle } from '../kit.js';
import { scene } from './imagefx.js';
const MONO = "'JetBrains Mono Variable',monospace";
const V = {};
V['bubble-chart-time-scrubber'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#333', ac: '#ffb600', dark: false });
  const REG = [['Asia', '#ff5872'], ['Africa', '#00d5e9'], ['Americas', '#7feb00'], ['Europe', '#ffe700']];
  const R = rng(4); const C = Array.from({ length: 70 }, (_, i) => { const r = i % 4; return { n: ['China', 'India', 'Nigeria', 'USA', 'Germany', 'Brazil', 'Japan', 'Korea', 'Kenya', 'France', 'Mexico', 'Egypt'][i % 12] + (i >= 12 ? ' ' + i : ''), r, pop: 0.5 + R() ** 3 * 14, g0: 400 + R() * 1400, gr: 0.8 + R() * 2.6 + (r === 3 ? 0.8 : 0), l0: 26 + R() * 10, lk: 0.5 + R() * 0.8, take: 1880 + R() * 90 }; });
  let year = 2025, play = false;
  const svg = s('svg', { viewBox: '0 0 900 560', style: 'width:100%;height:100%' }); const W = 900, H = 560, L = 60, B = 510;
  const X = (g) => L + ((Math.log10(g) - 2.5) / 2.7) * (W - L - 20), Y = (l) => B - ((l - 20) / 70) * (B - 20);
  const at = (c, y) => { const t = clamp((y - c.take) / 150, 0, 1); const g = c.g0 * Math.pow(1 + c.gr / 100, Math.max(0, y - 1800) * (0.4 + t * 0.6)); const l = c.l0 + (84 - c.l0) * (1 - Math.exp(-Math.max(0, y - c.take) * c.lk / 60)); return [Math.min(g, 110000), Math.min(l, 86), c.pop * (0.2 + 0.8 * clamp((y - 1800) / 225, 0, 1))]; };
  const yl = h('b');
  const draw = () => { const els = [s('text', { x: W / 2 + 20, y: 380, 'text-anchor': 'middle', 'font-size': 200, fill: '#e8eaee', 'font-weight': 300, 'font-family': 'Inter Variable' }, Math.floor(year))]; [500, 1000, 2000, 5000, 10000, 20000, 50000, 100000].forEach((g) => els.push(s('line', { x1: X(g), x2: X(g), y1: 20, y2: B, stroke: '#eee' }), s('text', { x: X(g), y: B + 18, 'font-size': 11, fill: '#888', 'text-anchor': 'middle' }, g >= 1000 ? g / 1000 + 'k' : g))); [30, 40, 50, 60, 70, 80].forEach((l) => els.push(s('line', { x1: L, x2: W - 20, y1: Y(l), y2: Y(l), stroke: '#eee' }), s('text', { x: L - 8, y: Y(l) + 4, 'font-size': 11, fill: '#888', 'text-anchor': 'end' }, l))); els.push(s('text', { x: W / 2, y: B + 40, 'font-size': 13, fill: '#555', 'text-anchor': 'middle' }, 'Income per person (GDP/capita, PPP$ inflation-adjusted) ▾'), s('text', { x: 16, y: 280, 'font-size': 13, fill: '#555', transform: 'rotate(-90 16 280)', 'text-anchor': 'middle' }, 'Life expectancy ▾')); [...C].sort((a, b) => at(b, year)[2] - at(a, year)[2]).forEach((c) => { const [g, l, p] = at(c, year); els.push(s('circle', { cx: X(g), cy: Y(l), r: Math.sqrt(p) * 9, fill: REG[c.r][1], stroke: '#333', 'stroke-width': 0.6, opacity: 0.9 }, s('title', {}, c.n))); }); svg.replaceChildren(...els); yl.textContent = Math.floor(year); sl.input.value = year; };
  const sl = slider('', 1800, 2025, year, 1, (v) => { year = v; draw(); });
  const loop = () => { if (play) { year += 0.5; if (year >= 2025) { year = 2025; play = false; pb.textContent = '▶'; } draw(); } requestAnimationFrame(loop); };
  const pb = h('button', { style: { width: '40px', height: '40px', borderRadius: '50%', background: '#333', color: '#fff', border: 0 }, onclick: () => { play = !play; if (play && year >= 2025) year = 1800; pb.textContent = play ? '❚❚' : '▶'; } }, '▶');
  root.style.display = 'grid'; root.style.gridTemplateColumns = '1fr 240px'; root.style.gridTemplateRows = '36px 1fr 56px';
  root.append(h('div.k-row', { style: { gridColumn: '1/-1', padding: '0 14px', gap: '16px', fontSize: '12px', borderBottom: '1px solid #eee' } }, h('b', { style: { color: '#ffb600' } }, '◉ Gapminder-ish'), 'Bubbles', 'Maps', 'Trends', 'Ranks', h('span', { style: { flex: 1 } }), 'Share', 'English'), h('div', {}, svg), h('div', { style: { padding: '10px', fontSize: '12px', borderLeft: '1px solid #eee', display: 'grid', gap: '6px', alignContent: 'start' } }, h('b', {}, 'Color: World regions'), s('svg', { viewBox: '0 0 200 100', width: 200 }, ...REG.map(([n, c], i) => s('circle', { cx: 30 + i * 46, cy: 50, r: 20, fill: c }))), ...REG.map(([n, c]) => h('div.k-row', {}, h('span', { style: { width: '10px', height: '10px', background: c, borderRadius: '50%' } }), n)), h('div', { style: { marginTop: '10px' } }, 'Size: Population'), h('input', { placeholder: 'Search country…', style: { padding: '5px' } }), ...C.slice(0, 12).map((c) => h('div', { style: { opacity: .7 } }, '☐ ' + c.n))), h('div.k-row', { style: { gridColumn: '1/-1', padding: '0 20px', gap: '14px' } }, pb, h('div', { style: { flex: 1 } }, sl), yl));
  draw(); loop();
  window.__demoProof = async () => { year = 2025; draw(); return 'scrubbed to 2025; play animates 1800→2025'; };
};
V['data-chart-mapping-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#1ec77b', dark: false }); root.style.overflow = 'auto';
  const SAMPLE = 'country,continent,gdp,population,happiness\nNorway,Europe,89,5.4,7.3\nJapan,Asia,34,125,6.1\nKorea,Asia,33,52,5.9\nBrazil,Americas,9,214,6.3\nKenya,Africa,2,54,4.5\nUSA,Americas,76,332,6.9\nIndia,Asia,2.4,1408,4.0\nGermany,Europe,48,83,6.9';
  let data = [], cols = [], chart = 'bubble', map = { x: null, y: null, size: null, color: null };
  const ta = h('textarea', { placeholder: 'Paste your data here (csv, tsv, json)…', style: { width: '100%', height: '220px', border: '1px solid #ddd', font: `12px ${MONO}`, padding: '10px' }, oninput: () => parse() });
  const dims = h('div', { style: { display: 'grid', gap: '6px' } }), slots = h('div', { style: { display: 'grid', gap: '8px' } }), out = h('div', { style: { minHeight: '360px', border: '1px solid #eee', display: 'grid', placeItems: 'center' } });
  const parse = () => { const lines = ta.value.trim().split('\n'); cols = lines[0]?.split(',') || []; data = lines.slice(1).map((l) => Object.fromEntries(l.split(',').map((v, i) => [cols[i], isNaN(+v) ? v : +v]))); dims.replaceChildren(...cols.map((c) => { const num = typeof data[0]?.[c] === 'number'; const el = h('div', { draggable: true, style: { border: '1px solid #ccc', padding: '6px 10px', borderRadius: '4px', fontSize: '12px', cursor: 'grab', background: '#fafafa' }, ondragstart: (e) => e.dataTransfer.setData('text', c) }, (num ? '# ' : 'Aa ') + c); return el; })); render(); };
  const drawSlots = () => slots.replaceChildren(...Object.keys(map).map((k) => h('div', { style: { border: '2px dashed ' + (map[k] ? '#1ec77b' : '#ccc'), padding: '10px', borderRadius: '4px', fontSize: '12px' }, ondragover: (e) => e.preventDefault(), ondrop: (e) => { map[k] = e.dataTransfer.getData('text'); drawSlots(); render(); } }, h('b', {}, k.toUpperCase()), ' ', map[k] || 'drop dimension here')));
  const render = () => { if (!map.x || !map.y || !data.length) { out.textContent = 'Map dimensions to see the chart'; return; } const xs = data.map((d) => d[map.x]), ys = data.map((d) => d[map.y]); const [x0, x1] = [Math.min(...xs), Math.max(...xs)], [y0, y1] = [Math.min(...ys), Math.max(...ys)]; const ss = map.size ? data.map((d) => d[map.size]) : null; const smax = ss ? Math.max(...ss) : 1; const cats = map.color ? [...new Set(data.map((d) => d[map.color]))] : []; const PAL = ['#1ec77b', '#f5a623', '#4a90e2', '#d0021b', '#9013fe']; out.replaceChildren(s('svg', { viewBox: '0 0 600 340', width: 600 }, s('line', { x1: 40, y1: 300, x2: 580, y2: 300, stroke: '#333' }), s('line', { x1: 40, y1: 20, x2: 40, y2: 300, stroke: '#333' }), ...data.map((d, i) => { const x = 40 + ((d[map.x] - x0) / (x1 - x0 || 1)) * 520, y = 300 - ((d[map.y] - y0) / (y1 - y0 || 1)) * 260; return chart === 'bar' ? s('rect', { x: 50 + i * (520 / data.length), y, width: 520 / data.length - 8, height: 300 - y, fill: cats.length ? PAL[cats.indexOf(d[map.color]) % 5] : '#1ec77b' }) : s('g', {}, s('circle', { cx: x, cy: y, r: ss ? 4 + Math.sqrt(d[map.size] / smax) * 30 : 6, fill: cats.length ? PAL[cats.indexOf(d[map.color]) % 5] : '#1ec77b', opacity: .7 }), s('text', { x, y: y - 8, 'font-size': 10, 'text-anchor': 'middle' }, d[cols[0]])); }))); };
  const sec = (n, t, ...k) => h('div', { style: { padding: '20px 40px', borderBottom: '1px solid #eee' } }, h('div', { style: { fontSize: '18px', marginBottom: '14px' } }, `${n}. ${t}`), ...k);
  root.append(h('div.k-row', { style: { height: '44px', padding: '0 20px', borderBottom: '3px solid #1ec77b', fontSize: '12px', gap: '16px' } }, h('b', {}, 'RAW Graphs-ish 2.0'), h('span', { style: { flex: 1 } }), 'Docs', 'Learning', 'Gallery', h('span', { style: { background: '#1ec77b', color: '#fff', padding: '4px 10px' } }, 'Donate')), sec(1, 'Load your data', h('div', { style: { display: 'grid', gridTemplateColumns: '200px 1fr', gap: '20px' } }, h('div', { style: { display: 'grid', gap: '6px', fontSize: '13px', alignContent: 'start' } }, ...['Paste your data', 'Upload your data', 'Try our data samples', 'SPARQL query', 'From URL', 'Open your project'].map((t, i) => h('div', { style: { padding: '8px 10px', background: i === 0 ? '#e7f9f0' : '', borderLeft: i === 0 ? '3px solid #1ec77b' : '3px solid transparent', cursor: 'pointer' }, onclick: () => { if (i === 2) { ta.value = SAMPLE; parse(); } } }, t))), h('div', {}, ta, h('div', { style: { fontSize: '12px', opacity: .6, marginTop: '6px', textAlign: 'center' } }, 'Copy and paste your data from other applications or websites. You can use tabular (TSV, CSV, DSV) or JSON data.')))), sec(2, 'Choose a chart', seg([['bubble', '◯ Bubble chart'], ['bar', '▮ Bar chart']], chart, (v) => { chart = v; render(); })), sec(3, 'Mapping', h('div', { style: { display: 'grid', gridTemplateColumns: '200px 1fr', gap: '20px' } }, dims, slots)), sec(4, 'Customize', out, h('div.k-row', { style: { marginTop: '10px' } }, btn('Export SVG', () => copy(out.innerHTML), 'pri'), btn('PNG', () => toast('chart.png')))));
  drawSlots(); parse();
  window.__demoProof = async () => { map = { x: 'gdp', y: 'happiness', size: 'population', color: 'continent' }; ta.value = SAMPLE; parse(); drawSlots(); ta.value = ''; return 'sample mapped to bubble chart (step 4); step 1 textarea shown'; };
};
V['graphing-calc-workspace'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#333', ac: '#2f72dc', dark: false });
  const COLS = ['#c74440', '#2d70b3', '#388c46', '#6042a6', '#fa7e19', '#000']; const exprs = [{ s: '', c: COLS[0] }];
  const cv = h('canvas', { style: { width: '100%', height: '100%', cursor: 'move' } }); const wrap = h('div', { style: { position: 'relative' } }, cv); let cx = 0, cy = 0, sc = 50; let vars = { a: 1 };
  drag(cv, { move: (e) => { cx -= e.movementX / sc; cy += e.movementY / sc; draw(); } }); cv.addEventListener('wheel', (e) => { e.preventDefault(); sc = clamp(sc * (e.deltaY > 0 ? 0.9 : 1.1), 5, 800); draw(); }, { passive: false });
  const compile = (src) => { const m = src.replace(/\s/g, '').match(/^(?:y=)?(.+)$/); if (!m || !src.trim()) return null; if (/^[a-z]=[-\d.]+$/.test(src.replace(/\s/g, ''))) { const [k, v] = src.replace(/\s/g, '').split('='); vars[k] = +v; return null; } let e = m[1].replace(/\^/g, '**').replace(/(\d)([a-z(])/g, '$1*$2').replace(/\)\(/g, ')*(').replace(/\b(sin|cos|tan|sqrt|abs|log|exp|floor)\b/g, 'Math.$1').replace(/\bpi\b/g, 'Math.PI'); try { const f = new Function('x', 'v', `with(v){return ${e}}`); f(1, vars); return f; } catch { return 'err'; } };
  const draw = () => { fitCanvas(cv, wrap); const g = cv.g, W = cv.W, H = cv.H; g.fillStyle = '#fff'; g.fillRect(0, 0, W, H); const px = (x) => W / 2 + (x - cx) * sc, py = (y) => H / 2 - (y - cy) * sc; const step = [1, 2, 5, 10, 20, 50].find((s2) => s2 * sc > 60) || 100; for (const [st, col] of [[step / 5, '#f0f0f0'], [step, '#d8d8d8']]) { g.strokeStyle = col; g.lineWidth = 1; g.beginPath(); for (let x = Math.floor((cx - W / 2 / sc) / st) * st; x < cx + W / 2 / sc; x += st) { g.moveTo(px(x), 0); g.lineTo(px(x), H); } for (let y = Math.floor((cy - H / 2 / sc) / st) * st; y < cy + H / 2 / sc; y += st) { g.moveTo(0, py(y)); g.lineTo(W, py(y)); } g.stroke(); } g.strokeStyle = '#333'; g.lineWidth = 1.5; g.beginPath(); g.moveTo(px(0), 0); g.lineTo(px(0), H); g.moveTo(0, py(0)); g.lineTo(W, py(0)); g.stroke(); g.fillStyle = '#333'; g.font = '12px sans-serif'; for (let x = Math.floor((cx - W / 2 / sc) / step) * step; x < cx + W / 2 / sc; x += step) if (Math.abs(x) > 1e-9) g.fillText(+x.toFixed(2), px(x) - 4, py(0) + 14); for (let y = Math.floor((cy - H / 2 / sc) / step) * step; y < cy + H / 2 / sc; y += step) if (Math.abs(y) > 1e-9) g.fillText(+y.toFixed(2), px(0) + 4, py(y) + 4); vars = { a: vars.a }; exprs.forEach((e) => compile(e.s)); exprs.forEach((e) => { const f = compile(e.s); e.el && (e.el.style.borderLeftColor = f === 'err' ? '#f33' : e.c); if (typeof f !== 'function') return; g.strokeStyle = e.c; g.lineWidth = 2.5; g.beginPath(); let pen = false; for (let sx = 0; sx <= W; sx += 1) { const x = cx + (sx - W / 2) / sc; let y; try { y = f(x, vars); } catch { y = NaN; } if (!isFinite(y) || Math.abs(y - cy) > 1e4) { pen = false; continue; } pen ? g.lineTo(sx, py(y)) : g.moveTo(sx, py(y)); pen = true; } g.stroke(); }); };
  const list = h('div');
  const drawList = () => list.replaceChildren(...exprs.map((e, i) => { const inp = h('input', { value: e.s, placeholder: '', style: { width: '100%', border: 0, outline: 'none', font: '18px "Times New Roman",serif', padding: '14px 8px' }, oninput: (ev) => { e.s = ev.target.value; if (i === exprs.length - 1 && e.s) { exprs.push({ s: '', c: COLS[exprs.length % COLS.length] }); drawList(); list.querySelectorAll('input')[i].focus(); } draw(); } }); e.el = h('div', { style: { display: 'grid', gridTemplateColumns: '34px 1fr', borderBottom: '1px solid #ddd', borderLeft: '4px solid ' + e.c } }, h('div', { style: { background: '#f4f4f4', fontSize: '11px', color: '#888', padding: '4px' } }, i + 1), inp); return e.el; }));
  root.style.display = 'grid'; root.style.gridTemplateColumns = '340px 1fr'; root.style.gridTemplateRows = '40px 1fr';
  root.append(h('div.k-row', { style: { gridColumn: '1/-1', background: '#333', color: '#fff', padding: '0 14px', gap: '14px', fontSize: '13px' } }, '☰', 'Untitled Graph', h('span', { style: { flex: 1, textAlign: 'center', fontSize: '20px', fontWeight: 300 } }, 'desmos-ish'), h('span', { style: { background: '#2f72dc', padding: '4px 10px', borderRadius: '4px' } }, 'Sign up'), 'Log in'), h('div', { style: { borderRight: '1px solid #ccc', display: 'grid', gridTemplateRows: '32px 1fr' } }, h('div.k-row', { style: { background: '#f4f4f4', padding: '0 8px', borderBottom: '1px solid #ccc', fontSize: '18px' } }, '+', '↶', '↷', h('span', { style: { flex: 1 } }), '⚙', '«'), list), wrap);
  drawList(); setTimeout(draw, 0); new ResizeObserver(draw).observe(wrap);
  window.__demoProof = async () => { exprs[0].s = ''; drawList(); draw(); return 'graph ready (type y=… to plot; blank like reference)'; };
};
V['alg0-step-visualizer'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#3ecf8e', dark: false });
  let arr = [5, 2, 9, 1, 6, 3, 8, 4, 7], steps = [], si = 0, algo = 'Bubble Sort', timer = null;
  const bubble = (a) => { a = [...a]; const st = [{ a: [...a], hi: [], msg: 'Start' }]; for (let i = 0; i < a.length; i++) for (let j = 0; j < a.length - i - 1; j++) { st.push({ a: [...a], hi: [j, j + 1], msg: `Compare ${a[j]} and ${a[j + 1]}` }); if (a[j] > a[j + 1]) { [a[j], a[j + 1]] = [a[j + 1], a[j]]; st.push({ a: [...a], hi: [j, j + 1], sw: true, msg: `Swap → ${a[j]}, ${a[j + 1]}` }); } } st.push({ a: [...a], hi: [], done: true, msg: 'Sorted ✓' }); return st; };
  const select = (a) => { a = [...a]; const st = [{ a: [...a], hi: [], msg: 'Start' }]; for (let i = 0; i < a.length; i++) { let m = i; for (let j = i + 1; j < a.length; j++) { st.push({ a: [...a], hi: [m, j], msg: `min=${a[m]} vs ${a[j]}` }); if (a[j] < a[m]) m = j; } [a[i], a[m]] = [a[m], a[i]]; st.push({ a: [...a], hi: [i, m], sw: true, msg: `Place ${a[i]} at ${i}` }); } st.push({ a: [...a], hi: [], done: true, msg: 'Sorted ✓' }); return st; };
  const chart = h('div', { style: { display: 'flex', alignItems: 'flex-end', gap: '6px', height: '220px', padding: '16px', background: '#fafafa', border: '1px solid #eee', borderRadius: '8px' } }); const msg = h('div', { style: { textAlign: 'center', fontWeight: 700, margin: '8px 0' } }); const ctr = h('span');
  const draw = () => { const st = steps[si]; chart.replaceChildren(...st.a.map((v, i) => h('div', { style: { flex: 1, height: v * 20 + 'px', background: st.done ? '#3ecf8e' : st.hi.includes(i) ? (st.sw ? '#ff5a6e' : '#ffb74d') : '#c8c8c8', borderRadius: '4px 4px 0 0', display: 'grid', alignContent: 'start', justifyItems: 'center', fontSize: '11px', color: '#333', transition: 'height .2s' } }, h('span', { style: { marginTop: '-16px' } }, v)))); msg.textContent = st.msg; ctr.textContent = `Step ${si + 1}/${steps.length}`; };
  const load = () => { steps = algo === 'Bubble Sort' ? bubble(arr) : select(arr); si = 0; draw(); };
  const ALGS = { Sorting: ['Bubble Sort', 'Selection Sort', 'Insertion Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort'], Searching: ['Binary Search', 'Linear Search'], Graphs: ['BFS', 'DFS', 'Dijkstra'], 'Dynamic Programming': ['Knapsack', 'LCS'] };
  root.style.display = 'grid'; root.style.gridTemplateColumns = '240px 1fr'; root.style.gridTemplateRows = '44px 1fr';
  root.append(h('div.k-row', { style: { gridColumn: '1/-1', padding: '0 16px', borderBottom: '1px solid #eee', fontSize: '13px' } }, h('b', {}, '⬢ Algorithm Visualizer-ish'), h('span', { style: { flex: 1 } }), h('span', { style: { background: '#f1f1f1', padding: '4px 10px', borderRadius: '99px' } }, '⏮ ◀ ▶ ⏭')), h('div', { style: { borderRight: '1px solid #eee', padding: '10px', fontSize: '12px', overflow: 'auto' } }, h('input', { placeholder: 'Search algorithms', style: { width: '100%', padding: '6px', marginBottom: '8px' } }), ...Object.entries(ALGS).flatMap(([cat, xs]) => [h('div', { style: { fontWeight: 700, margin: '10px 0 4px' } }, '▾ ' + cat), ...xs.map((a) => h('div', { style: { padding: '5px 10px', cursor: 'pointer', borderRadius: '4px', background: a === algo ? '#e8f8f1' : '' }, onclick: () => { if (a.includes('Bubble') || a.includes('Selection')) { algo = a; load(); } else toast(a + ' (bubble/selection implemented)'); } }, a))])), h('div', { style: { padding: '20px 60px', display: 'grid', alignContent: 'start', justifyItems: 'center' } }, h('div', { style: { fontSize: '22px', fontWeight: 700 } }, 'Algorithm Visualizer'), h('p', { style: { maxWidth: '520px', textAlign: 'center', fontSize: '13px', opacity: .7 } }, 'Learn algorithms through step-by-step visualization. Pick an algorithm, then play, pause or step through each comparison and swap.'), h('div', { style: { width: '560px' } }, msg, chart), h('div.k-row', { style: { marginTop: '12px' } }, btn('⏮', () => { si = 0; draw(); }), btn('◀ Prev', () => { si = Math.max(0, si - 1); draw(); }), btn('▶ Play', () => { clearInterval(timer); timer = setInterval(() => { if (si < steps.length - 1) { si++; draw(); } else clearInterval(timer); }, 350); }, 'pri'), btn('Next ▶', () => { si = Math.min(steps.length - 1, si + 1); draw(); }), btn('Shuffle', () => { arr = arr.sort(() => Math.random() - 0.5); load(); }), ctr), h('div.k-row', { style: { marginTop: '16px', fontSize: '11px', gap: '14px', opacity: .7 } }, h('span', {}, '■ compare', { }), h('span', { style: { color: '#ff5a6e' } }, '■ swap'), h('span', { style: { color: '#3ecf8e' } }, '■ sorted'))));
  load();
  window.__demoProof = async () => { si = 7; draw(); return 'stepped to step 8 (compare/swap highlighted)'; };
};
V['timezone-timeline-scrubber'] = (root, T) => {
  theme(root, T, { bg: '#2b2240', fg: '#eee', ac: '#6ce38f', dark: true });
  const Z = [['Pacific Time', 'Los Angeles', -7], ['Mountain Time', 'Denver', -6], ['Central Time', 'Chicago', -5], ['Eastern Time', 'New York', -4], ['Rio de Janeiro', 'Brazil', -3], ['UTC', '', 0], ['London', 'United Kingdom', 1], ['Berlin', 'Germany', 2], ['Moscow', 'Russia', 3], ['Dubai', 'UAE', 4], ['Mumbai', 'India', 5.5], ['Singapore', '', 8], ['Seoul', 'South Korea', 9], ['Sydney', 'Australia', 10]];
  let off = 10 + 10 / 60; const now = 10.17;
  const rows = h('div', { style: { position: 'relative' } }); const line = h('div', { style: { position: 'absolute', top: 0, bottom: 0, width: '2px', background: '#6ce38f', pointerEvents: 'none' } }); const pill = h('div', { style: { position: 'absolute', top: '-26px', transform: 'translateX(-50%)', background: '#6ce38f', color: '#000', padding: '2px 8px', borderRadius: '99px', fontSize: '11px', fontWeight: 700 } });
  const L = 250, CW = 46;
  const draw = () => { rows.replaceChildren(...Z.map(([n, sub, o]) => h('div', { style: { display: 'flex', height: '32px', alignItems: 'center', borderBottom: '1px solid #ffffff10' } }, h('div', { style: { width: L + 'px', fontSize: '12px', paddingLeft: '14px', flex: 'none' } }, h('b', {}, n), ' ', h('span', { style: { opacity: .5 } }, sub)), h('div', { style: { display: 'flex', gap: '2px' } }, ...Array.from({ length: 24 }, (_, i) => { const hr = ((i + Math.floor(o) + 24) % 24); const day = hr >= 9 && hr < 18; const night = hr < 6 || hr >= 22; return h('div', { style: { width: CW - 2 + 'px', height: '22px', background: day ? '#ffffff30' : night ? '#ffffff08' : '#ffffff18', borderRadius: '3px', fontSize: '10px', display: 'grid', placeItems: 'center', opacity: .9 } }, hr === 0 ? h('b', {}, 'Oct 1') : `${hr % 12 || 12}${hr < 12 ? 'am' : 'pm'}`); })), h('div', { style: { position: 'absolute', left: L + off * CW + 6 + 'px', fontSize: '11px', fontWeight: 700, background: '#2b2240', padding: '0 4px' } }, fmt(off + o))))); rows.append(line); line.style.left = L + off * CW + 'px'; line.append(pill); pill.textContent = fmt(off + 9) + ' Seoul'; };
  const fmt = (x) => { x = ((x % 24) + 24) % 24; const hh = Math.floor(x), m = Math.round((x - hh) * 60 / 15) * 15; return `${hh % 12 || 12}:${String(m % 60).padStart(2, '0')}${hh < 12 ? 'am' : 'pm'}`; };
  rows.addEventListener('pointermove', (e) => { const p = localPos(e, rows); if (p.x > L) { off = clamp((p.x - L) / CW, 0, 23.9); draw(); } });
  root.style.overflow = 'auto';
  root.append(h('div.k-row', { style: { height: '44px', padding: '0 14px', gap: '14px', fontSize: '13px', background: '#231b36' } }, h('b', {}, '⏲ Every Time Zone-ish'), h('span', { style: { flex: 1 } }), 'Timeline', 'Meetings', 'People', h('span', { style: { background: '#6ce38f', color: '#000', padding: '3px 10px', borderRadius: '4px' } }, 'Sign in')), h('div.k-row', { style: { padding: '10px 14px', fontSize: '14px', gap: '10px' } }, h('b', {}, '📅 September 30 – October 1'), h('span', { style: { background: '#6c4bd8', padding: '2px 8px', borderRadius: '4px', fontSize: '11px' } }, 'Today'), h('span', { style: { background: '#6c4bd8', padding: '2px 8px', borderRadius: '4px', fontSize: '11px' } }, '+ Add zone')), h('div', { style: { paddingTop: '30px' } }, rows), h('div', { style: { position: 'absolute', right: '14px', bottom: '14px', background: '#e0457b', padding: '6px 12px', borderRadius: '4px', fontSize: '12px', cursor: 'pointer' }, onclick: () => copy(Z.map(([n, , o]) => `${n}: ${fmt(off + o)}`).join('\n')) }, '⧉ Copy times'));
  draw();
  window.__demoProof = async () => { off = 10.25; draw(); return 'scrubbed timeline; all zones updated'; };
};
V['waveform-audio-editor'] = (root, T) => {
  theme(root, T, { bg: '#161719', fg: '#ccc', ac: '#e33', dark: true });
  const SR = 22050, len = SR * 6; let buf = new Float32Array(len); for (let i = 0; i < len; i++) { const t = i / SR; buf[i] = (Math.sin(t * 220 * 6.283) * 0.4 + Math.sin(t * 331 * 6.283) * 0.2) * Math.exp(-((t % 1) * 3)) + (Math.random() - 0.5) * 0.05; }
  const cv = h('canvas', { style: { width: '100%', height: '100%' } }); const wrap = h('div', { style: { position: 'relative', background: '#0e0f10', border: '1px solid #2a2a2a' } }, cv); let sel = [0.2, 0.45], head = 0, src = null;
  const draw = () => { fitCanvas(cv, wrap); const g = cv.g, W = cv.W, H = cv.H; g.fillStyle = '#0e0f10'; g.fillRect(0, 0, W, H); g.fillStyle = '#ffffff10'; g.fillRect(sel[0] * W, 0, (sel[1] - sel[0]) * W, H); const step = Math.floor(len / W); g.fillStyle = '#e33'; for (let x = 0; x < W; x++) { let mn = 1, mx = -1; for (let k = 0; k < step; k += 8) { const v = buf[x * step + k] || 0; if (v < mn) mn = v; if (v > mx) mx = v; } const inSel = x / W >= sel[0] && x / W <= sel[1]; g.fillStyle = inSel ? '#ff6b6b' : '#a33'; g.fillRect(x, H / 2 - mx * H * 0.45, 1, (mx - mn) * H * 0.45 + 1); } g.fillStyle = '#fff'; g.fillRect(head * W, 0, 1, H); };
  let s0; drag(cv, { start: (e) => { s0 = localPos(e, cv).x / cv.W; sel = [s0, s0]; }, move: (e) => { const x = clamp(localPos(e, cv).x / cv.W, 0, 1); sel = [Math.min(s0, x), Math.max(s0, x)]; draw(); } });
  const range = () => [Math.floor(sel[0] * len), Math.floor(sel[1] * len)]; const fx = (f) => { const [a, b] = range(); for (let i = a; i < b; i++) buf[i] = f(buf[i], (i - a) / (b - a || 1), i); draw(); };
  const play = () => { const ac = audio(); const [a, b] = sel[1] - sel[0] > 0.01 ? range() : [0, len]; const ab = ac.createBuffer(1, b - a, SR); ab.copyToChannel(buf.slice(a, b), 0); src?.stop(); src = ac.createBufferSource(); src.buffer = ab; src.connect(ac.destination); src.start(); const t0 = performance.now(); const tick = () => { const p = (performance.now() - t0) / 1000 / ((b - a) / SR); if (p < 1) { head = (a + p * (b - a)) / len; draw(); requestAnimationFrame(tick); } }; tick(); };
  const tb = (l, f) => h('button', { style: { background: '#222', color: '#ccc', border: '1px solid #333', padding: '6px 10px', fontSize: '12px' }, onclick: f }, l);
  const modal = h('div', { style: { position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', width: '400px', background: '#1f2023', border: '1px solid #333', padding: '18px', fontSize: '12px', lineHeight: 1.6, boxShadow: '0 10px 40px #000a' } }, h('b', { style: { fontSize: '14px' } }, 'Welcome to AudioMass-ish'), h('p', {}, 'AudioMass-ish is a free, open source, web-based audio and waveform editor. It runs entirely in the browser with no backend and no plugins required.'), h('p', {}, 'Tips: drag on the waveform to select a region, then apply effects from the toolbar. Space to play.'), h('div', { style: { textAlign: 'right' } }, h('button', { style: { background: '#e33', color: '#fff', border: 0, padding: '5px 14px' }, onclick: () => modal.remove() }, 'OK')));
  window.addEventListener('keydown', (e) => e.code === 'Space' && (e.preventDefault(), play()));
  root.style.display = 'grid'; root.style.gridTemplateRows = '56px 1fr 60px'; root.style.padding = '0 14px 10px';
  root.append(h('div.k-row', { style: { gap: '6px' } }, h('div', { style: { background: '#000', color: '#e33', font: `22px ${MONO}`, padding: '4px 10px' } }, '00:00.000'), tb('▶', play), tb('■', () => src?.stop()), tb('Gain +', () => fx((v) => v * 1.5)), tb('Gain −', () => fx((v) => v * 0.6)), tb('Fade in', () => fx((v, t) => v * t)), tb('Fade out', () => fx((v, t) => v * (1 - t))), tb('Reverse', () => { const [a, b] = range(); buf.subarray(a, b).reverse(); draw(); }), tb('Silence', () => fx(() => 0)), tb('Normalize', () => { let m = 0; buf.forEach((v) => (m = Math.max(m, Math.abs(v)))); fx((v) => v / m * 0.95); }), h('span', { style: { flex: 1 } }), h('span', { style: { fontSize: '11px', opacity: .6 } }, 'File · Edit · View · Effects')), wrap, h('div.k-row', { style: { fontSize: '11px', opacity: .7 } }, 'Selection: ', h('b', {}, 'region'), ' · 22050 Hz mono · drag to select, Space to play'), modal);
  new ResizeObserver(draw).observe(wrap);
  window.__demoProof = async () => { sel = [0.3, 0.55]; fx((v, t) => v * (1 - t)); return 'selected region + fade out applied (welcome modal)'; };
};
V['ladybug-effects-studio'] = (root, T) => {
  theme(root, T, { bg: '#1b1c1e', fg: '#ddd', panel: '#242528', ac: '#ff4d4d', dark: true });
  const img = scene(420, 300, 'portrait', 7); const cv = h('canvas', { width: 420, height: 300, style: { width: '100%', borderRadius: '6px', background: '#000' } }); const P = { fx: 'halftone', amt: 0.6, size: 6, tint: '#ff4d4d' };
  const draw = () => { const g = cv.getContext('2d'); g.drawImage(img, 0, 0); const d = g.getImageData(0, 0, 420, 300); if (P.fx === 'halftone') { g.fillStyle = '#111'; g.fillRect(0, 0, 420, 300); g.fillStyle = '#eee'; for (let y = 0; y < 300; y += P.size) for (let x = 0; x < 420; x += P.size) { const i = (y * 420 + x) * 4; const l = (d.data[i] + d.data[i + 1] + d.data[i + 2]) / 765; g.beginPath(); g.arc(x, y, (P.size / 2) * l * (0.5 + P.amt), 0, 7); g.fill(); } } else if (P.fx === 'glitch') { g.putImageData(d, 0, 0); for (let k = 0; k < 20 * P.amt; k++) { const y = Math.random() * 300, hh = Math.random() * 20; g.drawImage(cv, 0, y, 420, hh, (Math.random() - 0.5) * 40, y, 420, hh); } } else { const lv = 2 + Math.round((1 - P.amt) * 6); for (let i = 0; i < d.data.length; i += 4) { const l = (d.data[i] + d.data[i + 1] + d.data[i + 2]) / 3; const q = Math.round((l / 255) * lv) / lv; const t = [1, 3, 5].map((k) => parseInt(P.tint.slice(k, k + 2), 16)); d.data[i] = t[0] * q; d.data[i + 1] = t[1] * q; d.data[i + 2] = t[2] * q; } g.putImageData(d, 0, 0); } };
  const step = (n, t, d) => h('div', { style: { display: 'grid', gridTemplateColumns: '24px 1fr', gap: '8px', fontSize: '12px' } }, h('b', { style: { color: '#ff4d4d' } }, n), h('div', {}, h('b', {}, t), ' ', h('span', { style: { opacity: .6 } }, d)));
  root.append(h('div', { style: { position: 'absolute', inset: 0, background: 'repeating-linear-gradient(90deg,#1f2023 0 60px,#1b1c1e 60px 120px)', opacity: .6 } }), h('div', { style: { position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', width: '860px', background: '#242528', border: '1px solid #3a3b3f', borderRadius: '10px', padding: '18px', display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '20px', boxShadow: '0 20px 60px #000c' } }, h('div', { style: { gridColumn: '1/-1' } }, h('span', { style: { font: "700 26px 'VT323',monospace", letterSpacing: '.2em' } }, '✺ A NEW LADYBUG-ish'), h('span', { style: { fontSize: '11px', opacity: .5, marginLeft: '12px' } }, 'IMAGE EFFECTS STUDIO')), h('div', { style: { display: 'grid', gap: '10px' } }, cv, seg(['halftone', 'glitch', 'posterize'], P.fx, (v) => { P.fx = v; draw(); }), slider('Amount', 0, 1, P.amt, 0.01, (v) => { P.amt = v; draw(); }), slider('Cell size', 3, 16, P.size, 1, (v) => { P.size = v; draw(); }), h('div.k-row', {}, h('input', { type: 'color', value: P.tint, oninput: (e) => { P.tint = e.target.value; draw(); } }), 'Tint')), h('div', { style: { display: 'grid', gap: '12px', alignContent: 'start' } }, h('div', { style: { fontSize: '13px' } }, 'We have more features than ever before, and the analysis is way bigger too. Here is how to use it:'), step('01', 'Drop', 'an image or pick a sample'), step('02', 'Choose', 'an effect family'), step('03', 'Tune', 'amount, cell size and tint'), step('04', 'Compare', 'hold to see original'), step('05', 'Export', 'PNG or animated GIF'), h('div.k-row', { style: { marginTop: '10px' } }, h('button', { style: { background: '#ff4d4d', color: '#fff', border: 0, padding: '9px 16px', borderRadius: '4px' }, onclick: () => { const a = h('a', { download: 'ladybug.png', href: cv.toDataURL() }); a.click(); } }, '↓ Export PNG'), btn('Random', () => { P.fx = pick(['halftone', 'glitch', 'posterize']); P.amt = Math.random(); draw(); })))));
  draw();
  window.__demoProof = async () => { P.amt = 0.7; draw(); return 'halftone effect tuned live'; };
};
// ---------- R2D3 scrollytelling ML explainer (2026-10-05 12:00 KST)
V['r2d3-scrollytelling-ml-explainer'] = (root, T) => {
  theme(root, T, { bg: '#ffffff', fg: '#111111', ac: '#5aa33e', dark: false, line: '#0000001a' });
  const SANS = "'Inter Variable', Helvetica, Arial, sans-serif";
  root.style.background = '#fff'; root.style.color = '#222'; root.style.fontFamily = SANS; root.style.overflowY = 'auto'; root.style.overflowX = 'hidden'; root.style.scrollBehavior = 'smooth';
  const NY = '#1d5a8a', SF = '#5fa83f';
  root.append(h('style', {}, `
    .rd-wrap{display:grid;grid-template-columns:minmax(380px,560px) 1fr;max-width:1440px;margin:0 auto;padding:0 0 0 150px;position:relative}
    .rd-logo{position:absolute;left:150px;top:14px;width:40px;height:40px;border:3px solid #111;font:500 13px/14px ${SANS};padding:3px 5px;box-sizing:border-box;z-index:3;background:#fff}
    .rd-step{min-height:88vh;padding:0 40px 0 0;display:flex;flex-direction:column;justify-content:center;opacity:.28;transition:opacity .5s}
    .rd-step.on{opacity:1}.rd-step:first-child{opacity:1;min-height:calc(100vh - 60px);justify-content:flex-start;padding-top:110px}
    .rd-step h1{font:400 44px/1.08 ${SANS};letter-spacing:-.01em;margin:0 0 30px;color:#111;max-width:330px}
    .rd-step p{font:400 16px/1.6 ${SANS};color:#333;max-width:330px;margin:0 0 16px}
    .rd-step h2{font:600 22px/1.25 ${SANS};margin:0 0 14px;color:#111;max-width:330px}
    .rd-lang{font-size:12px;color:#666;margin:0 0 22px;display:flex;gap:6px;align-items:center}.rd-lang select{font-size:12px;border:1px solid #999;width:108px}
    .rd-scroll{font:700 14px ${SANS};letter-spacing:.04em;text-align:center;width:330px;margin-top:8px;cursor:pointer}.rd-scroll i{display:block;width:0;height:0;margin:6px auto;border:14px solid transparent;border-top:8px solid #111;border-bottom:0;animation:rdB 1.6s ease-in-out infinite}
    @keyframes rdB{50%{transform:translateY(5px)}}
    .rd-viz{position:sticky;top:0;height:calc(100vh - 44px);display:grid;place-items:center start}
    .rd-viz svg{width:min(640px,100%);height:auto;overflow:visible}
    .rd-viz .d{transition:transform 1s cubic-bezier(.6,0,.3,1),opacity .6s}
    .rd-viz .fade{transition:opacity .7s}
    .rd-ax{font:11px ${SANS};fill:#888}.rd-lab{font:600 12px ${SANS};fill:#333}
    .rd-dots{position:fixed;right:22px;top:50%;transform:translateY(-50%);display:grid;gap:8px;z-index:4}
    .rd-dots b{width:8px;height:8px;border-radius:50%;background:#ccc;cursor:pointer;transition:all .3s}.rd-dots b.on{background:#111;transform:scale(1.3)}
    .k-root .rd-node{font:600 12px ${SANS}}
  `));
  const R = rng(11);
  const homes = Array.from({ length: 140 }, (_, i) => { const sf = i % 2 === 0; const ele = sf ? Math.max(1, 10 + R() ** 1.2 * 230 - (R() < .3 ? 30 : 0)) : Math.max(1, R() ** 2.3 * 75); return { sf, ele, ppsf: sf ? 450 + R() * 1100 : 620 + R() ** .8 * 1500, beds: 1 + Math.floor(R() * 4), bath: 1 + Math.floor(R() * 3), year: 1890 + Math.floor(R() * 125), sqft: 500 + R() ** 1.5 * 3500, price: 0.3 + R() ** 2 * 4 }; });
  const W = 640, H = 620, FEAT = ['beds', 'bath', 'price', 'year', 'sqft', 'ppsf'];
  const ext = (k) => [Math.min(...homes.map((d) => d[k])), Math.max(...homes.map((d) => d[k]))];
  const EX = Object.fromEntries([...FEAT, 'ele'].map((k) => [k, ext(k)]));
  const nrm = (k, v) => (v - EX[k][0]) / (EX[k][1] - EX[k][0] || 1);
  // scatterplot matrix (upper-right triangle, like the intro)
  const CS = 78, matrix = s('g', { class: 'fade' });
  FEAT.forEach((fy, r) => FEAT.forEach((fx, c) => { if (c < r) return; const x0 = c * (CS + 6), y0 = r * (CS + 6); homes.forEach((d) => { const jx = (R() - .5) * 4, jy = (R() - .5) * 4; matrix.append(s('circle', { cx: x0 + 4 + nrm(fx, d[fx]) * (CS - 8) + jx, cy: y0 + CS - 4 - nrm(fy === fx ? 'ele' : fy, fy === fx ? d.ele : d[fy]) * (CS - 8) + jy, r: 1.6, fill: d.sf ? SF : NY, opacity: .55 })); }); }));
  const axes = s('g', { class: 'fade', opacity: 0 }), deco = s('g', { class: 'fade', opacity: 0 });
  const dots = homes.map((d) => s('circle', { class: 'd', r: 4, cx: 0, cy: 0, fill: d.sf ? SF : NY, opacity: 0, stroke: '#fff', 'stroke-width': .6 }));
  const svg = s('svg', { viewBox: `-10 -10 ${W + 20} ${H + 20}` }, matrix, axes, deco, s('g', {}, ...dots));
  const X = (e) => 40 + (e / 250) * (W - 80);
  const put = (el, x, y, o = .9) => { el.style.transform = `translate(${x}px,${y}px)`; el.setAttribute('opacity', o); };
  const axisX = (label, y) => [s('line', { x1: 40, x2: W - 40, y1: y, y2: y, stroke: '#bbb' }), ...[0, 50, 100, 150, 200, 250].map((v) => s('g', {}, s('line', { x1: X(v), x2: X(v), y1: y, y2: y + 5, stroke: '#bbb' }), s('text', { class: 'rd-ax', x: X(v), y: y + 18, 'text-anchor': 'middle' }, v + 'm'))), s('text', { class: 'rd-lab', x: W / 2, y: y + 38, 'text-anchor': 'middle' }, label)];
  const legend = (y) => s('g', {}, s('circle', { cx: 48, cy: y, r: 5, fill: NY }), s('text', { class: 'rd-ax', x: 58, y: y + 4 }, 'New York'), s('circle', { cx: 130, cy: y, r: 5, fill: SF }), s('text', { class: 'rd-ax', x: 140, y: y + 4 }, 'San Francisco'));
  const SPLIT = 73;
  const acc = () => { const L = homes.filter((d) => d.ele <= SPLIT), Rr = homes.filter((d) => d.ele > SPLIT); return { L, Rr, ok: (L.filter((d) => !d.sf).length + Rr.filter((d) => d.sf).length) / homes.length }; };
  const STAGES = [
    () => { matrix.setAttribute('opacity', 1); axes.setAttribute('opacity', 0); deco.setAttribute('opacity', 0); homes.forEach((d, i) => put(dots[i], 5 * (CS + 6) + 4 + nrm('sqft', d.sqft) * (CS - 8), 5 * (CS + 6) + CS - 4 - nrm('ppsf', d.ppsf) * (CS - 8), 0)); },
    () => { matrix.setAttribute('opacity', 0); axes.replaceChildren(...axisX('Elevation', 470), legend(20)); axes.setAttribute('opacity', 1); deco.setAttribute('opacity', 0); const R2 = rng(5); homes.forEach((d, i) => put(dots[i], X(d.ele), 300 + (R2() - .5) * 200)); },
    () => { matrix.setAttribute('opacity', 0); axes.replaceChildren(...axisX('Elevation', 470), legend(20)); axes.setAttribute('opacity', 1); deco.setAttribute('opacity', 0); const bins = {}; [...homes].sort((a, b) => a.sf - b.sf).forEach((d) => { const b = Math.floor(d.ele / 10); const n = (bins[b] = (bins[b] || 0) + 1); put(dots[homes.indexOf(d)], X(b * 10 + 5), 462 - n * 9); }); },
    () => { STAGES[2](); const x = X(SPLIT); deco.replaceChildren(s('rect', { x, y: 40, width: W - 40 - x, height: 430, fill: SF, opacity: .08 }), s('line', { x1: x, x2: x, y1: 40, y2: 470, stroke: '#111', 'stroke-dasharray': '4 4' }), s('text', { class: 'rd-lab', x: x + 8, y: 64 }, `elevation > ${SPLIT}m`), s('text', { class: 'rd-ax', x: x + 8, y: 82 }, '→ classify as San Francisco')); deco.setAttribute('opacity', 1); },
    () => { matrix.setAttribute('opacity', 0); const Y = (p) => 450 - ((p - 400) / 1800) * 400; axes.replaceChildren(...axisX('Elevation', 470), s('line', { x1: 40, x2: 40, y1: 40, y2: 470, stroke: '#bbb' }), ...[500, 1000, 1500, 2000].map((p) => s('text', { class: 'rd-ax', x: 34, y: Y(p) + 4, 'text-anchor': 'end' }, '$' + p)), s('text', { class: 'rd-lab', x: -14, y: 250, transform: 'rotate(-90 -14 250)', 'text-anchor': 'middle' }, 'Price per sqft'), legend(20)); axes.setAttribute('opacity', 1); const x = X(SPLIT), yy = Y(1776); deco.replaceChildren(s('rect', { x, y: 40, width: W - 40 - x, height: 430, fill: SF, opacity: .08 }), s('rect', { x: 40, y: 40, width: x - 40, height: yy - 40, fill: NY, opacity: .08 }), s('line', { x1: x, x2: x, y1: 40, y2: 470, stroke: '#111', 'stroke-dasharray': '4 4' }), s('line', { x1: 40, x2: x, y1: yy, y2: yy, stroke: '#111', 'stroke-dasharray': '4 4' }), s('text', { class: 'rd-ax', x: 46, y: yy - 8 }, '> $1,776 / sqft → New York')); deco.setAttribute('opacity', 1); homes.forEach((d, i) => put(dots[i], X(d.ele), Y(d.ppsf))); },
    () => { matrix.setAttribute('opacity', 0); axes.setAttribute('opacity', 0); const { L, Rr, ok } = acc(); deco.replaceChildren(s('rect', { x: W / 2 - 90, y: 30, width: 180, height: 34, rx: 4, fill: '#111' }), s('text', { class: 'rd-node', x: W / 2, y: 52, fill: '#fff', 'text-anchor': 'middle' }, `elevation > ${SPLIT}m ?`), s('path', { d: `M${W / 2} 64 C ${W / 2} 120, 170 110, 170 170`, fill: 'none', stroke: '#999', 'stroke-width': 2 }), s('path', { d: `M${W / 2} 64 C ${W / 2} 120, 470 110, 470 170`, fill: 'none', stroke: '#999', 'stroke-width': 2 }), s('text', { class: 'rd-ax', x: 210, y: 120 }, 'no'), s('text', { class: 'rd-ax', x: 420, y: 120 }, 'yes'), s('text', { class: 'rd-lab', x: 170, y: 560, 'text-anchor': 'middle' }, `${L.length} homes · mostly New York`), s('text', { class: 'rd-lab', x: 470, y: 560, 'text-anchor': 'middle' }, `${Rr.length} homes · San Francisco`), s('text', { class: 'rd-lab', x: W / 2, y: 600, 'text-anchor': 'middle', fill: '#111' }, `accuracy ${Math.round(ok * 100)}%`)); deco.setAttribute('opacity', 1); const place = (arr, cx) => [...arr].sort((a, b) => a.sf - b.sf).forEach((d, k) => put(dots[homes.indexOf(d)], cx - 66 + (k % 12) * 12, 530 - Math.floor(k / 12) * 12)); place(L, 170); place(Rr, 470); },
  ];
  const TXT = [null,
    ['First, some intuition', 'Let\'s say you had to determine whether a home is in San Francisco or in New York. In machine-learning terms, categorizing data points is a classification task.', 'Since San Francisco is relatively hilly, the elevation of a home may be a good way to distinguish the two cities.'],
    ['Adding nuance', 'Based on the home-elevation data, homes above a certain elevation tend to be in San Francisco. A histogram makes the overlap easier to read.'],
    ['Drawing boundaries', `A simple rule: if a home sits higher than ${SPLIT} m, call it San Francisco. Everything to the right of the dashed line is classified as SF.`],
    ['Adding a dimension', 'Adding price per square foot gives a second boundary. Expensive low-elevation homes are very likely New York. Statistical learning finds these boundaries automatically.'],
    ['Your first fork', 'A decision tree applies these if-then splits one after another. Each home falls down the tree into a bucket; the share sorted correctly is the model\'s accuracy.', 'Scroll back up to watch the data re-form.'],
  ];
  const steps = [h('section.rd-step.on', {}, h('h1', {}, 'A Visual Introduction to Machine Learning'), h('div.rd-lang', {}, '🌐', h('select', {}, ...['English', '한국어', '日本語', 'Español', 'Français'].map((l) => h('option', {}, l)))), h('p', { html: 'In machine learning, computers apply <b>statistical learning</b> techniques to automatically identify patterns in data. These techniques can be used to make highly accurate predictions.' }), h('p', { html: '<i>Keep scrolling.</i> Using a data set about homes, we will create a machine learning model to distinguish homes in New York from homes in San Francisco.' }), h('div.rd-scroll', { onclick: () => go(1) }, 'SCROLL', h('i')))];
  TXT.slice(1).forEach(([t, ...ps]) => steps.push(h('section.rd-step', {}, h('h2', {}, t), ...ps.map((p) => h('p', {}, p)))));
  steps.push(h('section', { style: { minHeight: '40vh' } }));
  const nav = h('div.rd-dots', {}, ...STAGES.map((_, i) => h('b', { onclick: () => go(i), title: 'step ' + (i + 1) })));
  root.append(h('div.rd-wrap', {}, h('div.rd-logo', {}, 'R2', h('br'), 'D3'), h('div', {}, ...steps), h('div.rd-viz', {}, svg)), nav);
  let cur = -1;
  const set = (i) => { if (i === cur) return; cur = i; STAGES[i](); steps.forEach((el, k) => el.classList && k < STAGES.length && el.classList.toggle('on', k === i || (k === 0 && i === 0))); [...nav.children].forEach((b, k) => b.classList.toggle('on', k === i)); };
  const go = (i) => { root.style.scrollBehavior = 'smooth'; root.scrollTop = steps[i].offsetTop - (i ? root.clientHeight * 0.15 : 0); };
  const onScroll = () => { const mid = root.scrollTop + root.clientHeight * 0.55; let i = 0; steps.slice(0, STAGES.length).forEach((el, k) => { if (el.offsetTop <= mid) i = k; }); set(i); };
  root.addEventListener('scroll', onScroll, { passive: true });
  set(0);
  window.__demoProof = async () => { const seen = []; for (const i of [1, 2, 3, 4, 5]) { root.style.scrollBehavior = 'auto'; root.scrollTop = steps[i].offsetTop - root.clientHeight * 0.15; onScroll(); seen.push(cur); await sleep(60); } const a = Math.round(acc().ok * 100); root.scrollTop = 0; onScroll(); await sleep(50); return `scrolled stages ${seen.join(',')} (tree accuracy ${a}%), back to intro stage ${cur}`; };
};

export function mount(root, variant, opts, T) { (V[variant] || V['alg0-step-visualizer'])(root, T); }
