import { h, s, css, drag, localPos, clamp, copy, toast, sleep, hexToRgb, rgbToHex, hsl, gesture } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle, codebox } from '../kit.js';
const shade = (hex, amt) => { const [r, g, b] = hexToRgb(hex); return rgbToHex(r + amt, g + amt, b + amt); };
const V = {};
V['neumorph-softui-generator'] = (root, T) => {
  theme(root, T, { bg: '#e0e0e0', fg: '#001f3f', panel: '#e0e0e0', ac: '#001f3f', dark: false });
  const P = { color: '#e0e0e0', size: 300, radius: 50, dist: 20, int: 0.15, blur: 60, shape: 'flat', light: 'tl' };
  const el = h('div'); let code; const dirs = { tl: [1, 1], tr: [-1, 1], br: [-1, -1], bl: [1, -1] };
  const cssOf = () => { const [dx, dy] = dirs[P.light]; const d = P.dist, a = Math.round(P.int * 255); const dark = shade(P.color, -a / 2), light = shade(P.color, a / 2); const bg = P.shape === 'concave' ? `linear-gradient(145deg, ${shade(P.color, -12)}, ${shade(P.color, 12)})` : P.shape === 'convex' ? `linear-gradient(145deg, ${shade(P.color, 12)}, ${shade(P.color, -12)})` : P.color; const ins = P.shape === 'pressed' ? 'inset ' : ''; return `border-radius: ${P.radius}px;\nbackground: ${bg};\nbox-shadow: ${ins}${dx * d}px ${dy * d}px ${P.blur}px ${dark},\n            ${ins}${-dx * d}px ${-dy * d}px ${P.blur}px ${light};`; };
  code = codebox(() => cssOf());
  const draw = () => { el.style.cssText = `width:${P.size}px;height:${P.size}px;` + cssOf().replace(/\n\s*/g, ' '); root.style.setProperty('--bg', P.color); root.style.background = P.color; code.update(); };
  const stage = h('div', { style: { position: 'relative', width: '520px', height: '520px', display: 'grid', placeItems: 'center' } }, el, ...Object.keys(dirs).map((k) => h('button', { style: { position: 'absolute', [k[0] === 't' ? 'top' : 'bottom']: '10px', [k[1] === 'l' ? 'left' : 'right']: '10px', width: '30px', height: '30px', background: P.light === k ? '#ffd43b' : 'transparent', border: '2px solid #001f3f33', borderRadius: '50%' }, onclick: (e) => { P.light = k; stage.querySelectorAll('button').forEach((b) => (b.style.background = 'transparent')); e.target.style.background = '#ffd43b'; draw(); } })));
  const pn = h('div', { style: { width: '380px', borderRadius: '20px', padding: '24px', display: 'grid', gap: '14px', boxShadow: '12px 12px 30px #bebebe,-12px -12px 30px #ffffff' } }, h('div.k-row', {}, 'Pick a color:', h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); } }), 'or', h('code', {}, P.color)), slider('Size', 10, 410, P.size, 1, (v) => { P.size = v; draw(); }, (v) => v + 'px'), slider('Radius', 0, 150, P.radius, 1, (v) => { P.radius = v; draw(); }), slider('Distance', 5, 50, P.dist, 1, (v) => { P.dist = v; draw(); }), slider('Intensity', 0.01, 0.6, P.int, 0.01, (v) => { P.int = v; draw(); }), slider('Blur', 0, 100, P.blur, 1, (v) => { P.blur = v; draw(); }), seg([['flat', 'Flat'], ['concave', 'Concave'], ['convex', 'Convex'], ['pressed', 'Pressed']], 'flat', (v) => { P.shape = v; draw(); }), code, btn('Copy', () => copy(code.textContent), 'pri'));
  root.append(h('div', { style: { textAlign: 'center', padding: '20px 0 0' } }, h('div', { style: { font: '800 32px Inter Variable' } }, 'Neumorphism-ish'), h('div', { style: { opacity: .6 } }, 'Generate Soft-UI CSS code')), h('div', { style: { display: 'flex', justifyContent: 'center', gap: '60px', alignItems: 'center', marginTop: '10px' } }, stage, pn));
  root.style.setProperty('--codebg', '#001f3f');
  draw();
  window.__demoProof = async () => { P.shape = 'convex'; P.dist = 26; draw(); return 'convex shape, distance 26'; };
};
function glassCss(P) { return `background: rgba(${hexToRgb(P.color).join(', ')}, ${P.alpha});\nborder-radius: 16px;\nbox-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);\nbackdrop-filter: blur(${P.blur}px) saturate(${P.sat}%);\n-webkit-backdrop-filter: blur(${P.blur}px);\nborder: 1px solid rgba(255, 255, 255, ${P.outline});`; }
V['glassmorphism-css-studio'] = (root, T) => {
  theme(root, T, { bg: '#f25f5c', fg: '#fff', dark: true });
  root.style.background = 'linear-gradient(160deg,#ff6b6b 0%,#f06595 40%,#ffa94d 100%)';
  const P = { blur: 5, alpha: 0.2, sat: 180, color: '#ffffff', outline: 0.3 };
  const card = h('div', { style: { position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-40%)', width: '520px', padding: '24px', color: '#fff' } });
  const code = codebox(() => glassCss(P)); root.style.setProperty('--codebg', '#0006');
  const draw = () => { card.style.cssText += glassCss(P).replace(/\n/g, ' '); code.update(); };
  card.append(h('div', { style: { textAlign: 'center', fontWeight: 800 } }, 'Glassmorphism CSS Generator'), slider('Blur value', 0, 20, P.blur, 0.5, (v) => { P.blur = v; draw(); }), slider('Transparency', 0, 1, P.alpha, 0.01, (v) => { P.alpha = v; draw(); }), slider('Saturation', 0, 200, P.sat, 1, (v) => { P.sat = v; draw(); }), h('div.k-row', {}, 'Color', h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); } }), toggle('Outline', true, (v) => { P.outline = v ? 0.3 : 0; draw(); })), code, btn('Copy CSS', () => copy(code.textContent), 'pri'));
  root.append(h('div', { style: { position: 'absolute', top: '30px', width: '100%', textAlign: 'center', font: '300 88px/1 Inter Variable', letterSpacing: '.06em', opacity: .9 } }, 'GLASSMORPHISM'), h('div', { style: { position: 'absolute', left: '18%', top: '30%', width: '220px', height: '220px', borderRadius: '50%', background: 'linear-gradient(#ffd43b,#ff922b)' } }), h('div', { style: { position: 'absolute', right: '20%', bottom: '12%', width: '160px', height: '160px', borderRadius: '30px', background: 'linear-gradient(#845ef7,#339af0)', transform: 'rotate(20deg)' } }), card);
  draw();
  window.__demoProof = async () => { P.blur = 12; P.alpha = 0.28; draw(); return 'blur 12px, alpha .28 applied live'; };
};
V['glassmorphism-live-css-studio'] = (root, T) => {
  theme(root, T, { bg: '#0a0a0a', fg: '#fff', ac: '#6c47ff', dark: true });
  const P = { blur: 16, alpha: 0.15, sat: 160, color: '#ffffff', outline: 0.18 };
  const orb = h('div', { style: { position: 'absolute', right: '12%', top: '22%', width: '380px', height: '380px', borderRadius: '44% 56% 60% 40%', background: 'conic-gradient(from 120deg,#ff3cac,#784ba0,#2b86c5,#00e0ff,#ff3cac)', filter: 'saturate(1.3)', animation: 'spin 14s linear infinite' } });
  css('@keyframes spin{to{transform:rotate(360deg)}}');
  const card = h('div', { style: { position: 'absolute', right: '8%', top: '30%', width: '380px', padding: '22px', display: 'grid', gap: '12px' } });
  const code = codebox(() => glassCss(P)); root.style.setProperty('--codebg', '#000c');
  const draw = () => { card.style.cssText += glassCss(P).replace(/\n/g, ' '); code.update(); };
  card.append(h('b', {}, 'Settings'), slider('Blur value', 0, 40, P.blur, 1, (v) => { P.blur = v; draw(); }), slider('Transparency', 0, 1, P.alpha, 0.01, (v) => { P.alpha = v; draw(); }), slider('Depth', 0, 1, P.outline, 0.01, (v) => { P.outline = v; draw(); }), code, btn('Copy CSS', () => copy(code.textContent, 'CSS copied to clipboard'), 'pri'));
  root.append(h('div.k-row', { style: { height: '54px', padding: '0 40px', gap: '26px', borderBottom: '1px solid #222' } }, h('b', {}, '▲ hype-ish'), 'Challenges', 'Tutorials', 'Courses', 'Tools', h('span', { style: { flex: 1 } }), h('span.k-btn.pri', {}, 'Get Pro')), h('div', { style: { position: 'absolute', left: '8%', top: '26%', maxWidth: '480px' } }, h('span', { style: { background: '#ffffff14', padding: '6px 12px', borderRadius: '99px', fontSize: '13px' } }, 'Learn Glassmorphism'), h('h1', { style: { fontSize: '58px', lineHeight: 1.05, margin: '18px 0' } }, 'The original generator for Glassmorphism'), h('p', { style: { opacity: .7 } }, 'Made by the person who created the glassmorphism trend.'), btn('Learn more →', () => {}, 'pri')), orb, card);
  draw();
  window.__demoProof = async () => { P.blur = 24; draw(); await copy(code.textContent, 'CSS copied to clipboard'); return 'depth/blur adjusted + copy toast'; };
};
V['claymorph-component-studio'] = (root, T) => {
  theme(root, T, { bg: '#0f0f0f', fg: '#fff', ac: '#ff5a1f', dark: true });
  const P = { depth: 8, radius: 28, hi: 0.5, color: '#2a2a2a' }; let pick = 'Button';
  const clay = () => `background:${P.color};border-radius:${P.radius}px;box-shadow: ${P.depth}px ${P.depth}px ${P.depth * 2}px #0009, inset -${P.depth / 2}px -${P.depth / 2}px ${P.depth}px #0006, inset ${P.depth / 2}px ${P.depth / 2}px ${P.depth}px rgba(255,255,255,${P.hi * 0.25});`;
  const COMPS = ['Button', 'Card', 'Toggle', 'Input', 'Badge', 'Avatar', 'Slider', 'Checkbox', 'Tabs', 'Alert', 'Progress', 'Tooltip'];
  const gridEl = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(6,1fr)', gap: '14px' } }); const prev = h('div', { style: { display: 'grid', placeItems: 'center', height: '220px' } }); const code = codebox(() => `.clay-${pick.toLowerCase()} {\n  ${clay().replace(/;\s*/g, ';\n  ')}\n}`);
  const renderPrev = () => { const st = clay(); prev.replaceChildren(pick === 'Card' ? h('div', { style: { width: '260px', height: '160px', padding: '20px', cssText: st } }, 'Clay card') : pick === 'Toggle' ? h('div', { style: { width: '120px', height: '56px', cssText: st, position: 'relative' } }, h('i', { style: { position: 'absolute', right: '8px', top: '8px', width: '40px', height: '40px', borderRadius: '50%', background: '#ff5a1f' } })) : h('div', { style: { padding: '18px 34px', cssText: st, fontWeight: 700 } }, pick)); prev.firstChild.setAttribute('style', prev.firstChild.getAttribute('style') + st); };
  const draw = () => { gridEl.replaceChildren(...COMPS.map((c) => h('button', { onclick: () => { pick = c; draw(); }, style: { padding: '16px 8px', color: '#fff', border: pick === c ? '2px solid #ff5a1f' : '0', cssText: '' } }, c))); gridEl.querySelectorAll('button').forEach((b) => b.setAttribute('style', b.getAttribute('style') + clay() + 'color:#fff;padding:16px 8px;')); renderPrev(); code.update(); };
  root.append(h('div.k-row', { style: { height: '56px', padding: '0 40px', gap: '26px' } }, h('b', { style: { background: '#ff5a1f', color: '#000', padding: '4px 8px' } }, 'ROCOS-ish'), h('span', { style: { flex: 1 } }), 'Home', 'Components', 'Docs'), h('div', { style: { padding: '10px 60px', display: 'grid', gridTemplateColumns: '1fr 340px', gap: '30px' } }, h('div', {}, h('div', { style: { fontSize: '12px', letterSpacing: '.2em', opacity: .6 } }, 'LIVE CLAYMORPH STUDIO · 64 COMPONENTS'), h('h1', { style: { fontSize: '56px', margin: '8px 0 20px', lineHeight: 1 } }, 'Claymorphism UI Generator'), gridEl, prev), panel('Clay params', slider('Depth', 0, 20, P.depth, 1, (v) => { P.depth = v; draw(); }), slider('Radius', 0, 60, P.radius, 1, (v) => { P.radius = v; draw(); }), slider('Highlight', 0, 1, P.hi, 0.05, (v) => { P.hi = v; draw(); }), h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); } }), code, h('div.k-row', {}, btn('Copy CSS', () => copy(code.textContent), 'pri'), btn('Copy HTML', () => copy(`<button class="clay-${pick.toLowerCase()}">${pick}</button>`))))));
  draw();
  window.__demoProof = async () => { pick = 'Toggle'; P.depth = 12; draw(); return 'picked Toggle, depth 12'; };
};
V['css-shadow-palette-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fff', ac: '#c83fff', dark: false });
  const P = { oomph: 0.5, crisp: 0.5, lx: 0.3, ly: 0.2, bg: '#e8b8ff', tint: true, res: 0.5 };
  const shadows = (lvl) => { const n = Math.round(2 + P.res * 4); const [r, g, b] = P.tint ? hexToRgb(P.bg).map((v) => Math.round(v * 0.35)) : [0, 0, 0]; return Array.from({ length: n * lvl }, (_, i) => { const k = (i + 1) / n; const d = k * 4 * (0.5 + P.oomph); return `${(-P.lx * d * 2).toFixed(1)}px ${(P.ly * d * 3 + d).toFixed(1)}px ${(d * (2 - P.crisp * 1.5)).toFixed(1)}px hsl(${rgbToHsl3(r, g, b)} / ${(0.36 * (0.4 + P.oomph) / (i + 1)).toFixed(2)})`; }).join(', '); };
  const rgbToHsl3 = (r, g, b) => `${r} ${g} ${b}`.replace(/(\d+) (\d+) (\d+)/, (m, a, c, d) => `${Math.round(a / 2.55)}deg 30% 30%`);
  const left = h('div', { style: { position: 'relative', display: 'grid', alignContent: 'center', gap: '40px', padding: '40px 70px' } });
  const code = codebox(() => `:root {\n  --shadow-elevation-low: ${shadows(1)};\n  --shadow-elevation-medium: ${shadows(2).slice(0, 120)}…;\n}`);
  const draw = () => { left.style.background = P.bg; left.replaceChildren(...[['Low', 1], ['Medium', 2], ['High', 3]].map(([n, l]) => h('div', { style: { background: '#fff', borderRadius: '8px', height: '90px', width: `${200 + l * 40}px`, boxShadow: shadows(l), padding: '10px', fontSize: '12px', color: '#6b3a86' } }, `Top / ${n} elevation`))); dot.style.left = (1 - P.lx) * 100 + '%'; dot.style.top = P.ly * 100 + '%'; code.update(); };
  const pad = h('div', { style: { position: 'relative', height: '150px', background: '#f5f0ff', borderRadius: '10px', cursor: 'crosshair' } }); const dot = h('div', { style: { position: 'absolute', width: '18px', height: '18px', margin: '-9px', borderRadius: '50%', background: '#ffd43b', boxShadow: '0 0 0 4px #ffd43b55' } }); pad.append(dot);
  drag(pad, { start: (e) => { const p = localPos(e, pad); P.lx = 1 - p.x / p.w; P.ly = p.y / p.h; draw(); }, move: (e) => { const p = localPos(e, pad); P.lx = clamp(1 - p.x / p.w, 0, 1); P.ly = clamp(p.y / p.h, 0, 1); draw(); } });
  root.style.display = 'grid'; root.style.gridTemplateColumns = '1fr 520px';
  root.append(left, h('div', { style: { padding: '26px', display: 'grid', gap: '14px', alignContent: 'start' } }, h('div', { style: { fontSize: '28px', fontWeight: 800, textAlign: 'right' } }, 'Shadow Palette ', h('span', { style: { color: '#c83fff' } }, 'Generator')), h('div', { style: { opacity: .6, textAlign: 'right', fontSize: '13px' } }, 'Create a set of lush, realistic CSS shadows'), h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' } }, slider('Oomph', 0, 1, P.oomph, 0.01, (v) => { P.oomph = v; draw(); }), slider('Crispy', 0, 1, P.crisp, 0.01, (v) => { P.crisp = v; draw(); })), h('div.k-h', {}, 'Light position'), pad, h('div.k-row', {}, 'Background color', h('input', { type: 'color', value: P.bg, oninput: (e) => { P.bg = e.target.value; draw(); } }), toggle('Tint shadows', true, (v) => { P.tint = v; draw(); })), slider('Resolution', 0, 1, P.res, 0.01, (v) => { P.res = v; draw(); }), code, btn('Copy tokens', () => copy(code.textContent), 'pri')));
  draw();
  window.__demoProof = async () => { await gesture(pad, [[200, 60], [140, 40], [100, 30]]); P.oomph = 0.8; draw(); return 'moved light + oomph .8'; };
};
V['fancy-border-radius-blob'] = (root, T) => {
  theme(root, T, { bg: '#1b1446', fg: '#fff', ac: '#ff3d8b', dark: true });
  root.style.background = 'radial-gradient(80% 80% at 50% 30%,#2a1c63,#140e36)';
  let v = [30, 70, 70, 30, 30, 30, 70, 70];
  const S = 380; const box = h('div', { style: { position: 'relative', width: S + 'px', height: S + 'px', margin: '0 auto', border: '1px dashed #ffffff44' } });
  const blob = h('div', { style: { position: 'absolute', inset: 0, background: 'linear-gradient(45deg,#ff3d8b 0%,#a53dff 100%)' } }); box.append(blob);
  const val = () => `${v[0]}% ${100 - v[0]}% ${100 - v[1]}% ${v[1]}% / ${v[4]}% ${v[5]}% ${100 - v[5]}% ${100 - v[4]}%`;
  const inp = h('input', { style: { width: '460px', padding: '10px', background: '#fff', color: '#111', border: 0, fontFamily: 'monospace', fontSize: '14px' } });
  const handles = [[0, 'top', 'x'], [1, 'bottom', 'x'], [4, 'left', 'y'], [5, 'right', 'y']].map(([i, side, ax]) => { const k = h('div', { style: { position: 'absolute', width: '14px', height: '14px', margin: '-7px', borderRadius: '50%', background: '#fff', cursor: 'grab', boxShadow: '0 0 0 3px #ff3d8b', touchAction: 'none' } }); drag(k, { move: (e) => { const p = localPos(e, box); v[i] = Math.round(clamp((ax === 'x' ? p.x / p.w : p.y / p.h) * 100, 0, 100)); draw(); } }); k.side = side; k.i = i; box.append(k); return k; });
  const draw = () => { blob.style.borderRadius = val(); inp.value = val(); handles.forEach((k) => { const p = v[k.i]; Object.assign(k.style, k.side === 'top' ? { left: p + '%', top: '0%' } : k.side === 'bottom' ? { left: p + '%', top: '100%' } : k.side === 'left' ? { left: '0%', top: p + '%' } : { left: '100%', top: p + '%' }); }); };
  root.append(h('div', { style: { textAlign: 'center', padding: '30px 0 24px' } }, h('div', { style: { font: '800 30px Inter Variable', letterSpacing: '.12em' } }, 'FANCY-BORDER-RADIUS'), h('div', { style: { opacity: .7, marginTop: '8px' } }, 'Drag the handles to shape an 8-value border-radius blob.')), box, h('div.k-row', { style: { justifyContent: 'center', marginTop: '30px' } }, 'border-radius:', inp, btn('COPY', () => copy(inp.value), 'pri'), btn('🎲', () => { v = v.map(() => Math.round(Math.random() * 100)); draw(); })), h('div', { style: { textAlign: 'center', marginTop: '14px' } }, toggle('Custom size', false, (x) => (box.style.width = x ? '480px' : S + 'px'))));
  draw();
  window.__demoProof = async () => { v = [62, 18, 70, 30, 45, 76, 70, 70]; draw(); return 'reshaped via handles, CSS chip updated'; };
};
V['clippath-shape-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fff', ac: '#ff5a5f', dark: false });
  const SH = { Triangle: [[50, 0], [0, 100], [100, 100]], Trapezoid: [[20, 0], [80, 0], [100, 100], [0, 100]], Parallelogram: [[25, 0], [100, 0], [75, 100], [0, 100]], Rhombus: [[50, 0], [100, 50], [50, 100], [0, 50]], Pentagon: [[50, 0], [100, 38], [82, 100], [18, 100], [0, 38]], Hexagon: [[25, 0], [75, 0], [100, 50], [75, 100], [25, 100], [0, 50]], Star: [[50, 0], [61, 35], [98, 35], [68, 57], [79, 91], [50, 70], [21, 91], [32, 57], [2, 35], [39, 35]], Arrow: [[0, 20], [60, 20], [60, 0], [100, 50], [60, 100], [60, 80], [0, 80]], Message: [[0, 0], [100, 0], [100, 75], [75, 75], [75, 100], [50, 75], [0, 75]] };
  let pts = SH.Triangle.map((p) => p.slice());
  const box = h('div', { style: { position: 'relative', width: '520px', height: '520px' } });
  const img = h('div', { style: { position: 'absolute', inset: 0, background: 'linear-gradient(160deg,#1e3a8a 0%,#f59e0b 55%,#be123c 100%)' } }); const ghost = h('div', { style: { position: 'absolute', inset: 0, background: 'linear-gradient(160deg,#1e3a8a,#f59e0b,#be123c)', opacity: 0.15 } });
  box.append(ghost, img); const code = h('pre.k-code');
  const draw = () => { const cp = `polygon(${pts.map(([x, y]) => `${x}% ${y}%`).join(', ')})`; img.style.clipPath = cp; code.textContent = `clip-path: ${cp};`; box.querySelectorAll('.hd').forEach((e) => e.remove()); pts.forEach((p, i) => { const k = h('div.hd', { style: { position: 'absolute', left: p[0] + '%', top: p[1] + '%', width: '16px', height: '16px', margin: '-8px', borderRadius: '50%', background: '#fff', border: '3px solid #ff5a5f', cursor: 'grab', touchAction: 'none' } }); drag(k, { move: (e) => { const q = localPos(e, box); p[0] = Math.round(clamp(q.x / q.w * 100, 0, 100)); p[1] = Math.round(clamp(q.y / q.h * 100, 0, 100)); draw(); } }); box.append(k); }); };
  root.append(h('div', { style: { position: 'absolute', inset: 0, display: 'grid', gridTemplateColumns: '1fr 360px', padding: '30px 50px', gap: '30px' } }, h('div', { style: { display: 'grid', placeItems: 'center' } }, box, code), h('div', {}, h('b', { style: { fontSize: '20px' } }, 'Clippy-ish · CSS clip-path maker'), h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '10px', marginTop: '16px' } }, Object.entries(SH).map(([n, p]) => h('button', { onclick: () => { pts = p.map((x) => x.slice()); draw(); }, style: { border: '1px solid #eee', background: '#fff', borderRadius: '8px', padding: '10px 4px', fontSize: '11px' } }, h('div', { style: { height: '50px', background: '#ff5a5f', clipPath: `polygon(${p.map(([x, y]) => `${x}% ${y}%`).join(',')})`, marginBottom: '6px' } }), n))), h('div', { style: { marginTop: '16px' } }, toggle('Show outside clip-path', true, (v) => (ghost.style.opacity = v ? 0.15 : 0))), btn('Copy CSS', () => copy(code.textContent), 'pri'))));
  draw();
  window.__demoProof = async () => { pts[0] = [50, 8]; pts[1] = [6, 92]; draw(); return 'dragged polygon handles'; };
};
V['bezier-timing-curve-lab'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#e6007e', dark: false });
  let b = [0.17, 0.67, 0.83, 0.67]; const LIB = { ease: [0.25, 0.1, 0.25, 1], linear: [0, 0, 1, 1], 'ease-in': [0.42, 0, 1, 1], 'ease-out': [0, 0, 0.58, 1], 'ease-in-out': [0.42, 0, 0.58, 1], back: [0.68, -0.55, 0.27, 1.55] }; let cmp = 'ease';
  const S = 300, pad = 80; const svg = s('svg', { width: S + 60, height: S + pad * 2 + 20, style: 'overflow:visible' });
  const title = h('div', { style: { font: '700 44px JetBrains Mono Variable,monospace', textAlign: 'center', padding: '24px' } });
  const X = (x) => 30 + x * S, Y = (y) => pad + (1 - y) * S;
  const d1 = h('div', { style: { width: '40px', height: '40px', background: '#e6007e', borderRadius: '6px', position: 'relative', left: 0 } }), d2 = h('div', { style: { width: '40px', height: '40px', background: '#00a8ff', borderRadius: '6px', position: 'relative', left: 0 } });
  const draw = () => { const str = `cubic-bezier(${b.map((v) => +v.toFixed(2)).join(',')})`; title.textContent = str.replace(/0\./g, '.');
    svg.replaceChildren(s('rect', { x: 30, y: pad, width: S, height: S, fill: '#f7f7f7' }), s('line', { x1: X(0), y1: Y(0), x2: X(b[0]), y2: Y(b[1]), stroke: '#e6007e', 'stroke-width': 2 }), s('line', { x1: X(1), y1: Y(1), x2: X(b[2]), y2: Y(b[3]), stroke: '#00a8ff', 'stroke-width': 2 }), s('path', { d: `M${X(0)} ${Y(0)}C${X(b[0])} ${Y(b[1])},${X(b[2])} ${Y(b[3])},${X(1)} ${Y(1)}`, stroke: '#222', 'stroke-width': 4, fill: 'none' }), s('text', { x: 30, y: pad + S + 20, 'font-size': 11, fill: '#888' }, 'TIME'), s('text', { x: 4, y: pad + 10, 'font-size': 11, fill: '#888', transform: `rotate(-90 12 ${pad + 60})` }, 'PROGRESSION'));
    [[0, '#e6007e'], [2, '#00a8ff']].forEach(([i, c]) => { const k = s('circle', { cx: X(b[i]), cy: Y(b[i + 1]), r: 10, fill: c, stroke: '#fff', 'stroke-width': 3, style: 'cursor:grab' }); drag(k, { move: (e) => { const p = localPos(e, svg); b[i] = +clamp((p.x - 30) / S, 0, 1).toFixed(2); b[i + 1] = +((pad + S - p.y) / S).toFixed(2); draw(); } }); svg.append(k); }); };
  const go = () => { [d1, d2].forEach((d, i) => { d.style.transition = 'none'; d.style.left = '0px'; d.offsetWidth; d.style.transition = `left 1.2s cubic-bezier(${(i ? LIB[cmp] : b).join(',')})`; d.style.left = '260px'; }); };
  root.append(title, h('div', { style: { display: 'grid', gridTemplateColumns: '400px 1fr 1fr', gap: '30px', padding: '0 60px' } }, svg, h('div', {}, h('h3', {}, 'Preview & compare'), btn('GO', go, 'pri'), h('div', { style: { display: 'grid', gap: '14px', marginTop: '20px', background: '#f7f7f7', padding: '14px' } }, d1, d2)), h('div', {}, h('h3', {}, 'Library'), h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '10px' } }, Object.entries(LIB).map(([n, v]) => h('button', { onclick: () => { cmp = n; b = v.slice(); draw(); go(); }, style: { border: '1px solid #ddd', background: '#fff', padding: '8px', borderRadius: '6px' } }, s('svg', { viewBox: '0 0 100 100', width: 60, height: 60 }, s('path', { d: `M0 100C${v[0] * 100} ${100 - v[1] * 100},${v[2] * 100} ${100 - v[3] * 100},100 0`, stroke: '#222', fill: 'none', 'stroke-width': 4 })), h('div', { style: { fontSize: '11px' } }, n)))), btn('Copy', () => copy(title.textContent)))));
  draw();
  window.__demoProof = async () => { b = [0.17, 0.67, 0.83, 0.67]; draw(); go(); await sleep(700); return 'curve set, dual preview animated'; };
};
const EASE = { easeInSine: [0.12, 0, 0.39, 0], easeOutSine: [0.61, 1, 0.88, 1], easeInOutSine: [0.37, 0, 0.63, 1], easeInQuad: [0.11, 0, 0.5, 0], easeOutQuad: [0.5, 1, 0.89, 1], easeInOutQuad: [0.45, 0, 0.55, 1], easeInCubic: [0.32, 0, 0.67, 0], easeOutCubic: [0.33, 1, 0.68, 1], easeInOutCubic: [0.65, 0, 0.35, 1], easeInQuart: [0.5, 0, 0.75, 0], easeOutQuart: [0.25, 1, 0.5, 1], easeInOutQuart: [0.76, 0, 0.24, 1], easeInQuint: [0.64, 0, 0.78, 0], easeOutQuint: [0.22, 1, 0.36, 1], easeInOutQuint: [0.83, 0, 0.17, 1], easeInExpo: [0.7, 0, 0.84, 0], easeOutExpo: [0.16, 1, 0.3, 1], easeInOutExpo: [0.87, 0, 0.13, 1], easeInCirc: [0.55, 0, 1, 0.45], easeOutCirc: [0, 0.55, 0.45, 1], easeInOutCirc: [0.85, 0, 0.15, 1], easeInBack: [0.36, 0, 0.66, -0.56], easeOutBack: [0.34, 1.56, 0.64, 1], easeInOutBack: [0.68, -0.6, 0.32, 1.6] };
V['easing-curve-motion-catalog'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#1a8cff', dark: false }); root.style.overflow = 'auto';
  const gridEl = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(6,1fr)', gap: '14px', padding: '0 60px 40px' } });
  for (const [n, b] of Object.entries(EASE)) { const dot = s('circle', { cx: 5, cy: 95, r: 5, fill: '#1a8cff' }); const card = h('div', { style: { border: '1px solid #eee', borderRadius: '10px', padding: '12px', cursor: 'pointer' }, onclick: () => copy(`cubic-bezier(${b.join(', ')})`, `${n} copied`), onmouseenter: () => { dot.animate([{ transform: 'translate(0,0)' }, { transform: 'translate(90px,-90px)' }], { duration: 900, easing: `cubic-bezier(${b.join(',')})`, fill: 'forwards' }); } }, s('svg', { viewBox: '-5 -25 110 150', width: '100%', height: 110 }, s('path', { d: `M0 100C${b[0] * 100} ${100 - b[1] * 100},${b[2] * 100} ${100 - b[3] * 100},100 0`, stroke: '#27ae60', fill: 'none', 'stroke-width': 3 }), dot), h('div', { style: { fontSize: '12px', textAlign: 'center' } }, n)); card.dot = dot; gridEl.append(card); }
  root.append(h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 220px', gap: '20px', padding: '30px 60px 20px' } }, h('div', {}, h('b', { style: { fontSize: '20px' } }, 'Easing Functions Cheat Sheet'), h('p', { style: { opacity: .7, maxWidth: '640px' } }, 'Easing functions specify the rate of change of a parameter over time. Hover a card to see the motion; click to copy CSS.')), h('div', { style: { background: '#1a8cff', color: '#fff', padding: '14px', borderRadius: '8px', fontSize: '13px' } }, h('b', {}, 'Export'), h('div', {}, 'CSS · SCSS · JS'))), gridEl);
  window.__demoProof = async () => { gridEl.querySelectorAll('div').forEach((c, i) => c.dot && i < 60 && c.dispatchEvent(new Event('mouseenter'))); await sleep(950); return 'hover-played all curves'; };
};
const ANIMS = { 'scale-up-center': [{ transform: 'scale(.5)' }, { transform: 'scale(1)' }], 'rotate-center': [{ transform: 'rotate(0)' }, { transform: 'rotate(360deg)' }], 'slide-top': [{ transform: 'translateY(0)' }, { transform: 'translateY(-100px)' }], 'flip-horizontal': [{ transform: 'rotateY(0)' }, { transform: 'rotateY(180deg)' }], 'swing-top-fwd': [{ transform: 'rotateX(0)', transformOrigin: 'top' }, { transform: 'rotateX(180deg)', transformOrigin: 'top' }], 'bounce-in-top': [{ transform: 'translateY(-300px)', opacity: 0 }, { transform: 'translateY(0)', opacity: 1, offset: 0.4 }, { transform: 'translateY(-60px)', offset: 0.6 }, { transform: 'translateY(0)' }], 'fade-in': [{ opacity: 0 }, { opacity: 1 }], 'jello': [{ transform: 'scale3d(1,1,1)' }, { transform: 'scale3d(1.25,.75,1)' }, { transform: 'scale3d(.75,1.25,1)' }, { transform: 'scale3d(1.15,.85,1)' }, { transform: 'scale3d(1,1,1)' }], 'blur-in': [{ filter: 'blur(12px)', opacity: 0 }, { filter: 'blur(0)', opacity: 1 }], 'tracking-in-expand': [{ letterSpacing: '-.5em', opacity: 0 }, { opacity: 1 }] };
V['css-anim-preset-lab'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#e8364f', dark: false });
  const CAT = { basic: ['scale-up-center', 'rotate-center', 'slide-top', 'flip-horizontal', 'swing-top-fwd'], entrances: ['bounce-in-top', 'fade-in', 'blur-in', 'tracking-in-expand'], attention: ['jello'] };
  let cat = 'basic', anim = 'scale-up-center', dur = 0.5, ease = 'cubic-bezier(0.39,0.575,0.565,1)', favs = [];
  const box = h('div', { style: { width: '180px', height: '180px', background: '#e8364f', borderRadius: '6px', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: 700 } }, 'animista');
  const code = codebox(() => `.${anim} {\n  animation: ${anim} ${dur}s ${ease} both;\n}\n@keyframes ${anim} {\n${ANIMS[anim].map((k, i, a) => `  ${Math.round((k.offset ?? i / (a.length - 1)) * 100)}% { ${Object.entries(k).filter(([p]) => p !== 'offset').map(([p, v]) => `${p.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())}: ${v};`).join(' ')} }`).join('\n')}\n}`);
  const play = () => { box.getAnimations().forEach((a) => a.cancel()); box.animate(ANIMS[anim], { duration: dur * 1000, easing: ease, fill: 'both' }); code.update(); };
  const sub = h('div.k-row', { style: { justifyContent: 'center', flexWrap: 'wrap', gap: '6px' } });
  const drawSub = () => sub.replaceChildren(...CAT[cat].map((a) => h('button', { onclick: () => { anim = a; drawSub(); play(); }, style: { border: 0, borderBottom: a === anim ? '2px solid #e8364f' : '2px solid transparent', background: 'none', padding: '6px 8px', fontSize: '13px' } }, a)));
  root.append(h('div', { style: { textAlign: 'center', padding: '20px 0 6px' } }, h('div', { style: { font: '300 72px Georgia,serif', letterSpacing: '.02em' } }, 'animista'), h('div', { style: { fontSize: '11px', letterSpacing: '.3em', opacity: .6 } }, 'ON-DEMAND CSS ANIMATIONS LIBRARY')), h('div.k-row', { style: { justifyContent: 'center', gap: '24px', borderTop: '1px solid #eee', borderBottom: '1px solid #eee', padding: '10px' } }, Object.keys(CAT).map((c) => h('button', { onclick: () => { cat = c; anim = CAT[c][0]; drawSub(); play(); }, style: { border: 0, background: 'none', fontSize: '15px', textTransform: 'uppercase', letterSpacing: '.12em' } }, c))), sub,
    h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 380px', gap: '20px', padding: '20px 60px' } }, h('div', { style: { display: 'grid', placeItems: 'center', minHeight: '380px', background: '#fafafa', perspective: '600px' } }, box), h('div', { style: { display: 'grid', gap: '10px', alignContent: 'start' } }, slider('Duration', 0.1, 3, dur, 0.1, (v) => { dur = v; play(); }, (v) => v + 's'), select([['cubic-bezier(0.39,0.575,0.565,1)', 'ease-out-sine'], ['ease', 'ease'], ['linear', 'linear'], ['cubic-bezier(0.68,-0.55,0.265,1.55)', 'ease-in-out-back']], ease, (v) => { ease = v; play(); }), h('div.k-row', {}, btn('▶ Replay', play, 'pri'), btn('♥ Favorite', () => { favs.push(anim); toast(`Favorites: ${favs.length}`); }), btn('{ } Copy CSS', () => copy(code.textContent))), code)));
  drawSub(); code.update();
  window.__demoProof = async () => { cat = 'entrances'; anim = 'bounce-in-top'; drawSub(); play(); await sleep(400); return 'selected entrances/bounce-in-top, playing'; };
};
V['composable-css-anim-playground'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#6c5ce7', dark: false });
  const UT = ['fade', 'up', 'down', 'left', 'right', 'small', 'big', 'rotate-left', 'rotate-right', 'flip-up', 'skew']; let on = new Set(['fade', 'up', 'small']); let stagger = 80, dur = 600;
  const word = h('div', { style: { display: 'flex', gap: '40px', justifyContent: 'center', font: '400 90px Inter Variable', marginTop: '50px' } });
  const letters = 'AnimXYZ'.split('').map((c, i) => h('span', { style: { color: ['#222', '#222', '#222', '#222', '#6c5ce7', '#e84393', '#00b894'][i], display: 'inline-block' } }, c)); word.append(...letters);
  const kf = () => { const from = { opacity: on.has('fade') ? 0 : 1, transform: [on.has('up') ? 'translateY(-60px)' : '', on.has('down') ? 'translateY(60px)' : '', on.has('left') ? 'translateX(-60px)' : '', on.has('right') ? 'translateX(60px)' : '', on.has('small') ? 'scale(.5)' : '', on.has('big') ? 'scale(1.6)' : '', on.has('rotate-left') ? 'rotate(-90deg)' : '', on.has('rotate-right') ? 'rotate(90deg)' : '', on.has('flip-up') ? 'rotateX(90deg)' : '', on.has('skew') ? 'skewX(30deg)' : ''].join(' ') || 'none' }; return [from, { opacity: 1, transform: 'none' }]; };
  const play = () => letters.forEach((l, i) => l.animate(kf(), { duration: dur, delay: i * stagger, easing: 'cubic-bezier(.4,0,.2,1)', fill: 'both' }));
  const chips = h('div.k-row', { style: { justifyContent: 'center', flexWrap: 'wrap', gap: '8px', maxWidth: '760px', margin: '0 auto' } });
  const drawChips = () => chips.replaceChildren(...UT.map((u) => h('button', { onclick: () => { on.has(u) ? on.delete(u) : on.add(u); drawChips(); play(); }, style: { borderRadius: '99px', border: '1px solid #ddd', padding: '6px 12px', background: on.has(u) ? '#6c5ce7' : '#fff', color: on.has(u) ? '#fff' : '#333' } }, u)));
  const code = h('pre.k-code', { style: { maxWidth: '760px', margin: '14px auto' } });
  const upd = () => (code.textContent = `<XyzTransitionGroup xyz="${[...on].join(' ')} stagger-${stagger / 10}" style="--xyz-duration: ${dur}ms">`);
  root.append(word, h('div', { style: { textAlign: 'center', font: '800 34px Inter Variable', margin: '30px 0 20px' } }, 'The first composable CSS animation toolkit.'), chips, h('div.k-row', { style: { justifyContent: 'center', marginTop: '14px', gap: '20px' } }, h('div', { style: { width: '200px' } }, slider('Stagger', 0, 300, stagger, 10, (v) => { stagger = v; upd(); })), h('div', { style: { width: '200px' } }, slider('--xyz-duration', 100, 2000, dur, 50, (v) => { dur = v; upd(); })), btn('▶ Replay', play, 'pri')), code);
  drawChips(); upd(); setTimeout(play, 100);
  window.__demoProof = async () => { on.add('rotate-right'); drawChips(); upd(); play(); await sleep(1500); return 'added rotate-right utility, stagger replay'; };
};
V['css-clippath-transition-gallery'] = (root, T) => {
  theme(root, T, { bg: '#3b82f6', fg: '#fff', ac: '#1d4ed8', dark: true });
  const TR = { 'Circles': { 'circle:center': ['circle(0% at 50% 50%)', 'circle(75% at 50% 50%)'], 'circle:top-left': ['circle(0% at 0 0)', 'circle(150% at 0 0)'], 'circle:hesitate': ['circle(0%)', 'circle(125%)'] }, 'Squares': { 'square:center': ['inset(50% 50% 50% 50%)', 'inset(0 0 0 0)'], 'square:top-left': ['inset(0 100% 100% 0)', 'inset(0 0 0 0)'] }, 'Wipes': { 'wipe:right': ['inset(0 100% 0 0)', 'inset(0 0 0 0)'], 'wipe:down': ['inset(0 0 100% 0)', 'inset(0 0 0 0)'], 'wipe:cinematic': ['inset(50% 0 50% 0)', 'inset(0 0 0 0)'] }, 'Diamonds': { 'diamond:center': ['polygon(50% 50%,50% 50%,50% 50%,50% 50%)', 'polygon(50% -50%,150% 50%,50% 150%,-50% 50%)'] } };
  let cur = location.hash.slice(1) || 'circle:center', dur = 2.5, ease = 'cubic-bezier(.25,1,.30,1)';
  const find = (k) => Object.values(TR).find((g) => g[k])?.[k];
  const stage = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, right: '300px', background: '#3b82f6', overflow: 'hidden' } });
  const layer = h('div', { style: { position: 'absolute', inset: 0, background: '#3b82f6', color: '#fff', display: 'grid', placeItems: 'center', font: '300 90px Inter Variable' } }, 'transition.css ↖');
  stage.append(h('div', { style: { position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', font: '300 90px Inter Variable', background: '#fff', color: '#3b82f6' } }, 'transition.css'), layer);
  const play = () => { location.hash = cur; const [a, b] = find(cur) || find('circle:center'); layer.animate([{ clipPath: a }, { clipPath: b }], { duration: dur * 1000, easing: ease, fill: 'both' }); };
  const side = h('div', { style: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '300px', background: '#fff', color: '#222', padding: '18px', overflow: 'auto' } }, h('div', { style: { fontSize: '12px', opacity: .6 } }, 'Get started'), h('h2', { style: { color: '#3b82f6', margin: '4px 0' } }, 'Settings'), slider('--transition__duration', 0.3, 5, dur, 0.1, (v) => (dur = v), (v) => v + 's'), select([['cubic-bezier(.25,1,.30,1)', 'cubic-bezier(.25, 1, .30, 1)'], ['ease', 'ease'], ['linear', 'linear']], ease, (v) => (ease = v)),
    ...Object.entries(TR).map(([g, items]) => h('div', {}, h('h3', { style: { color: '#3b82f6', margin: '14px 0 4px' } }, g), ...Object.keys(items).map((k) => h('div', { style: { padding: '3px 0', fontFamily: 'monospace', fontSize: '12px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }, onclick: () => { cur = k; play(); } }, h('span', {}, `in:${k}`), h('span', { style: { color: '#3b82f6' } }, '▶'))))));
  root.append(stage, side); setTimeout(play, 200);
  window.__demoProof = async () => { cur = 'circle:center'; dur = 0.4; play(); await sleep(500); return 'hash-routed in:circle:center replayed'; };
};
V['css-keyframe-timeline-studio'] = (root, T) => {
  theme(root, T, { bg: '#f5f6f8', fg: '#1f2330', panel: '#fff', ac: '#4f6bff', dark: false });
  let kfs = [{ t: 0, x: 0, r: 0, s: 1 }, { t: 50, x: 260, r: 180, s: 1.4 }, { t: 100, x: 520, r: 360, s: 1 }], head = 0, sel = 1, playing = false;
  const obj = h('div', { style: { position: 'absolute', left: '80px', top: '140px', width: '90px', height: '90px', borderRadius: '18px', background: 'linear-gradient(135deg,#4f6bff,#b44fff)' } });
  const stage = h('div', { style: { position: 'relative', background: '#fff', borderRadius: '12px', boxShadow: '0 4px 20px #0001' } }, obj);
  const tl = h('div', { style: { position: 'relative', height: '80px', background: '#fff', borderRadius: '10px', margin: '0 0 0 0', cursor: 'pointer' } });
  const code = codebox(() => `@keyframes move {\n${kfs.map((k) => `  ${k.t}% { transform: translateX(${k.x}px) rotate(${k.r}deg) scale(${k.s}); }`).join('\n')}\n}`);
  const interp = (t) => { const sorted = kfs.slice().sort((a, b) => a.t - b.t); let a = sorted[0], b = sorted[sorted.length - 1]; for (let i = 0; i < sorted.length - 1; i++) if (t >= sorted[i].t && t <= sorted[i + 1].t) { a = sorted[i]; b = sorted[i + 1]; } const f = b.t === a.t ? 0 : (t - a.t) / (b.t - a.t); return { x: a.x + (b.x - a.x) * f, r: a.r + (b.r - a.r) * f, s: a.s + (b.s - a.s) * f }; };
  const draw = () => { const v = interp(head); obj.style.transform = `translateX(${v.x}px) rotate(${v.r}deg) scale(${v.s})`; tl.replaceChildren(h('div', { style: { position: 'absolute', left: '10px', right: '10px', top: '38px', height: '2px', background: '#e3e6ee' } }), ...kfs.map((k, i) => { const d = h('div', { style: { position: 'absolute', left: `calc(10px + ${k.t}% * 0.98)`, top: '30px', width: '16px', height: '16px', margin: '0 -8px', transform: 'rotate(45deg)', background: i === sel ? '#4f6bff' : '#fff', border: '2px solid #4f6bff', cursor: 'ew-resize' } }); drag(d, { start: () => { sel = i; }, move: (e) => { const p = localPos(e, tl); k.t = Math.round(clamp(p.x / p.w * 100, 0, 100)); draw(); } }); return d; }), h('div', { style: { position: 'absolute', left: `calc(10px + ${head}% * 0.98)`, top: 0, bottom: 0, width: '2px', background: '#ff4f6b' } })); code.update(); };
  drag(tl, { start: (e) => { if (e.target !== tl) return false; head = clamp(localPos(e, tl).x / tl.clientWidth * 100, 0, 100); draw(); }, move: (e) => { head = clamp(localPos(e, tl).x / tl.clientWidth * 100, 0, 100); draw(); } });
  const loop = () => { if (playing) { head = (head + 0.8) % 100; draw(); } requestAnimationFrame(loop); }; loop();
  root.style.display = 'grid'; root.style.gridTemplateColumns = '1fr 320px'; root.style.gridTemplateRows = '48px 1fr 150px'; root.style.gap = '12px'; root.style.padding = '0 14px 14px';
  root.append(h('div.k-row', { style: { gridColumn: '1/-1', gap: '14px' } }, h('b', {}, '◆ KeyframePad-ish'), h('span', { style: { flex: 1 } }), btn('▶ Play', (e) => { playing = !playing; e.target.textContent = playing ? '⏸ Pause' : '▶ Play'; }, 'pri'), btn('+ Keyframe', () => { kfs.push({ t: Math.round(head), ...interp(head) }); sel = kfs.length - 1; draw(); })), stage,
    panel('Keyframe', slider('translateX', 0, 700, kfs[sel].x, 1, (v) => { kfs[sel].x = v; draw(); }), slider('rotate', 0, 720, kfs[sel].r, 1, (v) => { kfs[sel].r = v; draw(); }), slider('scale', 0.2, 3, kfs[sel].s, 0.05, (v) => { kfs[sel].s = v; draw(); }), seg(['CSS', 'Tailwind', 'Framer', 'GSAP'], 'CSS', () => {}), code, btn('Copy', () => copy(code.textContent), 'pri')), h('div', { style: { gridColumn: '1/-1' } }, h('div.k-h', {}, 'Timeline · scrub the playhead'), tl));
  draw();
  window.__demoProof = async () => { head = 62; draw(); return 'scrubbed playhead to 62%'; };
};
V['svgartista-stroke-draw'] = (root, T) => {
  theme(root, T, { bg: '#1c1c1c', fg: '#ddd', panel: '#262626', ac: '#1abc9c', dark: true });
  let dur = 2, stagger = 0.2, color = '#1abc9c', fill = true;
  const svg = s('svg', { viewBox: '0 0 400 260', width: 620, height: 400 });
  const paths = ['M200 30L290 170H250L200 90L150 170H110Z', 'M170 150h60l-30-50z', 'M60 230h40M110 230h40M160 230h40M210 230h40M260 230h40M310 230h30'];
  const draw = () => { svg.replaceChildren(...paths.map((d, i) => s('path', { d, fill: 'none', stroke: color, 'stroke-width': i === 2 ? 6 : 5, 'stroke-linejoin': 'round' })), s('text', { x: 200, y: 222, 'text-anchor': 'middle', fill: 'none', stroke: color, 'stroke-width': 1.4, 'font-size': 42, 'font-weight': 800, 'font-family': 'Inter Variable', 'letter-spacing': 4 }, 'SVG ARTISTA'));
    [...svg.children].forEach((p, i) => { const L = p.getTotalLength ? (p.tagName === 'text' ? 1200 : p.getTotalLength()) : 1000; p.style.strokeDasharray = L; p.animate([{ strokeDashoffset: L, fillOpacity: 0 }, { strokeDashoffset: 0, fillOpacity: 0, offset: 0.8 }, { strokeDashoffset: 0, fillOpacity: fill ? 1 : 0 }], { duration: dur * 1000, delay: i * stagger * 1000, fill: 'both', easing: 'ease-in-out' }); if (fill) p.setAttribute('fill', color); }); code.update(); };
  const code = codebox(() => `svg path { stroke-dasharray: var(--len); animation: draw ${dur}s ease-in-out forwards; }\n${paths.map((_, i) => `svg path:nth-child(${i + 1}) { animation-delay: ${(i * stagger).toFixed(1)}s }`).join('\n')}\n@keyframes draw { to { stroke-dashoffset: 0; fill-opacity: ${fill ? 1 : 0} } }`);
  root.style.display = 'grid'; root.style.gridTemplateColumns = '280px 1fr'; root.style.gridTemplateRows = '40px 1fr';
  root.append(h('div.k-row', { style: { gridColumn: '1/-1', background: '#141414', padding: '0 14px' } }, h('b', {}, 'SVG Artista-ish'), h('span', { style: { flex: 1 } }), btn('Upload SVG', () => toast('Demo uses built-in logo')), btn('Get code', () => copy(code.textContent), 'pri')), panel('Stroke settings', slider('Duration', 0.5, 6, dur, 0.1, (v) => { dur = v; draw(); }), slider('Stagger', 0, 1, stagger, 0.05, (v) => { stagger = v; draw(); }), h('input', { type: 'color', value: color, oninput: (e) => { color = e.target.value; draw(); } }), toggle('Fill after stroke', true, (v) => { fill = v; draw(); }), select(['ease-in-out', 'linear', 'ease-out'], 'ease-in-out', () => draw()), btn('↻ Replay', draw, 'pri'), code), h('div', { style: { display: 'grid', placeItems: 'center', background: '#fff' } }, svg));
  draw();
  window.__demoProof = async () => { dur = 0.8; stagger = 0.1; draw(); await sleep(1200); return 'stroke-draw replayed and filled'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['neumorph-softui-generator'])(root, T); }
