import { h, s, drag, localPos, clamp, copy, toast, sleep, rng, pick, blip, drum, midi, audio, fitCanvas } from '../lib.js';
import { theme, slider, seg, select, btn } from '../kit.js';
const MONO = "'JetBrains Mono Variable',monospace";
const V = {};
function win95(title, body, { x = 100, y = 80, w = 360, hh = 240, dark = false } = {}) { const bar = h('div.k-row', { style: { background: 'linear-gradient(90deg,#000080,#1084d0)', color: '#fff', padding: '2px 4px', fontSize: '12px', fontWeight: 700, cursor: 'move', gap: '4px' } }, title, h('span', { style: { flex: 1 } }), ...['_', '□', '×'].map((c) => h('span', { style: { background: '#c0c0c0', color: '#000', width: '16px', height: '14px', display: 'grid', placeItems: 'center', fontSize: '10px', boxShadow: 'inset -1px -1px #000,inset 1px 1px #fff', cursor: 'pointer' }, onclick: c === '×' ? () => w0.remove() : null }, c))); const w0 = h('div', { style: { position: 'absolute', left: x + 'px', top: y + 'px', width: w + 'px', background: '#c0c0c0', boxShadow: 'inset -1px -1px #000,inset 1px 1px #fff,inset -2px -2px #808080', padding: '3px', zIndex: 10 } }, bar, h('div', { style: { height: hh + 'px', background: dark ? '#000' : '#fff', margin: '3px', boxShadow: 'inset 1px 1px #808080', overflow: 'auto', color: dark ? '#0f0' : '#000' } }, body)); let ox, oy; drag(bar, { start: (e) => { ox = e.clientX - w0.offsetLeft; oy = e.clientY - w0.offsetTop; w0.parentNode.append(w0); }, move: (e) => { w0.style.left = e.clientX - ox + 'px'; w0.style.top = e.clientY - oy + 'px'; } }); return w0; }
V['parody-desktop-os-sandbox'] = (root, T) => {
  theme(root, T, { bg: '#000', fg: '#ff0', ac: '#ff0', dark: true }); root.style.font = `14px/1.5 ${MONO}`;
  const boot = h('div', { style: { position: 'absolute', inset: 0, padding: '16px', color: '#ffea00', cursor: 'pointer' } }); const LINES = ['WINDOWS93-ish BIOS v0.93 (c) 2026 junk corp', 'CPU: Pentium-ish 93 MHz ........ OK', 'Memory Test: 640K ........ enough for anybody', 'Detecting IDE drives ... floppy A: [3½"]', '', 'Loading KERNEL93.SYS', 'Loading SILLY.DRV .......... done', 'Starting desktop ...', '', '▌ click anywhere to boot'];
  (async () => { for (const l of LINES) { boot.append(h('div', { style: { color: l.startsWith('▌') ? '#0f0' : '' } }, l || '\u00a0')); await sleep(60); } })();
  const desk = () => { boot.remove(); root.style.background = '#008080'; const icons = [['💾', 'My Computer'], ['🗑', 'Trash'], ['📁', 'Documents'], ['🎵', 'Radio'], ['🖥', 'Terminal'], ['🐱', 'Virtual Cat'], ['🎨', 'Paint'], ['🧩', 'Solitaire']]; icons.forEach(([ic, n], i) => root.append(h('div', { style: { position: 'absolute', left: 14 + Math.floor(i / 6) * 90 + 'px', top: 14 + (i % 6) * 84 + 'px', width: '76px', textAlign: 'center', color: '#fff', fontSize: '12px', cursor: 'pointer' }, ondblclick: () => open(n) }, h('div', { style: { fontSize: '34px' } }, ic), n))); root.append(h('div.k-row', { style: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '30px', background: '#c0c0c0', boxShadow: 'inset 0 1px #fff', padding: '0 4px', gap: '6px', color: '#000' } }, h('b', { style: { boxShadow: 'inset -1px -1px #000,inset 1px 1px #fff', padding: '2px 8px' } }, '⊞ Start'), h('span', { style: { flex: 1 } }), h('span', { style: { boxShadow: 'inset 1px 1px #808080', padding: '2px 8px' } }, '12:00 PM'))); open('Terminal'); };
  const open = (n) => { if (n === 'Terminal') { const out = h('div', { style: { padding: '6px', font: `12px ${MONO}` } }, 'Windows93-ish terminal. type help'); const inp = h('input', { style: { width: '95%', background: '#000', color: '#0f0', border: 0, font: `12px ${MONO}`, outline: 'none' }, onkeydown: (e) => { if (e.key !== 'Enter') return; const c = inp.value.trim(); out.append(h('div', {}, '> ' + c), h('div', {}, { help: 'commands: help, date, cowsay, beep, clear', date: new Date().toString(), beep: (blip(880, 0.2, 'square'), 'BEEP'), cowsay: ' ____\n< moo >\n ----\n  \\ ^__^\n    (oo)\\___' }[c] || (c === 'clear' ? (out.textContent = '', '') : 'bad command or file name'))); inp.value = ''; } }); root.append(win95('Terminal', [out, inp], { x: 260, y: 90, w: 480, hh: 280, dark: true })); setTimeout(() => inp.focus(), 50); } else root.append(win95(n, h('div', { style: { padding: '12px', fontSize: '13px' } }, n === 'Virtual Cat' ? '🐱 meow. (click me)' : `${n} — nothing important here.`), { x: 200 + Math.random() * 300, y: 60 + Math.random() * 200 })); };
  boot.addEventListener('click', desk); root.append(boot);
  window.__demoProof = async () => 'BIOS boot screen; click boots desktop';
};
V['retro-boot-desktop-museum'] = (root, T) => {
  theme(root, T, { bg: '#f5ecd9', fg: '#2a2a2a', ac: '#c98a1a', dark: false }); root.style.overflow = 'auto';
  const ITEMS = [['01', 'The Desktop', 'Windows 95'], ['02', 'Specifications', 'Pentium II'], ['03', 'Sound', 'SoundBlaster'], ['04', 'The Internet', '56k modem'], ['05', 'Screensavers', '3D Pipes']];
  const enter = () => { const d = h('div', { style: { position: 'fixed', inset: '38px 0 0 0', background: '#008080', zIndex: 20 } }); d.append(win95('Welcome', h('div', { style: { padding: '14px', fontSize: '13px', lineHeight: 1.6 } }, h('b', {}, 'Welcome to 1997-ish'), h('p', {}, 'Explore the desktop. Double-click icons. Close this window to exit the museum.'), btn('Exit museum', () => d.remove())), { x: 300, y: 120, w: 420, hh: 180 }), h('div.k-row', { style: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '30px', background: '#c0c0c0', padding: '0 4px' } }, h('b', { style: { boxShadow: 'inset -1px -1px #000,inset 1px 1px #fff', padding: '2px 8px' } }, '⊞ Start'))); ['💻 My Computer', '🌐 Netscape', '📝 Notepad', '🎵 Winamp'].forEach((t, i) => d.append(h('div', { style: { position: 'absolute', left: '16px', top: 16 + i * 80 + 'px', color: '#fff', textAlign: 'center', fontSize: '12px', width: '80px' } }, h('div', { style: { fontSize: '32px' } }, t.split(' ')[0]), t.split(' ').slice(1).join(' ')))); document.body.append(d); };
  root.append(h('div.k-row', { style: { height: '44px', padding: '0 60px', fontSize: '11px', letterSpacing: '.15em', borderBottom: '1px solid #e0d2b4' } }, h('b', {}, '◐ THE 1997 DESK · COMPUTER MUSEUM-ish'), h('span', { style: { flex: 1 } }), 'COLLECTION', 'ABOUT', 'VISIT', h('span', { style: { background: '#2a2a2a', color: '#fff', padding: '3px 10px', borderRadius: '99px' } }, 'EN')), h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 360px', gap: '60px', padding: '50px 120px 30px' } }, h('div', {}, h('div', { style: { fontSize: '11px', letterSpacing: '.3em', opacity: .6 } }, 'FIRST BOOT · 1997 · OPEN COLLECTION'), h('div', { style: { font: "700 96px/0.95 'Fraunces Variable'", margin: '16px 0' } }, 'Welcome', h('br'), 'to ', h('i', { style: { color: '#c98a1a', textDecoration: 'underline', textDecorationThickness: '3px' } }, '1997.')), h('p', { style: { maxWidth: '460px', lineHeight: 1.6 } }, 'A field guide to the golden age of home computing. Boot a legendary desktop, fiddle with its settings, and hear the dial-up sing.'), h('div.k-row', { style: { gap: '14px', marginTop: '20px' } }, h('button', { style: { background: '#c98a1a', color: '#fff', border: 0, padding: '12px 22px', fontWeight: 700, letterSpacing: '.1em' }, onclick: enter }, 'ENTER THE COLLECTION →'), h('button', { style: { background: 'none', border: '1px solid #2a2a2a', padding: '12px 22px' }, onclick: () => blip(1200, 1, 'square', 0.05) }, '▶ HEAR THE MODEM'))), h('div', { style: { background: '#fbf6ea', border: '1px solid #e0d2b4', padding: '18px', position: 'relative' } }, h('div', { style: { position: 'absolute', right: '10px', top: '-20px', font: "900 120px 'Fraunces Variable'", opacity: .06 } }, '97'), h('b', {}, 'Contents'), ...ITEMS.map(([n, t, sub]) => h('div.k-row', { style: { borderTop: '1px solid #eadfc6', padding: '10px 0', fontSize: '13px' } }, h('span', { style: { opacity: .5 } }, n), t, h('span', { style: { flex: 1 } }), h('span', { style: { opacity: .5, fontSize: '11px' } }, sub))))), h('div', { style: { margin: '0 120px', background: '#fff', border: '1px solid #e0d2b4', padding: '16px', display: 'grid', gap: '10px', fontSize: '13px' } }, h('b', {}, '🍪 Cookie & Privacy Settings'), h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' } }, h('div', { style: { background: '#f6f6f6', padding: '10px' } }, '☑ Essential cookies'), h('div', { style: { background: '#f6f6f6', padding: '10px' } }, '☐ Analytics')), h('div.k-row', { style: { justifyContent: 'flex-end' } }, h('button', { style: { background: '#0e7d6f', color: '#fff', border: 0, padding: '6px 14px' } }, 'Save'), btn('Accept all', () => {}))));
  window.__demoProof = async () => 'museum landing; ENTER opens Win95-style desktop';
};
V['winamp-skinned-player-chrome'] = (root, T) => {
  theme(root, T, { bg: '#3a6ea5', fg: '#fff', ac: '#0f0', dark: true });
  const TR = [['DJ Mike Llama - Llama Whippin\' Intro', 60, [0, 4, 7]], ['Chiptune Sunrise', 64, [0, 3, 7]], ['Modem Lullaby', 57, [0, 5, 9]], ['Floppy Disco', 62, [0, 4, 9]]]; let ti = 0, play = false, step = 0, vol = 0.6;
  const ac0 = () => audio(); let an = null; const bars = new Array(19).fill(0);
  setInterval(() => { if (!play) return; const [, r, ch] = TR[ti]; step++; blip(midi(r + ch[step % 3] + (step % 8 < 4 ? 12 : 0)), 0.15, 'square', 0.04 * vol); if (step % 2 === 0) drum(step % 4 ? 'hat' : 'kick'); bars.forEach((_, i) => (bars[i] = Math.random() * (1 - i / 30))); }, 130);
  const disp = h('div', { style: { background: '#000', color: '#0f0', font: `11px ${MONO}`, padding: '4px 6px', height: '40px', display: 'grid', gridTemplateColumns: '60px 1fr' } }); const viz = h('canvas', { width: 76, height: 16, style: { width: '76px', height: '16px' } });
  const tick = () => { disp.replaceChildren(h('div', { style: { font: `18px ${MONO}` } }, play ? `${String(Math.floor(step * 0.13 / 60)).padStart(2, '0')}:${String(Math.floor(step * 0.13) % 60).padStart(2, '0')}` : '00:00'), h('div', { style: { overflow: 'hidden', whiteSpace: 'nowrap' } }, `${ti + 1}. ${TR[ti][0]} (3:${20 + ti})  *** `, h('br'), '128 kbps 44 kHz stereo')); disp.firstChild.after(viz); const g = viz.getContext('2d'); g.fillStyle = '#000'; g.fillRect(0, 0, 76, 16); bars.forEach((b, i) => { g.fillStyle = b > 0.7 ? '#f33' : b > 0.4 ? '#ff3' : '#0f0'; g.fillRect(i * 4, 16 - b * 16, 3, b * 16); if (!play) bars[i] *= 0.9; }); requestAnimationFrame(tick); };
  const b95 = (l, f) => h('button', { style: { background: 'linear-gradient(#5a5a6a,#2a2a38)', color: '#ddd', border: '1px solid #111', fontSize: '10px', padding: '2px 6px' }, onclick: f }, l);
  const skin = (t, body, x, y, w) => { const el = h('div', { style: { position: 'absolute', left: x + 'px', top: y + 'px', width: w + 'px', background: 'linear-gradient(#3b3b52,#23232f)', border: '1px solid #000', padding: '0 3px 4px', boxShadow: '0 0 0 1px #5a5a7a inset' } }, h('div', { style: { font: `bold 9px ${MONO}`, color: '#ccc', textAlign: 'center', letterSpacing: '.2em', padding: '2px', background: 'repeating-linear-gradient(90deg,#8888aa 0 1px,transparent 1px 3px)', backgroundClip: 'content-box', cursor: 'move' } }, h('span', { style: { background: '#2a2a3a', padding: '0 6px' } }, t)), body); let ox, oy; drag(el.firstChild, { start: (e) => { ox = e.clientX - el.offsetLeft; oy = e.clientY - el.offsetTop; }, move: (e) => { el.style.left = e.clientX - ox + 'px'; el.style.top = e.clientY - oy + 'px'; } }); return el; };
  const main = skin('WINAMP-ish', h('div', { style: { display: 'grid', gap: '4px' } }, disp, h('input', { type: 'range', min: 0, max: 1, step: 0.01, value: vol, oninput: (e) => (vol = +e.target.value), style: { accentColor: '#0f0' } }), h('div.k-row', { style: { gap: '2px' } }, b95('⏮', () => { ti = (ti + 3) % 4; }), b95('▶', () => { audio(); play = true; }), b95('❚❚', () => (play = false)), b95('■', () => { play = false; step = 0; }), b95('⏭', () => { ti = (ti + 1) % 4; }), b95('⏏', () => toast('Open file (demo)')))), 360, 220, 275);
  const eq = skin('WINAMP EQUALIZER', h('div.k-row', { style: { height: '70px', gap: '5px', justifyContent: 'center', background: '#111', padding: '4px' } }, ...Array.from({ length: 11 }, (_, i) => h('input', { type: 'range', min: -12, max: 12, value: Math.round(Math.sin(i) * 6), orient: 'vertical', style: { writingMode: 'vertical-lr', direction: 'rtl', height: '60px', width: '12px', accentColor: i ? '#ff3' : '#0f0' } }))), 360, 330, 275);
  const pl = skin('WINAMP PLAYLIST', h('div', { style: { background: '#000', font: `11px ${MONO}`, minHeight: '120px', padding: '4px' } }, ...TR.map((t, i) => h('div', { style: { color: i === ti ? '#fff' : '#0f0', background: i === ti ? '#0000c6' : '', cursor: 'pointer' }, ondblclick: () => { ti = i; audio(); play = true; } }, `${i + 1}. ${t[0]}`))), 360, 440, 275);
  const vis = skin('MILKDROP-ish', (() => { const c = h('canvas', { width: 380, height: 230, style: { display: 'block', background: '#000' } }); let t = 0; const lp = () => { t += 0.03; const g = c.getContext('2d'); g.fillStyle = '#0003'; g.fillRect(0, 0, 380, 230); g.strokeStyle = `hsl(${t * 40} 90% 60%)`; g.lineWidth = 2; g.beginPath(); for (let x = 0; x < 380; x++) { const v = play ? bars[x % 19] : 0.1; x ? g.lineTo(x, 115 + Math.sin(x / 20 + t * 3) * 60 * v) : g.moveTo(0, 115); } g.stroke(); requestAnimationFrame(lp); }; lp(); return c; })(), 640, 220, 390);
  root.append(...[['🗂', 'My Files'], ['🌐', 'Internet'], ['🎵', 'Winamp'], ['🗑', 'Recycle Bin'], ['📄', 'llama.mp3'], ['💿', 'Skins']].map(([ic, n], i) => h('div', { style: { position: 'absolute', left: 16 + i * 84 + 'px', top: '14px', width: '72px', textAlign: 'center', fontSize: '11px' } }, h('div', { style: { fontSize: '30px' } }, ic), n)), main, eq, pl, vis);
  tick();
  window.__demoProof = async () => { play = true; step = 40; bars.forEach((_, i) => (bars[i] = Math.random())); await sleep(300); play = false; return 'Winamp chrome: transport, EQ, playlist, visualizer'; };
};
V['retro-media-player-chrome'] = (root, T) => {
  theme(root, T, { bg: '#f6cfd0', fg: '#222', ac: '#222', dark: false }); root.style.fontFamily = 'Chicago,Charcoal,Geneva,sans-serif';
  const CH = [['Poolside FM', 60, [0, 4, 7, 11]], ['Tokyo Disco', 62, [0, 3, 7, 10]], ['Hangover Club', 57, [0, 5, 9, 12]]]; let ci = 0, play = false, step = 0;
  setInterval(() => { if (!play) return; step++; const [, r, ch] = CH[ci]; if (step % 2 === 0) blip(midi(r + ch[(step / 2) % 4 | 0]), 0.35, 'triangle', 0.05); if (step % 4 === 0) drum('kick'); if (step % 4 === 2) drum('hat'); }, 140);
  const macWin = (t, body, x, y, w) => { const el = h('div', { style: { position: 'absolute', left: x + 'px', top: y + 'px', width: w + 'px', background: '#fff', border: '2px solid #222', boxShadow: '3px 3px 0 #222', zIndex: 5 } }, h('div.k-row', { style: { borderBottom: '2px solid #222', padding: '2px 6px', background: 'repeating-linear-gradient(#222 0 1px,#fff 1px 3px)', cursor: 'move' } }, h('span', { style: { background: '#fff', border: '1px solid #222', width: '12px', height: '12px', cursor: 'pointer' }, onclick: () => el.remove() }), h('span', { style: { flex: 1, textAlign: 'center' } }, h('span', { style: { background: '#fff', padding: '0 8px', fontSize: '12px', fontWeight: 700 } }, t))), body); let ox, oy; drag(el.firstChild, { start: (e) => { ox = e.clientX - el.offsetLeft; oy = e.clientY - el.offsetTop; }, move: (e) => { el.style.left = e.clientX - ox + 'px'; el.style.top = e.clientY - oy + 'px'; } }); root.append(el); return el; };
  const openPlayer = () => { const title = h('b'); const upd = () => (title.textContent = '♪ ' + CH[ci][0]); upd(); macWin('Poolsuite-ish.FM', h('div', { style: { padding: '12px', display: 'grid', gap: '10px', fontSize: '12px' } }, h('div', { style: { height: '120px', background: 'linear-gradient(#ffb3c1,#ffd8a8)', border: '1px solid #222', display: 'grid', placeItems: 'center', fontSize: '40px' } }, '🌴'), title, h('div.k-row', {}, btn('⏮', () => { ci = (ci + 2) % 3; upd(); }), btn(play ? '❚❚' : '▶', (e) => { audio(); play = !play; e.target.textContent = play ? '❚❚' : '▶'; }), btn('⏭', () => { ci = (ci + 1) % 3; upd(); })), select(CH.map((c) => c[0]), CH[0][0], (v) => { ci = CH.findIndex((c) => c[0] === v); upd(); })), 480, 160, 300); };
  const DOCK = [['🎵', 'Player', openPlayer], ['📼', 'Channels', openPlayer], ['📓', 'Notes', () => macWin('Notes', h('div', { style: { padding: '10px', fontSize: '12px' } }, 'Summer 1987. Sunscreen. Synths.'), 300, 200, 240)], ['🖼', 'Gallery', () => {}], ['📅', 'Events', () => {}], ['🛍', 'Shop', () => {}], ['🎮', 'Games', () => {}], ['⚙', 'Settings', () => {}], ['💌', 'Contact', () => {}]];
  root.append(h('div.k-row', { style: { position: 'absolute', left: 0, right: 0, top: 0, height: '24px', background: '#fff', borderBottom: '2px solid #222', padding: '0 10px', fontSize: '12px', gap: '16px', fontWeight: 700 } }, '🍑', 'File', 'Edit', 'View', 'Special', h('span', { style: { flex: 1 } }), h('span', { style: { background: '#222', color: '#fff', padding: '0 6px' } }, 'TUNE IN · FREE'), '☀ 27°'), h('div.k-row', { style: { position: 'absolute', bottom: '14px', left: '50%', transform: 'translateX(-50%)', background: '#fff', border: '2px solid #222', boxShadow: '3px 3px 0 #222', padding: '6px', gap: '4px' } }, ...DOCK.map(([ic, n, f]) => h('div', { style: { width: '54px', textAlign: 'center', fontSize: '10px', cursor: 'pointer', padding: '4px 0', border: '1px solid transparent' }, onclick: f }, h('div', { style: { fontSize: '24px' } }, ic), n))));
  window.__demoProof = async () => 'pink desktop with dock (click Player to open)';
};
export function mount(root, variant, opts, T) { (V[variant] || V['parody-desktop-os-sandbox'])(root, T); }
