import { h, s, drag, localPos, clamp, copy, toast, sleep, rng, pick, noise2, fitCanvas } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle } from '../kit.js';
import { glCanvas } from './sim.js';
const V = {};
const dl = (cv, n) => { const a = h('a', { download: n, href: cv.toDataURL() }); a.click(); };
V['tinkersynth-slopes-synth-desk'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#6c4cf5', dark: false });
  const P = { lines: 60, amp: 40, freq: 0.012, seed: 3, peaks: 0.6, perspective: 0.4, split: false };
  const cv = h('canvas', { width: 520, height: 640, style: { width: '400px', height: '492px', background: '#000' } });
  const draw = () => { const g = cv.getContext('2d'); g.fillStyle = '#000'; g.fillRect(0, 0, 520, 640); g.strokeStyle = '#fff'; g.lineWidth = 1.4; for (let i = 0; i < P.lines; i++) { const y0 = 80 + (i / P.lines) * 500; g.beginPath(); let first = true; for (let x = 40; x <= 480; x += 3) { const cx = Math.abs(x - 260) / 220; const env = Math.pow(1 - cx, 2) * P.peaks * 2; const n = noise2(x * P.freq + P.seed * 10, i * 0.25 + P.seed) ; const y = y0 - Math.max(0, n) * P.amp * env * (1 + i * P.perspective / P.lines); if (first) { g.moveTo(x, y); first = false; } else g.lineTo(x, y); } g.save(); g.fillStyle = '#000'; g.lineTo(480, 640); g.lineTo(40, 640); g.closePath(); g.fill(); g.restore(); g.beginPath(); first = true; for (let x = 40; x <= 480; x += 3) { const cx = Math.abs(x - 260) / 220; const env = Math.pow(1 - cx, 2) * P.peaks * 2; const n = noise2(x * P.freq + P.seed * 10, i * 0.25 + P.seed); const y = y0 - Math.max(0, n) * P.amp * env * (1 + i * P.perspective / P.lines); if (first) { g.moveTo(x, y); first = false; } else g.lineTo(x, y); } g.stroke(); } };
  const knob = (lab, k, mn, mx) => { const el = h('div', { style: { width: '54px', height: '54px', borderRadius: '50%', background: 'conic-gradient(#f0f 0 ' + ((P[k] - mn) / (mx - mn)) * 100 + '%,#333 0)', border: '4px solid #111', cursor: 'ns-resize' } }); let y0, v0; drag(el, { start: (e) => { y0 = e.clientY; v0 = P[k]; }, move: (e) => { P[k] = clamp(v0 + ((y0 - e.clientY) / 150) * (mx - mn), mn, mx); el.style.background = 'conic-gradient(#f0f 0 ' + ((P[k] - mn) / (mx - mn)) * 100 + '%,#333 0)'; draw(); } }); return h('div', { style: { display: 'grid', justifyItems: 'center', gap: '4px', fontSize: '10px', color: '#ccc' } }, el, lab); };
  const mod = (t, ...k) => h('div', { style: { background: '#1b1b1f', border: '2px solid #333', borderRadius: '6px', padding: '10px', display: 'grid', gap: '8px', color: '#ddd', fontSize: '11px' } }, h('b', { style: { color: '#f0f', letterSpacing: '.1em' } }, t), ...k);
  root.append(h('div.k-row', { style: { height: '56px', padding: '0 30px' } }, h('b', { style: { color: '#6c4cf5' } }, '▼ Tinkersynth-ish'), h('span', { style: { flex: 1 } }), 'Gallery', 'Shop', 'Help'), h('div', { style: { display: 'flex', gap: '30px', padding: '10px 60px' } }, h('div', { style: { background: '#fff', padding: '20px', boxShadow: '0 10px 40px #0002', display: 'grid', gap: '14px' } }, cv, h('div.k-row', {}, h('span', { style: { background: '#222', color: '#fff', borderRadius: '50%', width: '34px', height: '34px', display: 'grid', placeItems: 'center' } }, '⟳'), h('span', { style: { flex: 1 } }), h('button', { style: { background: '#6c4cf5', color: '#fff', border: 0, padding: '10px 24px', borderRadius: '6px' }, onclick: () => dl(cv, 'slopes.png') }, 'Download'))), h('div', { style: { flex: 1, background: '#f3efe6', borderRadius: '10px', padding: '18px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', alignContent: 'start' } }, h('div', { style: { gridColumn: '1/-1', font: '900 34px Georgia', color: '#1b1b1f' } }, 'Slopes'), mod('LINES', slider('Count', 10, 120, P.lines, 1, (v) => { P.lines = v; draw(); })), mod('PEAKS', h('div.k-row', {}, knob('Amp', 'amp', 0, 120), knob('Peaks', 'peaks', 0, 1.5))), mod('NOISE', slider('Frequency', 0.002, 0.04, P.freq, 0.001, (v) => { P.freq = v; draw(); }), btn('Randomize seed', () => { P.seed = Math.random() * 100; draw(); })), mod('PERSPECTIVE', slider('Depth', 0, 2, P.perspective, 0.05, (v) => { P.perspective = v; draw(); })), mod('PRINT', h('div', {}, '18×24" archival giclée'), h('div', { style: { color: '#f0f' } }, '$60')))));
  draw();
  window.__demoProof = async () => { P.amp = 70; P.peaks = 0.9; draw(); return 'slopes regenerated with higher peaks'; };
};
V['ritmo-simplex-wave-studio'] = (root, T) => {
  theme(root, T, { bg: '#ececec', fg: '#222', panel: '#fff', ac: '#1e90ff', dark: false });
  const P = { freq: 1.6, amp: 0.35, stripes: 12, angle: 35, t: 0, anim: true, cols: ['#2b1d3a', '#fff', '#8e5cc4', '#f4a340'] };
  const cv = h('canvas', { width: 560, height: 560, style: { boxShadow: '0 8px 30px #0002' } });
  const draw = () => { const g = cv.getContext('2d'); const img = g.createImageData(560, 560); const a = (P.angle * Math.PI) / 180, ca = Math.cos(a), sa = Math.sin(a); const cc = P.cols.map((c) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16))); for (let y = 0; y < 560; y += 2) for (let x = 0; x < 560; x += 2) { const u = (x * ca + y * sa) / 560, v = (-x * sa + y * ca) / 560; const w = u + noise2(v * P.freq * 3 + P.t, P.t * 0.3) * P.amp; const k = ((Math.floor(w * P.stripes) % 4) + 4) % 4; const c = cc[k]; for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [1, 1]]) { const i = ((y + dy) * 560 + x + dx) * 4; img.data[i] = c[0]; img.data[i + 1] = c[1]; img.data[i + 2] = c[2]; img.data[i + 3] = 255; } } g.putImageData(img, 0, 0); };
  const loop = () => { if (P.anim) { P.t += 0.01; draw(); } requestAnimationFrame(loop); };
  const sect = (t, ...k) => h('div', { style: { borderTop: '1px solid #eee', padding: '8px 0', display: 'grid', gap: '6px' } }, h('div', { style: { fontSize: '11px', fontWeight: 700 } }, '▾ ' + t), ...k);
  root.append(h('div.k-row', { style: { position: 'absolute', top: '10px', left: '50%', transform: 'translateX(-50%)', background: '#fff', borderRadius: '8px', padding: '4px', boxShadow: '0 1px 4px #0001' } }, seg(['Simplex', 'Waves', 'Grid', 'Truchet'], 'Simplex', () => {}), h('button', { style: { background: '#1e90ff', color: '#fff', border: 0, padding: '6px 14px', borderRadius: '6px' }, onclick: () => dl(cv, 'ritmo.png') }, 'Export')), h('div', { style: { position: 'absolute', left: 0, right: '300px', top: '60px', bottom: '60px', display: 'grid', placeItems: 'center' } }, cv), h('div', { style: { position: 'absolute', right: '20px', top: '20px', width: '260px', bottom: '20px', background: '#fff', borderRadius: '8px', padding: '12px', fontSize: '12px', overflow: 'auto' } }, sect('Canvas', select(['1:1 · 2400px', '4:5', '16:9'], '1:1 · 2400px', () => {})), sect('Noise', slider('Frequency', 0.2, 4, P.freq, 0.05, (v) => (P.freq = v)), slider('Amplitude', 0, 1, P.amp, 0.01, (v) => (P.amp = v))), sect('Stripes', slider('Count', 4, 40, P.stripes, 1, (v) => (P.stripes = v)), slider('Angle', 0, 180, P.angle, 1, (v) => (P.angle = v))), sect('Colors', h('div.k-row', {}, P.cols.map((c, i) => h('input', { type: 'color', value: c, oninput: (e) => (P.cols[i] = e.target.value), style: { width: '40px', height: '26px', border: 0 } })))), sect('Animation', toggle('Animate', true, (v) => (P.anim = v))), h('button', { style: { width: '100%', background: '#1e90ff', color: '#fff', border: 0, padding: '8px', borderRadius: '6px', marginTop: '8px' }, onclick: () => dl(cv, 'ritmo.png') }, 'Download PNG')), h('div.k-row', { style: { position: 'absolute', bottom: '16px', left: 'calc(50% - 150px)', transform: 'translateX(-50%)', fontSize: '11px' } }, '◀', '❚❚', '▶', 'loop 4s'));
  draw(); loop();
  window.__demoProof = async () => 'simplex-warped stripes animating';
};
V['threelab-generative-pattern-deck'] = (root, T) => {
  theme(root, T, { bg: '#2a1d2c', fg: '#eee', ac: '#3cf', dark: true });
  const U = { waves: 9, petals: 7, twist: 0.6, speed: 0.3, c1: [0.95, 0.8, 0.85], c2: [0.3, 0.2, 0.15], c3: [0.8, 0.65, 0.3] };
  const G = glCanvas(`void main(){vec2 p=(gl_FragCoord.xy-R*.5)/R.y;float r=length(p),a=atan(p.y,p.x);float T=t*speed;float w=sin(r*waves*6.283-T*3.+sin(a*petals+T)*twist*3.);float band=smoothstep(-.2,.2,w);float band2=smoothstep(.6,.9,sin(r*waves*12.566+sin(a*petals)*twist*4.-T*2.));vec3 c=mix(c2,c1,band);c=mix(c,c3,band2*.8);c*=1.-smoothstep(.7,1.2,r)*.3;gl_FragColor=vec4(c,1);}`, U);
  G.cv.style.position = 'absolute'; G.cv.style.inset = '0';
  root.append(G.cv, h('div.k-row', { style: { position: 'absolute', left: '12px', top: '10px', gap: '6px' } }, h('span', { style: { background: '#3cf', color: '#000', padding: '4px 12px', borderRadius: '4px', fontSize: '12px' } }, 'Randomize'), h('span', { style: { background: '#000a', padding: '4px 10px', borderRadius: '4px', fontSize: '12px' } }, 'threelab-ish · Pattern 12')), h('div', { style: { position: 'absolute', right: '12px', top: '10px', width: '210px', background: '#000a', borderRadius: '6px', padding: '10px', display: 'grid', gap: '8px', fontSize: '11px' } }, slider('Waves', 1, 20, U.waves, 0.1, (v) => (U.waves = v)), slider('Petals', 1, 16, U.petals, 1, (v) => (U.petals = v)), slider('Twist', 0, 2, U.twist, 0.01, (v) => (U.twist = v)), slider('Speed', 0, 2, U.speed, 0.01, (v) => (U.speed = v)), btn('Randomize', () => { U.waves = 3 + Math.random() * 12; U.petals = 2 + Math.round(Math.random() * 10); U.twist = Math.random() * 1.5; }, 'pri'), btn('Save PNG', () => dl(G.cv, 'pattern.png'))), h('div.k-row', { style: { position: 'absolute', bottom: '14px', left: '50%', transform: 'translateX(-50%)', background: '#000a', padding: '6px 10px', borderRadius: '6px', fontSize: '12px', gap: '14px' } }, '◀ prev', '● 12 / 40', 'next ▶'));
  const t0 = performance.now(); const loop = () => { G.draw((performance.now() - t0) / 1000); requestAnimationFrame(loop); }; loop();
  window.__demoProof = async () => 'radial wave pattern shader live';
};
V['city-roads-lineart-explorer'] = (root, T) => {
  theme(root, T, { bg: '#f7f2e8', fg: '#222', ac: '#222', dark: false });
  const cv = h('canvas', { style: { position: 'absolute', inset: 0, opacity: 0, transition: 'opacity .6s' } }); root.append(cv);
  const roads = (seed) => { fitCanvas(cv, root); const g = cv.g, W = cv.W, H = cv.H; const R = rng(seed); g.fillStyle = '#f7f2e8'; g.fillRect(0, 0, W, H); g.strokeStyle = '#222'; const segs = []; const grow = (x, y, a, d, w) => { if (d > 7 || x < 0 || y < 0 || x > W || y > H) return; const L = 40 + R() * 120; for (let k = 0; k < 3; k++) { const nx = x + Math.cos(a) * L, ny = y + Math.sin(a) * L; g.lineWidth = w; g.beginPath(); g.moveTo(x, y); g.quadraticCurveTo(x + Math.cos(a + 0.2) * L / 2, y + Math.sin(a + 0.2) * L / 2, nx, ny); g.stroke(); segs.push(1); x = nx; y = ny; a += (R() - 0.5) * 0.5; if (R() < 0.6) grow(x, y, a + Math.PI / 2 + (R() - 0.5) * 0.4, d + 1, Math.max(0.4, w * 0.6)); if (R() < 0.6) grow(x, y, a - Math.PI / 2 + (R() - 0.5) * 0.4, d + 1, Math.max(0.4, w * 0.6)); } }; for (let i = 0; i < 6; i++) grow(W / 2, H / 2, (i / 6) * 6.283, 0, 3); for (let i = 0; i < 1400; i++) { const x = R() * W, y = R() * H; const a = R() < 0.5 ? 0 : Math.PI / 2; g.lineWidth = 0.4; g.beginPath(); g.moveTo(x, y); g.lineTo(x + Math.cos(a) * 30, y + Math.sin(a) * 30); g.stroke(); } cv.style.opacity = 1; card.style.top = '20px'; info.textContent = `${segs.length + 1400} roads · ${inp.value}`; };
  const inp = h('input', { placeholder: 'Enter a city name to start', style: { width: '320px', padding: '10px 12px', border: '1px solid #ccc', background: '#fff', fontSize: '14px' }, onkeydown: (e) => e.key === 'Enter' && roads(inp.value.length * 7 + 3) });
  const sug = h('div', { style: { background: '#fff', border: '1px solid #ddd', borderTop: 0, width: '344px', textAlign: 'left', fontSize: '13px', display: 'none' } });
  inp.addEventListener('input', () => { const v = inp.value.trim(); sug.style.display = v ? 'block' : 'none'; sug.replaceChildren(...['', ', South Korea', ', Metropolitan City'].map((sfx) => h('div', { style: { padding: '8px 12px', borderTop: '1px solid #eee', cursor: 'pointer' }, onclick: () => { inp.value = v + sfx; sug.style.display = 'none'; roads(v.length * 7 + 3); } }, v + sfx))); });
  const info = h('div', { style: { fontSize: '12px', opacity: .6, marginTop: '6px' } }, 'This website renders every single road within a city');
  const card = h('div', { style: { position: 'absolute', left: '50%', top: '40%', transform: 'translateX(-50%)', textAlign: 'center', transition: 'top .6s' } }, h('div', { style: { fontSize: '26px' } }, 'city roads-ish'), info, h('div', { style: { marginTop: '12px' } }, inp), sug, h('div.k-row', { style: { justifyContent: 'center', marginTop: '10px', fontSize: '12px', gap: '12px', opacity: .7 } }, 'Customize', '·', 'Export PNG', '·', 'About'));
  root.append(card);
  window.__demoProof = async () => { inp.value = 'Seoul'; inp.dispatchEvent(new Event('input')); return 'typed city → suggestions (landing state)'; };
};
V['pattern-symmetry-playground'] = (root, T) => {
  theme(root, T, { bg: '#111', fg: '#ddd', panel: '#1b1b1b', ac: '#fff', acfg: '#000', dark: true });
  const P = { count: 36, curve: 2.2, width: 3, sym: 'none', invert: false };
  const svg = s('svg', { viewBox: '0 0 700 400', width: 700, height: 400, style: 'background:#000' });
  const draw = () => { const els = [s('rect', { width: 700, height: 400, fill: P.invert ? '#fff' : '#000' })]; for (let i = 0; i < P.count; i++) { let t = i / P.count; t = Math.pow(t, 1 / P.curve); let x = t * 520; const add = (x) => els.push(s('rect', { x, y: 0, width: P.width, height: 400, fill: P.invert ? '#000' : '#fff' })); add(x); if (P.sym === 'mirror') add(700 - x - P.width); if (P.sym === 'radial') add(350 + (x - 260) * -1); } svg.replaceChildren(...els); };
  const row = (l, c) => h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 110px', alignItems: 'center', fontSize: '12px', padding: '4px 0' } }, l, c);
  root.style.display = 'grid'; root.style.gridTemplateColumns = '1fr 300px';
  root.append(h('div', { style: { display: 'grid', placeItems: 'center', position: 'relative' } }, h('div.k-row', { style: { position: 'absolute', top: '12px', left: '14px', fontSize: '12px' } }, h('b', {}, '◎ RHYTHM-ish'), h('span', { style: { background: '#2c2', color: '#000', padding: '1px 5px', borderRadius: '3px', fontSize: '10px' } }, 'BETA')), h('span', { style: { position: 'absolute', right: '14px', top: '12px', background: '#fff', color: '#000', padding: '4px 12px', borderRadius: '99px', fontSize: '12px' } }, 'Export'), svg), h('div', { style: { background: '#1b1b1b', padding: '14px', display: 'grid', gap: '4px', alignContent: 'start', borderLeft: '1px solid #2a2a2a' } }, h('div.k-h', {}, 'Artboard'), row('Size', select(['700 × 400', '1080 × 1080'], '700 × 400', () => {})), h('div.k-h', {}, 'Elements'), row('Count', slider('', 2, 120, P.count, 1, (v) => { P.count = v; draw(); })), row('Width', slider('', 1, 20, P.width, 0.5, (v) => { P.width = v; draw(); })), h('div.k-h', {}, 'Distribution'), row('Curve', slider('', 0.2, 5, P.curve, 0.05, (v) => { P.curve = v; draw(); })), row('Symmetry', select(['none', 'mirror', 'radial'], 'none', (v) => { P.sym = v; draw(); })), row('Invert', toggle('', false, (v) => { P.invert = v; draw(); })), h('div.k-h', {}, 'Export'), btn('SVG', () => copy(svg.outerHTML)), btn('Copy code', () => copy(svg.outerHTML))));
  draw();
  window.__demoProof = async () => { P.curve = 2.6; draw(); return 'rhythmic line distribution curve 2.6'; };
};
V['canvas-fx-param-export'] = (root, T) => {
  theme(root, T, { bg: '#f7f7f7', fg: '#1f2d1f', panel: '#fff', ac: '#3e7d3e', dark: false });
  const P = { fx: 'grain', amt: 0.5, size: 2, hue: 140, glow: 0.3 };
  const cv = h('canvas', { width: 640, height: 400, style: { borderRadius: '10px', boxShadow: '0 6px 24px #0002' } });
  const draw = () => { const g = cv.getContext('2d'); const gr = g.createLinearGradient(0, 0, 640, 400); gr.addColorStop(0, `hsl(${P.hue} 50% 30%)`); gr.addColorStop(1, `hsl(${P.hue + 60} 60% 70%)`); g.fillStyle = gr; g.fillRect(0, 0, 640, 400); g.fillStyle = '#fff'; g.font = '900 72px Inter Variable'; g.textAlign = 'center'; g.fillText('canvas fx', 320, 220); const img = g.getImageData(0, 0, 640, 400); const R = rng(4); for (let i = 0; i < img.data.length; i += 4) { if (P.fx === 'grain') { const n = (R() - 0.5) * 255 * P.amt; img.data[i] += n; img.data[i + 1] += n; img.data[i + 2] += n; } else if (P.fx === 'scanlines' && ((i / 4 / 640) | 0) % (P.size * 2) < P.size) { img.data[i] *= 1 - P.amt; img.data[i + 1] *= 1 - P.amt; img.data[i + 2] *= 1 - P.amt; } else if (P.fx === 'posterize') { const lv = 2 + Math.round((1 - P.amt) * 8); for (let k = 0; k < 3; k++) img.data[i + k] = Math.round((img.data[i + k] / 255) * lv) * (255 / lv); } } g.putImageData(img, 0, 0); if (P.fx === 'pixelate') { const sz = 2 + Math.round(P.amt * 20); const t = document.createElement('canvas'); t.width = 640 / sz; t.height = 400 / sz; t.getContext('2d').drawImage(cv, 0, 0, t.width, t.height); g.imageSmoothingEnabled = false; g.drawImage(t, 0, 0, 640, 400); } code.textContent = `canvasFx(ctx, { effect: '${P.fx}', amount: ${P.amt}, size: ${P.size} })`; };
  const code = h('pre.k-code', { style: { width: '640px' } });
  root.append(h('div.k-row', { style: { height: '56px', padding: '0 30px', borderBottom: '1px solid #e5e5e5', background: '#fff' } }, h('b', { style: { color: '#3e7d3e' } }, '✺ canvas-fx-ish'), h('span', { style: { flex: 1 } }), 'Effects', 'Docs', 'GitHub'), h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 300px', gap: '20px', padding: '30px' } }, h('div', { style: { display: 'grid', justifyItems: 'center', gap: '14px' } }, cv, code), panel('Effect', seg(['grain', 'scanlines', 'posterize', 'pixelate'], P.fx, (v) => { P.fx = v; draw(); }), slider('Amount', 0, 1, P.amt, 0.01, (v) => { P.amt = v; draw(); }), slider('Size', 1, 8, P.size, 1, (v) => { P.size = v; draw(); }), slider('Hue', 0, 360, P.hue, 1, (v) => { P.hue = v; draw(); }), btn('Export PNG', () => dl(cv, 'fx.png'), 'pri'), btn('Copy params', () => copy(code.textContent)))));
  draw();
  window.__demoProof = async () => { P.fx = 'scanlines'; P.amt = 0.4; draw(); return 'scanlines fx applied, params code updated'; };
};
V['procedural-dungeon-theme-stage'] = (root, T) => {
  theme(root, T, { bg: '#000', fg: '#cfd8ff', panel: '#0c0f1a', ac: '#4f7cff', dark: true });
  const P = { seed: 7, rooms: 14, theme: 'blueprint' }; const TH = { blueprint: ['#000', '#5d8bff'], parchment: ['#e9dcbc', '#5a3d1e'], neon: ['#0a0014', '#ff3df2'] };
  const svg = s('svg', { viewBox: '-450 -80 900 520', style: 'width:100%;height:100%' }); const title = h('div', { style: { font: '700 14px Georgia', margin: '6px 0' } });
  const gen = () => { const R = rng(P.seed); const rooms = []; for (let i = 0; i < P.rooms; i++) { const w = 2 + Math.floor(R() * 4), d = 2 + Math.floor(R() * 4); rooms.push({ x: Math.floor(R() * 16), y: Math.floor(R() * 16), w, d, r: R() < 0.15 }); } const [bg, fg] = TH[P.theme]; root.style.background = bg; const iso = (x, y) => [(x - y) * 22, (x + y) * 11]; const els = []; rooms.sort((a, b) => a.x + a.y - b.x - b.y).forEach((r, i) => { const pts = [[r.x, r.y], [r.x + r.w, r.y], [r.x + r.w, r.y + r.d], [r.x, r.y + r.d]].map(([x, y]) => iso(x, y)); if (r.r) { const [cx, cy] = iso(r.x + r.w / 2, r.y + r.d / 2); els.push(s('ellipse', { cx, cy, rx: r.w * 18, ry: r.w * 9, fill: 'none', stroke: fg, 'stroke-width': 1.5 }), s('ellipse', { cx, cy: cy - 14, rx: r.w * 18, ry: r.w * 9, fill: 'none', stroke: fg, 'stroke-width': 1, opacity: .5 })); } else { els.push(s('polygon', { points: pts.map((p) => p.join(',')).join(' '), fill: fg + '14', stroke: fg, 'stroke-width': 1.5 })); els.push(s('polygon', { points: pts.map(([x, y]) => `${x},${y - 14}`).join(' '), fill: 'none', stroke: fg, 'stroke-width': 1, opacity: .45 })); for (let gx = 1; gx < r.w; gx++) { const [a, b] = [iso(r.x + gx, r.y), iso(r.x + gx, r.y + r.d)]; els.push(s('line', { x1: a[0], y1: a[1], x2: b[0], y2: b[1], stroke: fg, 'stroke-width': 0.4, opacity: .5 })); } } if (i) { const p = rooms[i - 1]; const [a, b] = [iso(p.x + p.w / 2, p.y + p.d / 2), iso(r.x + r.w / 2, p.y + p.d / 2)]; const c = iso(r.x + r.w / 2, r.y + r.d / 2); els.push(s('polyline', { points: `${a} ${b} ${c}`, fill: 'none', stroke: fg, 'stroke-width': 5, opacity: .25 })); } }); svg.replaceChildren(...els); const N1 = ['The Lost', 'The Drowned', 'The Hollow', 'The Ashen']; const N2 = ['Vaults of the Idle', 'Halls of Nuun', 'Crypt of Mirrors', 'Warrens of Salt']; title.replaceChildren(h('div', { style: { opacity: .6, fontSize: '11px' } }, 'Dungeon #' + P.seed), N1[P.seed % 4], h('br'), N2[(P.seed >> 1) % 4]); };
  root.style.display = 'grid'; root.style.gridTemplateColumns = '230px 1fr';
  root.append(h('div', { style: { background: '#0c0f1add', padding: '14px', display: 'grid', gap: '10px', alignContent: 'start', fontSize: '12px', borderRight: '1px solid #1c2340' } }, h('b', { style: { font: '700 20px Georgia', letterSpacing: '.08em' } }, 'DUNGEONEER-ish'), title, seg(['blueprint', 'parchment', 'neon'], P.theme, (v) => { P.theme = v; gen(); }), h('button', { style: { background: '#4f7cff', color: '#fff', border: 0, padding: '10px', borderRadius: '4px', fontWeight: 700 }, onclick: () => { P.seed++; gen(); } }, 'NEW DUNGEON ⟳'), slider('Rooms', 4, 30, P.rooms, 1, (v) => { P.rooms = v; gen(); }), h('div.k-row', {}, btn('Export SVG', () => copy(svg.outerHTML)), btn('PNG', () => toast('dungeon.png'))), h('div', { style: { opacity: .5, fontSize: '11px', lineHeight: 1.5 } }, 'Seeds are shareable. Press Space for a new dungeon.')), h('div', { style: { position: 'relative' } }, svg));
  window.addEventListener('keydown', (e) => e.code === 'Space' && (e.preventDefault(), P.seed++, gen()));
  gen();
  window.__demoProof = async () => { P.seed = 11; gen(); return 'generated blueprint dungeon #11'; };
};
V['fantasy-map-generator-workspace'] = (root, T) => {
  theme(root, T, { bg: '#6b8fc2', fg: '#222', panel: '#f5efe0', ac: '#7a4a1e', dark: false });
  const W = 360, H = 225; const cv = h('canvas', { width: W * 4, height: H * 4, style: { position: 'absolute', inset: 0, width: '100%', height: '100%' } }); let seed = 5, nStates = 9, showLabels = true;
  const gen = () => { const R = rng(seed); const hgt = new Float32Array(W * H); for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) { const dx = (x / W - 0.5) * 2, dy = (y / H - 0.5) * 2; const n = noise2(x * 0.015 + seed, y * 0.015) * 0.6 + noise2(x * 0.05 + seed, y * 0.05) * 0.25 + noise2(x * 0.12, y * 0.12 + seed) * 0.1; hgt[y * W + x] = n + 0.45 - Math.hypot(dx * 0.9, dy) * 0.55; } const seeds = []; for (let tries = 0; seeds.length < nStates && tries < 5000; tries++) { const x = (R() * W) | 0, y = (R() * H) | 0; if (hgt[y * W + x] > 0.1) seeds.push({ x, y }); } const PAL = ['#f5e4a6', '#cfe3b2', '#e8c1d6', '#c7d3ef', '#f3c7a1', '#d6e8c9', '#e3d0f2', '#f7d6c1', '#c9e7e3', '#efe2b8', '#d8c9e8', '#f2b8b8']; const g = cv.getContext('2d'); const img = g.createImageData(W, H); const st = new Int8Array(W * H).fill(-1); for (let i = 0; i < W * H; i++) { const x = i % W, y = (i / W) | 0; const hh = hgt[i]; let c; if (hh <= 0) { const d = clamp(-hh * 6, 0, 1); c = [120 - d * 30, 160 - d * 40, 210 - d * 20]; if (hh > -0.04) c = [190, 215, 235]; } else { let bi = 0, bd = 1e9; seeds.forEach((sd, k) => { const d = (sd.x - x) ** 2 + (sd.y - y) ** 2; if (d < bd) { bd = d; bi = k; } }); st[i] = bi; const p = PAL[bi % PAL.length]; c = [1, 3, 5].map((k) => parseInt(p.slice(k, k + 2), 16) - hh * 40); } img.data[i * 4] = c[0]; img.data[i * 4 + 1] = c[1]; img.data[i * 4 + 2] = c[2]; img.data[i * 4 + 3] = 255; } for (let i = W; i < W * H - W; i++) if (st[i] >= 0 && (st[i] !== st[i + 1] || st[i] !== st[i + W]) && st[i + 1] >= 0 && st[i + W] >= 0) { img.data[i * 4] -= 60; img.data[i * 4 + 1] -= 60; img.data[i * 4 + 2] -= 40; } const t = document.createElement('canvas'); t.width = W; t.height = H; t.getContext('2d').putImageData(img, 0, 0); g.imageSmoothingEnabled = true; g.drawImage(t, 0, 0, W * 4, H * 4); g.strokeStyle = '#5a4a3a'; g.lineWidth = 1.5; for (let i = W; i < W * H - W; i++) { if (hgt[i] > 0 && (hgt[i + 1] <= 0 || hgt[i + W] <= 0 || hgt[i - 1] <= 0)) { g.fillStyle = '#4a3b2c'; g.fillRect((i % W) * 4, ((i / W) | 0) * 4, 3, 3); } } if (showLabels) { const NAMES = ['Republic of Etoile', 'Kingdom of Tanar', 'Monch', 'Zeldan Caliphate', 'Orlesia', 'Grand Duchy of Vell', 'Empire of Sorn', 'Harmar', 'Coast League', 'Isle Kha', 'Bretonia', 'Marsh Union']; g.textAlign = 'center'; seeds.forEach((sd, k) => { g.font = `600 ${k % 3 ? 26 : 34}px 'Fraunces Variable',Georgia,serif`; g.fillStyle = '#3a2a1a'; g.strokeStyle = '#fff8'; g.lineWidth = 4; const [a, ...b] = NAMES[k % NAMES.length].split(' of '); g.strokeText(a, sd.x * 4, sd.y * 4); g.fillText(a, sd.x * 4, sd.y * 4); }); } };
  root.append(cv, h('div', { style: { position: 'absolute', right: '12px', bottom: '12px', display: 'grid', gap: '4px' } }, ...[['⟳', () => { seed++; gen(); }], ['🏷', () => { showLabels = !showLabels; gen(); }], ['＋', () => { nStates = Math.min(12, nStates + 1); gen(); }], ['－', () => { nStates = Math.max(3, nStates - 1); gen(); }]].map(([l, f]) => h('button', { style: { width: '34px', height: '34px', background: '#f5efe0', border: '1px solid #7a4a1e', borderRadius: '4px' }, onclick: f }, l))), h('div', { style: { position: 'absolute', left: '12px', top: '12px', background: '#f5efe0ee', border: '1px solid #7a4a1e', padding: '8px 10px', fontSize: '12px', display: 'grid', gap: '6px', width: '190px' } }, h('b', {}, '☰ Fantasy Map-ish'), h('div.k-row', { style: { flexWrap: 'wrap', gap: '4px' } }, ...['Layers', 'Style', 'Options', 'Tools', 'About'].map((t) => h('span', { style: { border: '1px solid #b89', padding: '1px 4px' } }, t))), slider('States', 3, 12, nStates, 1, (v) => { nStates = v; gen(); }), btn('New map', () => { seed++; gen(); }, 'pri')));
  gen();
  window.__demoProof = async () => { seed = 6; gen(); return 'generated heightmap + 9 political states'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['ritmo-simplex-wave-studio'])(root, T); }
