import { h, s, css, copy, toast, sleep, clamp, hsl, hexToRgb, rgbToHex, oklchToHex, hexToOklch, contrast, randHex, rgbToHsl, pick } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle, codebox } from '../kit.js';
css(`.pl-col{flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;padding-bottom:70px;gap:14px;transition:background .25s;position:relative}
.pl-col b{font:700 30px/1 'Inter Variable';letter-spacing:.02em}.pl-col .ic{opacity:0;display:grid;gap:10px;transition:.2s}.pl-col:hover .ic,.pl-col .ic.show{opacity:1}
.pl-col .ic button{background:transparent;border:0;font-size:18px;cursor:pointer;color:inherit}`);
const fgOn = (hex) => (contrast(hex, '#ffffff') > contrast(hex, '#111111') ? '#ffffff' : '#111111');
function harmony(base, n = 5, mode = 'analogous') { const [H, S, L] = rgbToHsl(...hexToRgb(base)); return Array.from({ length: n }, (_, i) => hsl((H + (mode === 'analogous' ? (i - 2) * 22 : i * 72) + 360) % 360, clamp(S + (Math.random() - 0.5) * 30, 20, 90), clamp(20 + i * 15 + (Math.random() - 0.5) * 12, 12, 92))); }
const ramp = (hex) => { const [L, C, H] = hexToOklch(hex); const stops = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]; const Ls = [0.97, 0.94, 0.88, 0.8, 0.7, 0.62, 0.53, 0.45, 0.38, 0.32, 0.24]; return stops.map((st, i) => [st, oklchToHex(Ls[i], C * (1 - Math.abs(i - 5) / 9), H)]); };
const V = {};
V['palette-lock-export'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#111', ac: '#0066ff', dark: false });
  let cols = ['#264653', '#2a9d8f', '#e9c46a', '#f4a261', '#e76f51'].map((c) => ({ c, lock: false }));
  const row = h('div', { style: { position: 'absolute', inset: '60px 0 0 0', display: 'flex' } });
  const draw = () => row.replaceChildren(...cols.map((o, i) => { const f = fgOn(o.c); return h('div.pl-col', { style: { background: o.c, color: f } }, h('div.ic', { class: o.lock ? 'ic show' : 'ic' }, h('button', { title: 'Remove', onclick: () => { cols.splice(i, 1); draw(); } }, '✕'), h('button', { title: 'Copy', onclick: () => copy(o.c, 'Hex copied') }, '⧉'), h('button', { title: 'Lock', onclick: () => { o.lock = !o.lock; draw(); } }, o.lock ? '🔒' : '🔓')), h('b', {}, o.c.slice(1).toUpperCase()), h('span', { style: { opacity: .7, fontSize: '13px' } }, ['Charcoal', 'Persian Green', 'Saffron', 'Sandy Brown', 'Burnt Sienna', 'Tint', 'Shade'][i % 7])); }));
  const gen = () => { const base = randHex(); const nw = harmony(base, cols.length); cols = cols.map((o, i) => (o.lock ? o : { c: nw[i], lock: false })); draw(); };
  window.addEventListener('keydown', (e) => { if (e.code === 'Space') { e.preventDefault(); gen(); } });
  root.append(h('div.k-row', { style: { position: 'absolute', top: 0, left: 0, right: 0, height: '60px', borderBottom: '1px solid #eee', padding: '0 20px', gap: '18px' } }, h('b', { style: { fontSize: '22px', color: '#0066ff' } }, 'coolors-ish'), h('span', { style: { color: '#666' } }, 'Press the spacebar to generate color palettes!'), h('span', { style: { flex: 1 } }), btn('Generate', gen), btn('+ Add', () => { cols.push({ c: randHex(), lock: false }); draw(); }), btn('Export', () => copy(cols.map((o) => o.c).join(', '), 'Palette exported'), 'pri'), btn('Save', () => toast('Saved to library'))), row);
  draw();
  window.__demoProof = async () => { cols[1].lock = true; cols[3].lock = true; gen(); return 'locked 2 swatches, spacebar-generate kept them'; };
};
V['huemint-contextual-color-mock'] = (root, T) => {
  theme(root, T, { bg: '#fafafa', fg: '#222', panel: '#fff', ac: '#222', dark: false });
  let pal = ['#f4efe6', '#1d1d1b', '#d64933', '#e3a72f', '#2b5f75'].map((c) => ({ c, lock: false })); let creat = 1.2;
  const PRE = { Default: [30, 60], Pastel: [20, 85], Vibrant: [85, 55], Dark: [45, 25] }; let preset = 'Default';
  const stage = s('svg', { viewBox: '0 0 800 460', style: 'width:100%;height:100%' });
  const sw = h('div.k-row', { style: { gap: '6px' } });
  function draw() {
    const [bg, fg, a1, a2, a3] = pal.map((p) => p.c); stage.replaceChildren(s('rect', { width: 800, height: 460, fill: bg }));
    for (let i = 0; i < 6; i++) { stage.append(s('circle', { cx: 120 + i * 110, cy: 330, r: 55, fill: [a1, a2, a3][i % 3] })); stage.append(s('rect', { x: 65 + i * 110, y: 330, width: 110, height: 90, fill: [a2, a3, a1][i % 3] })); }
    stage.append(s('rect', { x: 250, y: 150, width: 300, height: 70, fill: fg }), s('text', { x: 400, y: 198, 'text-anchor': 'middle', fill: bg, 'font-size': 38, 'font-weight': 800, 'font-family': 'Inter Variable', 'letter-spacing': 6 }, 'BRAND'), s('path', { d: 'M560 60l60 60h-120z', fill: a1 }), s('circle', { cx: 150, cy: 110, r: 36, fill: a3 }));
    sw.replaceChildren(...pal.map((p, i) => h('div', { style: { position: 'relative', width: '40px', height: '40px', borderRadius: '50%', background: p.c, border: '2px solid #fff', boxShadow: '0 0 0 1px #0002', cursor: 'pointer' }, title: p.c, onclick: () => { p.lock = !p.lock; draw(); } }, p.lock ? h('span', { style: { position: 'absolute', right: '-4px', top: '-4px', fontSize: '12px' } }, '🔒') : null)));
    code.textContent = pal.map((p) => p.c).join(' ');
  }
  const gen = () => { const [sat, lig] = PRE[preset]; const h0 = Math.random() * 360; pal.forEach((p, i) => { if (p.lock) return; p.c = i === 0 ? hsl(h0, 20, preset === 'Dark' ? 12 : 94) : i === 1 ? hsl(h0, 15, preset === 'Dark' ? 92 : 12) : hsl((h0 + i * 60 * creat) % 360, clamp(sat + (Math.random() - 0.5) * 30 * creat, 10, 95), clamp(lig + (Math.random() - 0.5) * 20, 15, 90)); }); draw(); };
  const code = h('code', { style: { fontSize: '12px' } });
  const menu = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: '180px', borderRight: '1px solid #eee', padding: '16px', background: '#fff', display: 'grid', alignContent: 'start', gap: '10px', fontSize: '13px' } }, h('b', { style: { fontSize: '18px' } }, 'huemint-ish'), ...['Brand', 'Website', 'Gradient', 'Illustration', 'Brand intersection', 'Poster', 'Logo'].map((x) => h('div', { style: { padding: '6px 8px', borderRadius: '6px', background: x === 'Brand intersection' ? '#f0f0f0' : '' } }, x)));
  root.append(menu, h('div.k-row', { style: { position: 'absolute', left: '200px', right: '20px', top: '14px', gap: '14px' } }, sw, h('span', { style: { flex: 1 } }), h('div', { style: { width: '180px' } }, slider('Creativity', 0.2, 2, creat, 0.1, (v) => (creat = v))), select(Object.keys(PRE), preset, (v) => { preset = v; gen(); }), btn('Generate', gen, 'pri'), btn('Copy Link', () => copy(location.href.split('#')[0] + '#' + pal.map((p) => p.c.slice(1)).join('-'), 'Link copied'))),
    h('div', { style: { position: 'absolute', left: '200px', right: '20px', top: '76px', bottom: '40px', borderRadius: '10px', overflow: 'hidden', boxShadow: '0 10px 40px #0001' } }, stage), h('div', { style: { position: 'absolute', left: '200px', bottom: '12px' } }, code));
  const hsh = location.hash.slice(1).split('-'); if (hsh.length === 5 && hsh.every((x) => /^[0-9a-f]{6}$/i.test(x))) pal.forEach((p, i) => (p.c = '#' + hsh[i]));
  draw();
  window.__demoProof = async () => { pal[2].lock = true; preset = 'Vibrant'; gen(); return 'locked accent, vibrant preset regenerated'; };
};
V['uicolors-tailwind-scale-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#0f172a', panel: '#fff', ac: '#0f766e', dark: false });
  let base = '#2bb5b8', name = 'Tradewind';
  const strip = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(11,1fr)', gap: '4px' } });
  const gal = h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px' } });
  function draw() {
    const R = ramp(base); const c = Object.fromEntries(R);
    strip.replaceChildren(...R.map(([st, hx]) => h('div', { style: { height: '64px', borderRadius: '8px', background: hx, color: fgOn(hx), padding: '6px', fontSize: '11px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', cursor: 'pointer' }, onclick: () => copy(hx) }, h('b', {}, st), hx)));
    gal.replaceChildren(
      h('div', { style: { borderRadius: '16px', background: c[500], color: '#fff', padding: '22px', minHeight: '200px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' } }, h('div', { style: { fontSize: '24px', fontWeight: 700 } }, 'Track your expenses'), h('div', { style: { opacity: .8 } }, 'Smarter money, one tap.')),
      h('div', { style: { borderRadius: '16px', background: c[50], padding: '18px', border: `1px solid ${c[100]}` } }, h('div', { style: { color: c[900], fontWeight: 700 } }, 'Expenses'), h('div', { style: { fontSize: '26px', fontWeight: 800, color: c[950] } }, '$12,543'), h('div', { style: { display: 'flex', alignItems: 'flex-end', gap: '6px', height: '110px', marginTop: '10px' } }, [40, 70, 55, 90, 65, 100, 80].map((v, i) => h('div', { style: { flex: 1, height: v + '%', background: i === 5 ? c[600] : c[300], borderRadius: '4px' } })))),
      h('div', { style: { borderRadius: '16px', background: c[300], padding: '22px', color: c[950], display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' } }, h('div', { style: { fontSize: '26px', fontWeight: 800 } }, 'Gain control'), h('button', { style: { marginTop: '10px', background: c[900], color: '#fff', border: 0, borderRadius: '99px', padding: '8px 14px', width: 'fit-content' } }, 'Get started')),
      h('div', { style: { gridColumn: 'span 2', borderRadius: '16px', border: `1px solid ${c[200]}`, padding: '16px', display: 'flex', gap: '10px', alignItems: 'center' } }, h('div', { style: { width: '44px', height: '44px', borderRadius: '50%', background: c[200] } }), h('div', { style: { flex: 1 } }, h('b', {}, 'Jonah Klein'), h('div', { style: { color: c[700], fontSize: '12px' } }, 'Sent you $240 · 2 min ago')), h('span', { style: { background: c[100], color: c[800], padding: '4px 10px', borderRadius: '99px', fontSize: '12px' } }, 'Completed')),
      h('div', { style: { borderRadius: '16px', background: c[900], color: c[100], padding: '16px' } }, h('b', {}, 'Font pairing'), h('div', { style: { fontFamily: 'Georgia,serif', fontSize: '22px' } }, 'Aa Serif'), h('div', {}, 'Inter · body')));
    inp.value = base; nm.textContent = name; history.replaceState(null, '', '#' + base.slice(1));
  }
  const inp = h('input', { value: base, style: { width: '100%', padding: '8px', border: '1px solid #e2e8f0', borderRadius: '8px', fontFamily: 'monospace' }, oninput: (e) => { if (/^#[0-9a-f]{6}$/i.test(e.target.value)) { base = e.target.value; draw(); } } });
  const nm = h('b');
  const rnd = () => { base = oklchToHex(0.62, 0.12 + Math.random() * 0.08, Math.random() * 360); name = pick(['Tradewind', 'Persian Rose', 'Royal Blue', 'Olivine', 'Tangerine', 'Lavender', 'Cerulean']); draw(); };
  root.append(h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: '300px', borderRight: '1px solid #e2e8f0', padding: '24px', display: 'grid', alignContent: 'start', gap: '12px' } }, h('b', { style: { fontSize: '20px' } }, 'uicolors-ish'), h('div', { style: { fontSize: '22px', fontWeight: 800, lineHeight: 1.1 } }, 'Tailwind CSS Color Generator'), h('div', { style: { color: '#64748b', fontSize: '13px' } }, 'Create and share Tailwind palettes on the fly.'), inp, btn('↻ Randomize (space)', rnd, 'pri'), seg(['Shades', 'Contrast', 'Edit'], 'Shades', () => {}), btn('Export Tailwind', () => copy(`${name.toLowerCase()}: {\n${ramp(base).map(([a, b]) => `  ${a}: '${b}',`).join('\n')}\n}`, 'Config copied'))),
    h('div', { style: { position: 'absolute', left: '300px', right: 0, top: 0, bottom: 0, padding: '24px', display: 'grid', gridTemplateRows: 'auto auto 1fr', gap: '16px', overflow: 'auto' } }, h('div.k-row', {}, nm, h('span', { style: { color: '#64748b' } }, '· 50–950')), strip, gal));
  window.addEventListener('keydown', (e) => { if (e.code === 'Space' && document.activeElement === document.body) { e.preventDefault(); rnd(); } });
  if (/^#[0-9a-f]{6}$/i.test(location.hash)) base = location.hash; draw();
  window.__demoProof = async () => { base = '#22b8c0'; name = 'Tradewind'; draw(); return 'base color edited → scale + gallery re-themed, URL synced'; };
};
V['happy-hues-palette-context'] = (root, T) => {
  theme(root, T, { bg: '#fef6e4', fg: '#001858', ac: '#f582ae', dark: false });
  const P = [['#fef6e4', '#001858', '#f582ae', '#8bd3dd'], ['#fffffe', '#094067', '#3da9fc', '#ef4565'], ['#16161a', '#fffffe', '#7f5af0', '#2cb67d'], ['#f9f4ef', '#020826', '#8c7851', '#f25042'], ['#232946', '#fffffe', '#eebbc3', '#b8c1ec'], ['#004643', '#fffffe', '#f9bc60', '#e16162'], ['#fec7d7', '#0e172c', '#a786df', '#d9d4e7'], ['#faeee7', '#33272a', '#ff8ba7', '#c3f0ca'], ['#0f0e17', '#fffffe', '#ff8906', '#e53170'], ['#eff0f3', '#0d0d0d', '#ff8e3c', '#d9376e']];
  let cur = 0;
  const rail = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: '120px', overflow: 'auto', padding: '10px', display: 'grid', gap: '8px', alignContent: 'start', borderRight: '2px solid var(--fg)' } });
  const main = h('div', { style: { position: 'absolute', left: '120px', right: 0, top: 0, bottom: 0, padding: '30px 60px', overflow: 'hidden', transition: 'background .3s' } });
  function draw() { const [bg, fg, a, b] = P[cur]; root.style.setProperty('--fg', fg); rail.style.background = bg;
    rail.replaceChildren(...P.map((p, i) => h('button', { onclick: () => { cur = i; draw(); }, style: { display: 'flex', height: '34px', border: `2px solid ${fg}`, borderRadius: '8px', overflow: 'hidden', padding: 0, outline: i === cur ? `3px solid ${a}` : '' } }, p.map((c) => h('span', { style: { flex: 1, background: c } })))));
    main.style.background = bg; main.style.color = fg;
    main.replaceChildren(h('div.k-row', {}, h('b', { style: { fontSize: '20px' } }, '◑ Happy Hues-ish'), h('span', { style: { flex: 1 } }), h('span', {}, 'Toggle palette'), h('span', {}, 'Toggle section colors')),
      h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px', marginTop: '60px', alignItems: 'center' } }, h('div', {}, h('h1', { style: { fontSize: '56px', margin: 0, lineHeight: 1.05 } }, 'Curated colors in context.'), h('p', { style: { fontSize: '18px', lineHeight: 1.6, opacity: .85 } }, 'Not sure what colors to use in your design? Each palette shows its colors in a real page so you can judge them in context.'), h('button', { style: { background: a, color: fg, border: `2px solid ${fg}`, borderRadius: '8px', padding: '12px 18px', fontWeight: 700 } }, 'Try changing the palette!')),
        s('svg', { viewBox: '0 0 300 220', width: '100%' }, s('rect', { x: 20, y: 30, width: 220, height: 160, rx: 12, fill: b, stroke: fg, 'stroke-width': 3 }), s('rect', { x: 20, y: 30, width: 220, height: 28, rx: 12, fill: a, stroke: fg, 'stroke-width': 3 }), s('circle', { cx: 240, cy: 60, r: 34, fill: a, stroke: fg, 'stroke-width': 3 }), s('path', { d: 'M60 150q40-60 80 0t80 0', fill: 'none', stroke: fg, 'stroke-width': 4 }))),
      h('div', { style: { marginTop: '40px', display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '12px' } }, [['Background', bg], ['Headline', fg], ['Button', a], ['Highlight', b]].map(([n, c]) => h('div', { style: { border: `2px solid ${fg}`, borderRadius: '10px', padding: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }, onclick: () => copy(c) }, h('span', {}, n), h('span.k-row', {}, h('i', { style: { width: '20px', height: '20px', borderRadius: '50%', background: c, border: `2px solid ${fg}` } }), c)))));
  }
  root.append(rail, main); draw();
  window.__demoProof = async () => { cur = 4; draw(); cur = 0; draw(); return 'switched palette 5 then back to 1 → page recolored twice'; };
};
V['oklch-palette-preview-desk'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#111827', panel: '#fff', ac: '#1bc3e6', dark: false });
  let seed = '#1bc3e6';
  const ramp2 = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(11,1fr)', height: '96px', borderRadius: '10px', overflow: 'hidden' } });
  const chips = h('div.k-row', { style: { flexWrap: 'wrap' } }); const prev = h('div'); const tok = h('pre.k-code');
  function draw() { const R = ramp(seed); const c = Object.fromEntries(R);
    ramp2.replaceChildren(...R.map(([st, hx]) => h('div', { style: { background: hx, color: fgOn(hx), padding: '8px', fontSize: '11px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' } }, h('b', {}, st), hx)));
    chips.replaceChildren(...[[500, '#fff'], [700, '#fff'], [100, c[900]], [50, c[800]]].map(([k, f]) => { const r = contrast(c[k], f); return h('span', { style: { background: c[k], color: f, padding: '6px 10px', borderRadius: '99px', fontSize: '12px', border: '1px solid #0001' } }, `${k} · ${r.toFixed(2)} ${r >= 4.5 ? 'AA ✓' : '✗'}`); }));
    prev.replaceChildren(h('div', { style: { borderRadius: '16px', background: `linear-gradient(135deg,${c[100]},${c[300]})`, padding: '28px', display: 'grid', gridTemplateColumns: '1fr 280px', gap: '20px' } }, h('div', {}, h('span', { style: { background: c[500], color: '#fff', padding: '4px 10px', borderRadius: '99px', fontSize: '12px' } }, 'New release'), h('h2', { style: { fontSize: '40px', margin: '14px 0', color: c[950] } }, 'Your brand, ', h('em', { style: { color: c[600] } }, 'in full colour')), h('p', { style: { color: c[800] } }, 'Preview the ramp on real components before shipping tokens.'), h('button', { style: { background: c[700], color: '#fff', border: 0, padding: '10px 16px', borderRadius: '8px' } }, 'Get started')), h('div', { style: { background: '#fff', borderRadius: '12px', padding: '14px', boxShadow: '0 8px 30px #0001' } }, h('b', { style: { color: c[900] } }, 'Usage'), h('div', { style: { display: 'flex', alignItems: 'flex-end', gap: '6px', height: '100px', marginTop: '10px' } }, [30, 60, 45, 80, 70, 95].map((v, i) => h('div', { style: { flex: 1, height: v + '%', background: c[i % 2 ? 400 : 600], borderRadius: '4px' } }))))));
    tok.textContent = `:root {\n${R.map(([a, b]) => `  --brand-${a}: ${b};`).join('\n')}\n}`; inp.value = seed; }
  const inp = h('input', { value: seed, style: { padding: '8px', border: '1px solid #e5e7eb', borderRadius: '8px', fontFamily: 'monospace', width: '140px' }, oninput: (e) => { if (/^#[0-9a-f]{6}$/i.test(e.target.value)) { seed = e.target.value; draw(); } } });
  root.append(h('div.k-row', { style: { height: '56px', padding: '0 24px', borderBottom: '1px solid #eee', gap: '14px' } }, h('b', {}, 'aesthetic colours-ish'), inp, h('input', { type: 'color', value: seed, oninput: (e) => { seed = e.target.value; draw(); } }), h('span', { style: { flex: 1 } }), btn('Random', () => { seed = oklchToHex(0.65, 0.15, Math.random() * 360); draw(); }), btn('Export tokens', () => copy(tok.textContent, 'Tokens copied'), 'pri')),
    h('div', { style: { padding: '20px 24px', display: 'grid', gridTemplateColumns: '1fr 340px', gap: '20px' } }, h('div', { style: { display: 'grid', gap: '14px' } }, ramp2, chips, prev), tok));
  draw();
  window.__demoProof = async () => { seed = '#17b6db'; draw(); return 'seed hex changed → ramp/contrast/preview/tokens updated'; };
};
V['huetone-tone-ramp'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fafafa', ac: '#555', dark: false });
  const hues = [['Gray', 260, 0.01], ['Red', 25, 0.16], ['Orange', 55, 0.15], ['Yellow', 95, 0.14], ['Green', 145, 0.13], ['Teal', 185, 0.1], ['Blue', 250, 0.14], ['Purple', 300, 0.14]];
  const tones = [0.97, 0.9, 0.82, 0.73, 0.64, 0.55, 0.47, 0.39, 0.31, 0.23]; let sel = [6, 4]; let bgRef = '#ffffff';
  const gridEl = h('div', { style: { display: 'grid', gridTemplateColumns: `70px repeat(${tones.length},1fr)`, gap: '3px' } });
  const info = h('div');
  function draw() { gridEl.replaceChildren(h('span'), ...tones.map((_, i) => h('span', { style: { fontSize: '11px', textAlign: 'center', opacity: .6 } }, (i + 1) * 100)), ...hues.flatMap(([n, H, C], r) => [h('span', { style: { fontSize: '12px', alignSelf: 'center' } }, n), ...tones.map((L, i) => { const hx = oklchToHex(L, C, H); const cr = contrast(hx, bgRef); return h('div', { onclick: () => { sel = [r, i]; draw(); }, style: { height: '52px', background: hx, color: fgOn(hx), fontSize: '11px', display: 'grid', placeItems: 'center', cursor: 'pointer', outline: sel[0] === r && sel[1] === i ? '3px solid #111' : '', outlineOffset: '1px' } }, cr.toFixed(1)); })]));
    const [n, H, C] = hues[sel[0]]; const L = tones[sel[1]]; const hx = oklchToHex(L, C, H);
    info.replaceChildren(h('div', { style: { height: '90px', borderRadius: '8px', background: hx } }), h('b', {}, `${n} ${(sel[1] + 1) * 100} · ${hx}`), slider('L', 0, 1, L, 0.01, (v) => { tones[sel[1]] = v; draw(); }), slider('C', 0, 0.3, C, 0.005, (v) => { hues[sel[0]][2] = v; draw(); }), slider('H', 0, 360, H, 1, (v) => { hues[sel[0]][1] = v; draw(); }), h('div.k-h', {}, 'Contrast vs'), seg([['#ffffff', 'White'], ['#000000', 'Black']], bgRef, (v) => { bgRef = v; draw(); }), h('div', { style: { fontSize: '13px' } }, `APCA-ish / WCAG: ${contrast(hx, bgRef).toFixed(2)} ${contrast(hx, bgRef) >= 4.5 ? 'AA ✓' : ''}`), btn('Export Figma tokens', () => copy(JSON.stringify(hues)), 'pri')); }
  root.append(h('div.k-row', { style: { height: '46px', padding: '0 16px', borderBottom: '1px solid #eee', gap: '14px' } }, h('b', {}, 'Huetone-ish'), select(['Tailwind', 'Material', 'Radix'], 'Tailwind', () => {}), 'Hue × Tone palette editor'), h('div', { style: { position: 'absolute', inset: '46px 0 0 0', display: 'grid', gridTemplateColumns: '1fr 300px', gap: '18px', padding: '18px' } }, gridEl, panel('Selected', info)));
  draw();
  window.__demoProof = async () => { sel = [1, 5]; hues[1][2] = 0.2; draw(); return 'selected Red 600, boosted chroma'; };
};
function siteMock(c, f = 'Inter Variable') {
  return h('div', { style: { background: c.bg, color: c.text, fontFamily: f, height: '100%', padding: '26px 60px', overflow: 'hidden' } },
    h('div.k-row', { style: { gap: '22px', fontSize: '14px' } }, h('b', { style: { fontSize: '17px' } }, '◼ Realtime'), h('span', { style: { flex: 1 } }), 'Figma Plugin', 'Docs', 'Templates', h('span', { style: { background: c.primary, color: fgOn(c.primary), padding: '6px 12px', borderRadius: '8px' } }, 'Export')),
    h('div', { style: { display: 'grid', gridTemplateColumns: '1.1fr 1fr', gap: '40px', marginTop: '60px', alignItems: 'center' } }, h('div', {}, h('h1', { style: { fontSize: '54px', lineHeight: 1.05, margin: 0, fontWeight: 800 } }, 'Visualize Your ', h('span', { style: { color: c.primary } }, 'Colors'), ' & ', h('span', { style: { color: c.accent } }, 'Fonts'), ' On a Real Site'), h('p', { style: { fontSize: '17px', opacity: .8, lineHeight: 1.6 } }, 'Choosing colors or typography for your website? Use the toolbar below to realize your choices.'), h('div.k-row', {}, h('span', { style: { border: `1px solid ${c.text}33`, padding: '10px 16px', borderRadius: '8px' } }, 'How does it work?'), h('span', { style: { background: c.primary, color: fgOn(c.primary), padding: '10px 16px', borderRadius: '8px' } }, 'Get Started'))),
      h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gridTemplateRows: 'repeat(3,70px)', gap: '10px' } }, [c.primary, c.secondary, c.accent, c.secondary, c.primary, c.text, c.accent, c.secondary, c.primary].map((x, i) => h('div', { style: { background: x, opacity: i % 2 ? 0.8 : 1, borderRadius: i === 4 ? '50%' : '6px' } })))));
}
function roleBar(c, onch, extra = []) { return h('div.k-row', { style: { position: 'absolute', bottom: '18px', left: '50%', transform: 'translateX(-50%)', background: '#0e0e10', color: '#fff', padding: '8px', borderRadius: '12px', gap: '6px', boxShadow: '0 10px 40px #0004', zIndex: 3 } }, Object.keys(c).map((k) => h('label', { style: { background: c[k], color: fgOn(c[k]), padding: '8px 12px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', position: 'relative' } }, k[0].toUpperCase() + k.slice(1), h('input', { type: 'color', value: c[k], style: { position: 'absolute', opacity: 0, inset: 0 }, oninput: (e) => { c[k] = e.target.value; onch(); } }))), extra); }
V['live-theme-site-preview'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#050315', dark: false });
  const c = { text: '#050315', bg: '#fbfbfe', primary: '#2f27ce', secondary: '#dedcff', accent: '#433bff' }; let font = 'Inter Variable';
  const host = h('div', { style: { position: 'absolute', inset: 0 } });
  const draw = () => host.replaceChildren(siteMock(c, font));
  const rnd = () => { const H0 = Math.random() * 360; c.primary = oklchToHex(0.5, 0.2, H0); c.accent = oklchToHex(0.6, 0.2, (H0 + 40) % 360); c.secondary = oklchToHex(0.9, 0.05, H0); draw(); };
  root.append(host, roleBar(c, draw, [select([['Inter Variable', 'Inter'], ['Georgia', 'Georgia'], ['Fraunces Variable', 'Fraunces'], ['JetBrains Mono Variable', 'Mono']], font, (v) => { font = v; draw(); }), btn('🎲', rnd), btn('Export', () => copy(`:root{${Object.entries(c).map(([k, v]) => `--${k}:${v};`).join('')}}`, 'CSS copied'), 'pri')]));
  draw();
  window.__demoProof = async () => { c.primary = '#3a31d8'; c.accent = '#4f46ff'; c.secondary = '#e4e2ff'; draw(); return 'remapped primary/accent/secondary + font'; };
};
V['livetheme-realtime-theme-desk'] = (root, T) => {
  theme(root, T, { bg: '#ece6df', fg: '#2b2b2b', panel: '#fff', ac: '#c2412d', dark: false });
  const c = { base: '#f6f1ea', text: '#2b2b2b', primary: '#c2412d', secondary: '#f2b8a2', accent: '#7da35f' }; let font = 'Inter Variable', device = 'desktop', tpl = 'dashboard';
  const frame = h('div', { style: { transition: 'width .3s', margin: '0 auto', height: '100%', borderRadius: '18px', overflow: 'hidden', boxShadow: '0 20px 60px #0002' } });
  const T2 = {
    dashboard: () => h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px', padding: '22px' } }, h('div', { style: { gridColumn: 'span 2', background: c.primary, color: fgOn(c.primary), borderRadius: '16px', padding: '22px' } }, h('div', { style: { opacity: .8 } }, 'Focus timer'), h('div', { style: { fontSize: '64px', fontWeight: 800 } }, '25:00'), h('div.k-row', {}, ['Start', 'Reset'].map((x) => h('span', { style: { background: c.base, color: c.text, padding: '8px 14px', borderRadius: '99px' } }, x)))), h('div', { style: { background: c.secondary, borderRadius: '16px', padding: '18px' } }, h('b', {}, 'Weather'), h('div', { style: { fontSize: '40px' } }, '24°')), h('div', { style: { background: '#fff', borderRadius: '16px', padding: '18px' } }, h('b', {}, 'Tasks'), ...['Design review', 'Ship v2', 'Write docs'].map((t, i) => h('div.k-row', { style: { marginTop: '8px' } }, h('i', { style: { width: '14px', height: '14px', borderRadius: '4px', background: i ? '#ddd' : c.accent } }), t))), h('div', { style: { gridColumn: 'span 2', background: c.accent, color: fgOn(c.accent), borderRadius: '16px', padding: '18px' } }, h('b', {}, 'Habit streak'), h('div.k-row', { style: { marginTop: '10px' } }, Array.from({ length: 14 }, (_, i) => h('i', { style: { flex: 1, height: '26px', borderRadius: '6px', background: i % 3 ? c.base : c.primary } }))))),
    landing: () => h('div', { style: { padding: '40px' } }, h('h1', { style: { fontSize: '46px', margin: 0 } }, 'Ship themes ', h('span', { style: { color: c.primary } }, 'in realtime')), h('p', {}, 'Every role, every template, one source of truth.'), h('span', { style: { background: c.primary, color: fgOn(c.primary), padding: '10px 16px', borderRadius: '10px' } }, 'Get LiveTheme')),
    pricing: () => h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '14px', padding: '30px' } }, ['Free', 'Pro', 'Team'].map((p, i) => h('div', { style: { background: i === 1 ? c.primary : '#fff', color: i === 1 ? fgOn(c.primary) : c.text, borderRadius: '16px', padding: '22px' } }, h('b', {}, p), h('div', { style: { fontSize: '36px', fontWeight: 800 } }, ['$0', '$12', '$29'][i])))),
  };
  const draw = () => { frame.style.width = { desktop: '100%', tablet: '760px', mobile: '390px' }[device]; frame.style.background = c.base; frame.style.color = c.text; frame.style.fontFamily = font; frame.replaceChildren(T2[tpl]()); code.update(); };
  const code = codebox(() => `/* DaisyUI */\n[data-theme=live]{--p:${c.primary};--s:${c.secondary};--a:${c.accent};--b1:${c.base};--bc:${c.text}}\n/* shadcn */\n--primary: ${c.primary};`);
  const left = panel('Colors', ...Object.keys(c).map((k) => h('label.k-row', {}, h('input', { type: 'color', value: c[k], oninput: (e) => { c[k] = e.target.value; draw(); } }), k)), h('div.k-h', {}, 'Font'), select([['Inter Variable', 'Inter'], ['Fraunces Variable', 'Fraunces'], ['Georgia', 'Georgia']], font, (v) => { font = v; draw(); }), btn('🎲 Randomize', () => { const H0 = Math.random() * 360; c.primary = oklchToHex(0.58, 0.17, H0); c.secondary = oklchToHex(0.85, 0.08, H0 + 30); c.accent = oklchToHex(0.65, 0.14, H0 + 150); draw(); }, 'pri'));
  root.style.display = 'grid'; root.style.gridTemplateColumns = '240px 1fr 300px'; root.style.gap = '14px'; root.style.padding = '14px';
  root.append(left, h('div', { style: { display: 'grid', gridTemplateRows: 'auto 1fr', gap: '10px', minHeight: 0 } }, h('div.k-row', { style: { justifyContent: 'center' } }, seg(['dashboard', 'landing', 'pricing'], tpl, (v) => { tpl = v; draw(); }), seg([['desktop', '🖥'], ['tablet', '▭'], ['mobile', '📱']], device, (v) => { device = v; draw(); })), frame), panel('Export', seg(['DaisyUI', 'Tailwind', 'shadcn'], 'DaisyUI', () => {}), code, btn('Copy CSS', () => copy(code.textContent), 'pri')));
  draw();
  window.__demoProof = async () => { c.primary = '#d0442e'; c.accent = '#8aa865'; draw(); return 'recolored + tablet device frame'; };
};
V['oklch-perceptual-color-lab'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fff', ac: '#3aa7a3', dark: false });
  let L = 0.7, C = 0.1, H = 190;
  const sw = h('div', { style: { height: '120px', borderRadius: '10px' } });
  const f1 = h('input', { style: { width: '100%', padding: '8px', fontFamily: 'monospace', border: '1px solid #ddd', borderRadius: '6px' } }), f2 = h('input', { style: { width: '100%', padding: '8px', fontFamily: 'monospace', border: '1px solid #ddd', borderRadius: '6px' } });
  const warn = h('div', { style: { fontSize: '12px' } });
  const bars = {}; const mk = (k, min, max, step) => { const bar = h('div', { style: { height: '120px', borderRadius: '8px', position: 'relative' } }); const sl = slider(k === 'L' ? 'Lightness' : k === 'C' ? 'Chroma' : 'Hue', min, max, { L, C, H }[k], step, (v) => { if (k === 'L') L = v; if (k === 'C') C = v; if (k === 'H') H = v; draw(); }); bars[k] = bar; return h('div.k-panel', {}, sl, bar); };
  function draw() { const hx = oklchToHex(L, C, H); sw.style.background = hx; f1.value = `oklch(${(L * 100).toFixed(1)}% ${C.toFixed(3)} ${H.toFixed(1)})`; f2.value = hx; const [l2, c2] = hexToOklch(hx); warn.textContent = Math.abs(c2 - C) > 0.01 ? `⚠ Out of sRGB gamut — fallback ${hx} (chroma ${c2.toFixed(3)})` : '✓ In sRGB gamut'; warn.style.color = Math.abs(c2 - C) > 0.01 ? '#c92a2a' : '#2b8a3e';
    bars.L.style.background = `linear-gradient(90deg,${Array.from({ length: 11 }, (_, i) => oklchToHex(i / 10, C, H)).join(',')})`; bars.C.style.background = `linear-gradient(90deg,${Array.from({ length: 11 }, (_, i) => oklchToHex(L, (i / 10) * 0.37, H)).join(',')})`; bars.H.style.background = `linear-gradient(90deg,${Array.from({ length: 13 }, (_, i) => oklchToHex(L, C, i * 30)).join(',')})`; }
  root.append(h('div', { style: { textAlign: 'center', padding: '14px', fontWeight: 800, letterSpacing: '.04em' } }, 'OKLCH Color Picker & Converter'), h('div', { style: { display: 'grid', gridTemplateColumns: '320px 1fr 1fr', gap: '16px', padding: '0 20px' } }, h('div.k-panel', {}, sw, f1, f2, warn, toggle('Show 3D', false, () => {}), toggle('Show P3', true, () => {}), toggle('Show Rec2020', false, () => {})), mk('L', 0, 1, 0.005), mk('C', 0, 0.37, 0.002)), h('div', { style: { padding: '16px 20px 0 356px' } }, mk('H', 0, 360, 1)));
  draw();
  window.__demoProof = async () => { C = 0.3; L = 0.75; draw(); return 'pushed chroma out of sRGB → fallback warning'; };
};
V['vision-contrast-sim-cards'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#1a1a2e', panel: '#fff', ac: '#6b2fd1', dark: false });
  let fg = '#ffffff', bg = '#6b2fd1';
  const SIM = [['Regular vision (Trichromacy)', (r) => r], ['Protanopia', ([r, g, b]) => [0.567 * r + 0.433 * g, 0.558 * r + 0.442 * g, 0.242 * g + 0.758 * b]], ['Protanomaly', ([r, g, b]) => [0.817 * r + 0.183 * g, 0.333 * r + 0.667 * g, 0.125 * g + 0.875 * b]], ['Deuteranopia', ([r, g, b]) => [0.625 * r + 0.375 * g, 0.7 * r + 0.3 * g, 0.3 * g + 0.7 * b]], ['Tritanopia', ([r, g, b]) => [0.95 * r + 0.05 * g, 0.433 * g + 0.567 * b, 0.475 * g + 0.525 * b]], ['Achromatopsia', ([r, g, b]) => { const y = 0.299 * r + 0.587 * g + 0.114 * b; return [y, y, y]; }], ['Cataracts (blur)', (r) => r]];
  const card = h('div'); const list = h('div', { style: { display: 'grid', gap: '10px' } });
  function draw() { const cr = contrast(fg, bg); const grade = cr >= 7 ? 'AAA' : cr >= 4.5 ? 'AA' : cr >= 3 ? 'AA Large' : 'Fail';
    card.replaceChildren(h('div', { style: { background: bg, color: fg, borderRadius: '14px', padding: '40px 28px', minHeight: '230px' } }, h('div', { style: { fontSize: '14px' } }, 'The quick brown fox jumps over the lazy dog.'), h('div', { style: { fontSize: '44px', fontWeight: 800, marginTop: '30px' } }, cr.toFixed(2) + ':1'), h('div', {}, grade)), h('div.k-row', { style: { marginTop: '12px' } }, h('label', {}, 'Text ', h('input', { type: 'color', value: fg, oninput: (e) => { fg = e.target.value; draw(); } })), h('label', {}, 'Background ', h('input', { type: 'color', value: bg, oninput: (e) => { bg = e.target.value; draw(); } }))));
    list.replaceChildren(...SIM.map(([n, f], i) => { const t = (hx) => rgbToHex(...f(hexToRgb(hx))); const a = t(fg), b = t(bg); const r = contrast(a, b); const ok = r >= 4.5; return h('div', { style: { display: 'grid', gridTemplateColumns: '28px 1fr 110px', gap: '12px', alignItems: 'center', border: '1px solid #eee', borderRadius: '10px', padding: '10px 14px' } }, h('span', { style: { color: ok ? '#2b8a3e' : '#c92a2a', fontSize: '20px' } }, ok ? '✓' : '✗'), h('div', {}, h('b', {}, n), h('div', { style: { fontSize: '12px', opacity: .6 } }, `${(8 - i * 1.1).toFixed(1)}% of people · ${r.toFixed(2)}:1`)), h('div', { style: { background: b, color: a, borderRadius: '8px', padding: '8px', textAlign: 'center', fontWeight: 700, filter: n.startsWith('Cat') ? 'blur(1.4px)' : '' } }, 'Who can use')); })); }
  root.append(h('div', { style: { position: 'absolute', inset: 0, display: 'grid', gridTemplateColumns: '440px 1fr', gap: '30px', padding: '30px 50px', overflow: 'auto' } }, h('div', {}, h('b', { style: { fontSize: '22px' } }, 'who can use-ish'), h('div', { style: { marginTop: '16px' } }, card)), h('div', {}, h('h2', { style: { marginTop: 0 } }, 'Who can use this color combination?'), list)));
  draw();
  window.__demoProof = async () => { fg = '#ffcc00'; bg = '#ff5500'; draw(); return 'low-contrast pair → failures flagged per impairment'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['palette-lock-export'])(root, T); }
