import { h, s, drag, localPos, clamp, copy, toast, sleep, rng, pick, noise2, fitCanvas } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle } from '../kit.js';
const V = {};
// ---------- falling sand
V['falling-sand-particle-sandbox'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#333', panel: '#fff', ac: '#e91e63', dark: false });
  const W = 300, H = 300; const E = { empty: 0, wall: 1, sand: 2, water: 3, plant: 4, fire: 5, lava: 6, ice: 7, gas: 8, stone: 9, seed: 10, dust: 11 };
  const COL = ['#f5e6e8', '#7a7a7a', '#e0b86a', '#4a90e2', '#5cb85c', '#ff6a00', '#e0401e', '#bfe8ff', '#cdb4db', '#8d8d8d', '#a0522d', '#d9c2a0'];
  const g = new Uint8Array(W * H); const cv = h('canvas', { width: W, height: H, style: { width: '640px', height: '640px', imageRendering: 'pixelated', cursor: 'crosshair', touchAction: 'none' } });
  const ctx = cv.getContext('2d'); const img = ctx.createImageData(W, H); let cur = 2, size = 6, paused = false;
  const rgb = COL.map((c) => [parseInt(c.slice(1, 3), 16), parseInt(c.slice(3, 5), 16), parseInt(c.slice(5, 7), 16)]);
  const get = (x, y) => (x < 0 || y < 0 || x >= W || y >= H ? 1 : g[y * W + x]);
  const swap = (a, b) => { const t = g[a]; g[a] = g[b]; g[b] = t; };
  const step = () => { for (let y = H - 1; y >= 0; y--) { const dir = Math.random() < 0.5 ? 1 : -1; for (let xi = 0; xi < W; xi++) { const x = dir > 0 ? xi : W - 1 - xi; const i = y * W + x, t = g[i]; if (t === 2 || t === 11 || t === 10) { const d = Math.random() < 0.5 ? 1 : -1; if (get(x, y + 1) === 0 || get(x, y + 1) === 3) swap(i, i + W); else if (get(x + d, y + 1) === 0 || get(x + d, y + 1) === 3) swap(i, i + W + d); else if (t === 10 && get(x, y + 1) === 2 && Math.random() < 0.02) g[i] = 4; } else if (t === 3 || t === 6) { const d = Math.random() < 0.5 ? 1 : -1; if (get(x, y + 1) === 0) swap(i, i + W); else if (get(x + d, y + 1) === 0) swap(i, i + W + d); else if (get(x + d, y) === 0) swap(i, i + d); if (t === 6) for (const n of [1, -1, W, -W]) { const j = i + n; if (j >= 0 && j < W * H) { if (g[j] === 3) { g[j] = 9; g[i] = 9; } else if (g[j] === 4 && Math.random() < 0.3) g[j] = 5; } } } else if (t === 4) { for (const n of [1, -1, W, -W]) { const j = i + n; if (j >= 0 && j < W * H && g[j] === 3 && Math.random() < 0.05) g[j] = 4; } } else if (t === 5) { if (Math.random() < 0.1) { g[i] = Math.random() < 0.3 ? 8 : 0; continue; } for (const n of [1, -1, W, -W]) { const j = i + n; if (j >= 0 && j < W * H && (g[j] === 4 || g[j] === 11) && Math.random() < 0.5) g[j] = 5; } if (get(x, y - 1) === 0 && Math.random() < 0.5) swap(i, i - W); } else if (t === 8) { const d = Math.floor(Math.random() * 3) - 1; if (Math.random() < 0.02) g[i] = 0; else if (get(x + d, y - 1) === 0) swap(i, i - W + d); } else if (t === 7) { for (const n of [1, -1, W, -W]) { const j = i + n; if (j >= 0 && j < W * H && g[j] === 3 && Math.random() < 0.01) g[j] = 7; } } } } };
  const render = () => { for (let i = 0; i < W * H; i++) { const c = rgb[g[i]]; const v = g[i] ? ((i * 2654435761) >>> 28) - 8 : 0; img.data[i * 4] = c[0] + v; img.data[i * 4 + 1] = c[1] + v; img.data[i * 4 + 2] = c[2] + v; img.data[i * 4 + 3] = 255; } ctx.putImageData(img, 0, 0); };
  const paint = (px, py, t) => { for (let y = -size; y <= size; y++) for (let x = -size; x <= size; x++) if (x * x + y * y <= size * size && Math.random() < 0.7) { const X = px + x, Y = py + y; if (X >= 0 && Y >= 0 && X < W && Y < H && (t === 0 || g[Y * W + X] === 0)) g[Y * W + X] = t; } };
  const at = (e) => { const p = localPos(e, cv); const r = cv.getBoundingClientRect(); return [Math.floor((p.x / r.width) * W), Math.floor((p.y / r.height) * H)]; };
  drag(cv, { start: (e) => paint(...at(e), cur), move: (e) => paint(...at(e), cur) });
  const loop = () => { if (!paused) { step(); step(); } render(); requestAnimationFrame(loop); };
  for (let x = 0; x < W; x++) for (let y = H - 34 - Math.floor(6 + 5 * Math.sin(x / 20)); y < H; y++) g[y * W + x] = 2;
  const names = Object.keys(E); const els = h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '3px' } }, names.map((n, i) => h('button', { style: { background: i ? COL[i] : '#fff', border: i === cur ? '2px solid #111' : '1px solid #ccc', fontSize: '11px', padding: '6px 2px', color: [1, 3, 5, 6, 9, 10].includes(i) ? '#fff' : '#222', borderRadius: '3px' }, onclick: (e) => { cur = i; els.querySelectorAll('button').forEach((b) => (b.style.border = '1px solid #ccc')); e.target.style.border = '2px solid #111'; } }, n === 'empty' ? 'Erase' : n[0].toUpperCase() + n.slice(1))));
  root.style.display = 'grid'; root.style.gridTemplateColumns = '220px 1fr 200px';
  root.append(h('div', { style: { borderRight: '1px solid #eee', fontSize: '13px' } }, ...['Discover more', 'Falling Sand', 'Procedural Worlds', 'Browser Games', 'Physics Toys', 'Cellular Automata', 'Pixel Art Tools'].map((t, i) => h('div', { style: { padding: '14px', borderBottom: '1px solid #eee', color: i ? '#444' : '#e91e63', fontWeight: i ? 400 : 700 } }, t, i ? h('span', { style: { float: 'right', opacity: .4 } }, '›') : null))), h('div', { style: { display: 'grid', placeItems: 'center', background: '#faf7f8' } }, cv), h('div', { style: { padding: '8px', display: 'grid', gap: '6px', alignContent: 'start' } }, h('div.k-row', {}, btn(paused ? '▶' : '❚❚', (e) => { paused = !paused; e.target.textContent = paused ? '▶' : '❚❚'; }), btn('Reset', () => g.fill(0)), btn('Info', () => toast('Sandspiel-ish'))), slider('Brush', 1, 20, size, 1, (v) => (size = v)), els));
  loop();
  window.__demoProof = async () => { cur = 3; paint(100, 60, 3); paint(200, 40, 3); cur = 1; for (let x = 60; x < 240; x++) g[180 * W + x] = x > 140 && x < 160 ? 0 : 1; paint(150, 120, 2); paint(60, 100, 4); for (let i = 0; i < 80; i++) step(); cur = 2; return 'sand + water + wall + plant simulated 80 steps'; };
};
// ---------- webgl-ish fluid (CPU stable fluids, low-res)
V['webgl-fluid-paint-stage'] = (root, T) => {
  theme(root, T, { bg: '#000', fg: '#ddd', panel: '#1a1a1a', ac: '#2fa1d6', dark: true });
  const N = 128, M = 80; const sz = N * M; const u = new Float32Array(sz), v = new Float32Array(sz), u0 = new Float32Array(sz), v0 = new Float32Array(sz), p = new Float32Array(sz), dv = new Float32Array(sz); const r = new Float32Array(sz), gg = new Float32Array(sz), b = new Float32Array(sz), r0 = new Float32Array(sz), g0 = new Float32Array(sz), b0 = new Float32Array(sz);
  const P = { diss: 0.995, vel: 0.99, curl: 30, radius: 6, bloom: true, paused: false };
  const I = (x, y) => clamp(y, 0, M - 1) * N + clamp(x, 0, N - 1);
  const samp = (f, x, y) => { x = clamp(x, 0, N - 1.001); y = clamp(y, 0, M - 1.001); const x0 = x | 0, y0 = y | 0, fx = x - x0, fy = y - y0; const a = f[y0 * N + x0], bb = f[y0 * N + x0 + 1], c = f[(y0 + 1) * N + x0], d = f[(y0 + 1) * N + x0 + 1]; return (a * (1 - fx) + bb * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy; };
  const adv = (dst, src, k) => { for (let y = 0; y < M; y++) for (let x = 0; x < N; x++) { const i = y * N + x; dst[i] = samp(src, x - u[i], y - v[i]) * k; } };
  const cv = h('canvas', { width: N, height: M, style: { position: 'absolute', inset: 0, width: '100%', height: '100%', filter: 'blur(3px) saturate(1.4)' } }); const ctx = cv.getContext('2d'); const img = ctx.createImageData(N, M);
  const splat = (x, y, dx, dy, col) => { const R = P.radius; for (let j = -R * 2; j <= R * 2; j++) for (let i = -R * 2; i <= R * 2; i++) { const w = Math.exp(-(i * i + j * j) / (R * R)); const k = I(Math.round(x) + i, Math.round(y) + j); u[k] += dx * w; v[k] += dy * w; r[k] += col[0] * w; gg[k] += col[1] * w; b[k] += col[2] * w; } };
  const step = () => { // vorticity
    for (let y = 1; y < M - 1; y++) for (let x = 1; x < N - 1; x++) { const i = y * N + x; p[i] = v[i + 1] - v[i - 1] - (u[i + N] - u[i - N]); } for (let y = 2; y < M - 2; y++) for (let x = 2; x < N - 2; x++) { const i = y * N + x; const gx = Math.abs(p[i + 1]) - Math.abs(p[i - 1]), gy = Math.abs(p[i + N]) - Math.abs(p[i - N]); const l = Math.hypot(gx, gy) + 1e-5; u[i] += (gy / l) * p[i] * P.curl * 0.0005; v[i] -= (gx / l) * p[i] * P.curl * 0.0005; }
    for (let y = 1; y < M - 1; y++) for (let x = 1; x < N - 1; x++) { const i = y * N + x; dv[i] = -0.5 * (u[i + 1] - u[i - 1] + v[i + N] - v[i - N]); p[i] = 0; } for (let k = 0; k < 14; k++) for (let y = 1; y < M - 1; y++) for (let x = 1; x < N - 1; x++) { const i = y * N + x; p[i] = (dv[i] + p[i - 1] + p[i + 1] + p[i - N] + p[i + N]) / 4; } for (let y = 1; y < M - 1; y++) for (let x = 1; x < N - 1; x++) { const i = y * N + x; u[i] -= 0.5 * (p[i + 1] - p[i - 1]); v[i] -= 0.5 * (p[i + N] - p[i - N]); }
    u0.set(u); v0.set(v); adv(u, u0, P.vel); adv(v, v0, P.vel); r0.set(r); g0.set(gg); b0.set(b); adv(r, r0, P.diss); adv(gg, g0, P.diss); adv(b, b0, P.diss); };
  const render = () => { for (let i = 0; i < sz; i++) { img.data[i * 4] = Math.min(255, r[i] * 255); img.data[i * 4 + 1] = Math.min(255, gg[i] * 255); img.data[i * 4 + 2] = Math.min(255, b[i] * 255); img.data[i * 4 + 3] = 255; } ctx.putImageData(img, 0, 0); };
  const hue = () => { const hh = Math.random() * 6; const f = hh % 1, i = hh | 0; const c = [[1, f, 0], [1 - f, 1, 0], [0, 1, f], [0, 1 - f, 1], [f, 0, 1], [1, 0, 1 - f]][i]; return c.map((x) => x * 0.9); };
  let col = hue(); root.addEventListener('pointerdown', () => (col = hue()));
  root.addEventListener('pointermove', (e) => { const q = localPos(e, cv); const rr = cv.getBoundingClientRect(); splat((q.x / rr.width) * N, (q.y / rr.height) * M, e.movementX * 0.3, e.movementY * 0.3, col.map((x) => x * 0.3)); });
  const loop = () => { if (!P.paused) step(); render(); requestAnimationFrame(loop); };
  const burst = () => { for (let k = 0; k < 6; k++) splat(Math.random() * N, Math.random() * M, (Math.random() - 0.5) * 20, (Math.random() - 0.5) * 20, hue()); };
  const gui = h('div', { style: { position: 'absolute', right: '12px', top: '10px', width: '245px', background: '#1a1a1a', font: '11px Lucida Grande,sans-serif', color: '#eee', padding: '4px 6px', display: 'grid', gap: '4px' } }, h('div', { style: { background: '#000', padding: '3px' } }, 'quality · high'), slider('density diffusion', 0.95, 1, P.diss, 0.001, (x) => (P.diss = x)), slider('velocity diffusion', 0.95, 1, P.vel, 0.001, (x) => (P.vel = x)), slider('vorticity', 0, 50, P.curl, 1, (x) => (P.curl = x)), slider('splat radius', 2, 14, P.radius, 1, (x) => (P.radius = x)), toggle('paused', false, (x) => (P.paused = x)), btn('Random splats', burst), toggle('bloom', true, (x) => (cv.style.filter = x ? 'blur(3px) saturate(1.4) brightness(1.2)' : 'blur(2px)')), h('div', { style: { borderLeft: '3px solid #2fa1d6', paddingLeft: '4px' } }, 'Capture'), h('div', { style: { borderLeft: '3px solid #e61d5f', paddingLeft: '4px' } }, 'Github'));
  root.append(cv, gui); loop();
  window.__demoProof = async () => { burst(); burst(); for (let i = 0; i < 30; i++) step(); return 'random splats advected with vorticity'; };
};
// ---------- reaction diffusion
function grayScott(W, H, F, K, seed) { const A = new Float32Array(W * H).fill(1), B = new Float32Array(W * H); const R = rng(seed); for (let k = 0; k < 14; k++) { const cx = (R() * W) | 0, cy = (R() * H) | 0; for (let y = -4; y < 4; y++) for (let x = -4; x < 4; x++) B[((cy + y + H) % H) * W + ((cx + x + W) % W)] = 1; } const A2 = new Float32Array(W * H), B2 = new Float32Array(W * H); return { A, B, F, K, step(n = 1) { for (let s2 = 0; s2 < n; s2++) { for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) { const i = y * W + x; const l = (y * W + ((x + 1) % W)), rr = y * W + ((x - 1 + W) % W), u = ((y + 1) % H) * W + x, d = ((y - 1 + H) % H) * W + x; const la = A[l] + A[rr] + A[u] + A[d] - 4 * A[i], lb = B[l] + B[rr] + B[u] + B[d] - 4 * B[i]; const ab2 = A[i] * B[i] * B[i]; A2[i] = A[i] + (1.0 * la * 0.2 - ab2 + this.F * (1 - A[i])); B2[i] = B[i] + (0.5 * lb * 0.2 - ab2 + 0) + ab2 * 0 + (0.5 * lb * 0 + 0); B2[i] = B[i] + (0.1 * lb + ab2 - (this.K + this.F) * B[i]); } A.set(A2); B.set(B2); } } }; }
V['reaction-diffusion-playground'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#1a73e8', dark: false }); root.style.overflow = 'auto';
  const MAPS = [[[90, 80, 0], [240, 220, 40]], [[250, 220, 0], [120, 40, 0]], [[60, 60, 60], [230, 230, 230]], [[20, 60, 180], [120, 220, 255]], [[10, 10, 10], [80, 220, 80]], [[140, 0, 120], [255, 200, 60]]];
  const PRE = [[0.055, 0.062], [0.029, 0.057], [0.037, 0.06], [0.03, 0.055], [0.025, 0.06], [0.039, 0.058]];
  const W = 96, H = 96; const sims = PRE.map(([F, K], i) => ({ gs: grayScott(W, H, F, K, i + 1), cv: h('canvas', { width: W, height: H, style: { width: '100%', aspectRatio: '1', imageRendering: 'auto', display: 'block' } }), map: MAPS[i] }));
  const render = (sm) => { const ctx = sm.cv.getContext('2d'); const img = ctx.createImageData(W, H); const [c0, c1] = sm.map; for (let i = 0; i < W * H; i++) { const t = clamp((sm.gs.A[i] - sm.gs.B[i]) * 1.2, 0, 1); for (let k = 0; k < 3; k++) img.data[i * 4 + k] = c1[k] + (c0[k] - c1[k]) * t; img.data[i * 4 + 3] = 255; } ctx.putImageData(img, 0, 0); };
  let sel = 0; const fs = slider('Feed rate f', 0.01, 0.1, PRE[0][0], 0.001, (x) => (sims[sel].gs.F = x)), ks = slider('Kill rate k', 0.04, 0.07, PRE[0][1], 0.0005, (x) => (sims[sel].gs.K = x));
  sims.forEach((sm, i) => { sm.cv.addEventListener('pointerdown', (e) => { sel = i; fs.set(sm.gs.F); ks.set(sm.gs.K); const p = localPos(e, sm.cv); const r = sm.cv.getBoundingClientRect(); const cx = ((p.x / r.width) * W) | 0, cy = ((p.y / r.height) * H) | 0; for (let y = -3; y < 3; y++) for (let x = -3; x < 3; x++) sm.gs.B[clamp(cy + y, 0, H - 1) * W + clamp(cx + x, 0, W - 1)] = 1; }); });
  const loop = () => { sims.forEach((sm) => { sm.gs.step(4); render(sm); }); requestAnimationFrame(loop); };
  root.append(h('div', { style: { padding: '30px 40px', maxWidth: '1300px' } }, h('h1', { style: { fontSize: '30px', margin: '0 0 12px' } }, 'Reaction-Diffusion Playground'), h('p', { style: { lineHeight: 1.6, fontSize: '14px' } }, 'Reaction-diffusion is a mathematical model describing how two chemicals might ', h('b', {}, 'react'), ' to each other as they ', h('b', {}, 'diffuse'), ' through a medium together. It was ', h('u', { style: { color: '#1a73e8' } }, 'proposed by Alan Turing in 1952'), ' as a possible explanation for how the interesting patterns of stripes and spots that are seen on the skin/fur of animals like giraffes and leopards form.'), h('p', { style: { lineHeight: 1.6, fontSize: '14px' } }, 'Each tile below runs the Gray-Scott model live. Click a tile to seed it and edit its feed/kill rates.'), h('div.k-row', { style: { gap: '20px', margin: '16px 0' } }, h('button', { style: { background: '#1a73e8', color: '#fff', border: 0, padding: '10px 18px', borderRadius: '4px' }, onclick: () => sims.forEach((sm, i) => (sm.gs = grayScott(W, H, sm.gs.F, sm.gs.K, i + 9))) }, 'Reseed all'), h('div', { style: { width: '220px' } }, fs), h('div', { style: { width: '220px' } }, ks))), h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(6,1fr)' } }, sims.map((sm) => sm.cv)));
  sims.forEach((sm) => sm.gs.step(600)); loop();
  window.__demoProof = async () => 'six Gray-Scott tiles evolving live';
};
// ---------- orb farm
V['orb-farm-ecosystem-terrarium'] = (root, T) => {
  theme(root, T, { bg: '#c9d4dd', fg: '#111', ac: '#335', dark: false }); root.style.fontFamily = 'Tahoma,Verdana,sans-serif'; root.style.fontSize = '12px';
  const W = 200, H = 150; const cv = h('canvas', { width: W, height: H, style: { width: '640px', height: '480px', imageRendering: 'pixelated', border: '2px solid #778', background: '#9ab' } }); const ctx = cv.getContext('2d'); const img = ctx.createImageData(W, H);
  const g = new Uint8Array(W * H); const COL = [[150, 175, 195], [214, 196, 150], [60, 140, 70], [240, 240, 240], [120, 110, 100]]; let cur = 1;
  for (let x = 0; x < W; x++) for (let y = H - 18 - Math.floor(4 * Math.sin(x / 17)); y < H; y++) g[y * W + x] = 1;
  const R = rng(4); const daph = Array.from({ length: 16 }, () => ({ x: R() * W, y: R() * 100 + 10, vx: 0, vy: 0, e: 1 }));
  const step = () => { for (let y = H - 2; y >= 0; y--) for (let x = 0; x < W; x++) { const i = y * W + x; if (g[i] === 1 && g[i + W] === 0) { g[i + W] = 1; g[i] = 0; } else if (g[i] === 2) { if (Math.random() < 0.004) { const d = [1, -1, -W, -W + 1, -W - 1][(Math.random() * 5) | 0]; if (g[i + d] === 0 && i + d > 0) g[i + d] = 2; } } } daph.forEach((d) => { d.vx += (Math.random() - 0.5) * 0.3; d.vy += (Math.random() - 0.5) * 0.3 + 0.01; d.vx *= 0.9; d.vy *= 0.9; d.x = clamp(d.x + d.vx, 1, W - 2); d.y = clamp(d.y + d.vy, 1, H - 20); const i = (d.y | 0) * W + (d.x | 0); for (const n of [0, 1, -1, W, -W]) if (g[i + n] === 2 && Math.random() < 0.1) { g[i + n] = 0; d.e = Math.min(2, d.e + 0.1); } }); };
  const render = () => { for (let i = 0; i < W * H; i++) { const c = COL[g[i]]; const y = (i / W) | 0; const dk = g[i] ? 0 : y * 0.25; img.data[i * 4] = c[0] - dk; img.data[i * 4 + 1] = c[1] - dk; img.data[i * 4 + 2] = c[2] - dk * 0.5; img.data[i * 4 + 3] = 255; } daph.forEach((d) => { for (const [ox, oy, k] of [[0, 0, 0], [1, 0, 1], [0, 1, 1], [-1, 0, 0]]) { const i = (((d.y + oy) | 0) * W + ((d.x + ox) | 0)) * 4; img.data[i] = k ? 210 : 240; img.data[i + 1] = k ? 90 : 240; img.data[i + 2] = k ? 200 : 240; } }); ctx.putImageData(img, 0, 0); };
  const paint = (e) => { const p = localPos(e, cv); const r = cv.getBoundingClientRect(); const cx = ((p.x / r.width) * W) | 0, cy = ((p.y / r.height) * H) | 0; for (let y = -3; y <= 3; y++) for (let x = -3; x <= 3; x++) if (x * x + y * y < 10) { const X = cx + x, Y = cy + y; if (X >= 0 && Y >= 0 && X < W && Y < H) g[Y * W + X] = cur; } };
  drag(cv, { start: paint, move: paint });
  const loop = () => { step(); render(); requestAnimationFrame(loop); };
  let page = 1; const pages = ['This is your personal aquatic ecosystem to mature, sculpt, and observe.', 'Plant algae (green) — it grows slowly toward the light.', 'Daphnia (pink) swim around and graze on algae to survive.', 'Balance the tank: too little algae and the daphnia starve.'];
  const pg = h('div'), cnt = h('div', { style: { position: 'absolute', right: '24px', bottom: '56px', fontSize: '18px' } });
  const dlg = h('div', { style: { position: 'absolute', left: '50%', top: '50%', transform: 'translate(-60%,-50%)', width: '440px', height: '420px', background: '#e9ecf0', border: '2px solid #556', boxShadow: '4px 4px 0 #0004' } }, h('div', { style: { background: '#223', color: '#fff', padding: '3px 6px' } }, 'Orb.Farm-ish'), h('div', { style: { margin: '12px', padding: '12px', background: '#fff', border: '1px solid #99a', borderRadius: '10px' } }, h('b', { style: { fontSize: '15px' } }, 'Welcome to Orb.Farm-ish!'), pg), s('svg', { viewBox: '0 0 100 100', width: 180, height: 180, style: 'display:block;margin:10px auto' }, s('ellipse', { cx: 50, cy: 52, rx: 26, ry: 36, fill: '#fde', stroke: '#b4a', 'stroke-width': 2 }), s('circle', { cx: 50, cy: 30, r: 4, fill: '#222' }), s('path', { d: 'M40 70q10 10 20 0M30 20l-14 -12M70 20l14 -12', stroke: '#b4a', 'stroke-width': 2, fill: 'none' })), cnt, h('button', { style: { position: 'absolute', right: '14px', bottom: '14px', padding: '6px 14px', border: '2px outset #ccc', background: '#ddd' }, onclick: () => { page++; if (page > 4) dlg.remove(); else upd(); } }, 'Next >'));
  const upd = () => { pg.textContent = pages[page - 1]; cnt.textContent = `${page}/4`; }; upd();
  const tools = h('div', { style: { position: 'absolute', right: '20px', top: '20px', width: '140px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4px', background: '#d8dde4', padding: '6px', border: '2px solid #889' } }, h('div', { style: { gridColumn: '1/-1', textAlign: 'center', fontSize: '26px' } }, '🌡'), ...['Sand', 'Algae', 'Glass', 'Stone', 'Water', 'Daphnia'].map((n, i) => h('button', { style: { padding: '6px 2px', border: '2px outset #ccc', background: '#e9ecf0', fontSize: '11px' }, onclick: () => { if (n === 'Daphnia') daph.push({ x: 100, y: 40, vx: 0, vy: 0, e: 1 }); else cur = { Sand: 1, Algae: 2, Glass: 3, Stone: 4, Water: 0 }[n]; } }, n)));
  root.append(h('div', { style: { position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', background: 'linear-gradient(#8a98a6,#c7d0d9)' } }, cv), tools, dlg);
  for (let x = 20; x < 180; x += 3) for (let y = H - 30; y < H - 20; y++) if (Math.random() < 0.5) g[y * W + x] = 2;
  loop();
  window.__demoProof = async () => { for (let i = 0; i < 40; i++) step(); return 'tank running with daphnia grazing (onboarding 1/4)'; };
};
// ---------- neato marble (WebGL domain warp)
export function glCanvas(frag, uniforms) { const cv = h('canvas', { style: { width: '100%', height: '100%', display: 'block' } }); const gl = cv.getContext('webgl', { preserveDrawingBuffer: true }); if (!gl) return { cv, draw() {} }; const sh = (t, src) => { const x = gl.createShader(t); gl.shaderSource(x, src); gl.compileShader(x); if (!gl.getShaderParameter(x, gl.COMPILE_STATUS)) console.warn(gl.getShaderInfoLog(x)); return x; }; const pr = gl.createProgram(); gl.attachShader(pr, sh(gl.VERTEX_SHADER, 'attribute vec2 p;void main(){gl_Position=vec4(p,0,1);}')); gl.attachShader(pr, sh(gl.FRAGMENT_SHADER, 'precision highp float;uniform vec2 R;uniform float t;' + Object.keys(uniforms).map((k) => `uniform ${Array.isArray(uniforms[k]) ? 'vec' + uniforms[k].length : 'float'} ${k};`).join('') + frag)); gl.linkProgram(pr); gl.useProgram(pr); const b = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, b); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]), gl.STATIC_DRAW); const loc = gl.getAttribLocation(pr, 'p'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0); return { cv, gl, draw(t) { const r = cv.getBoundingClientRect(); if (cv.width !== (r.width | 0)) { cv.width = r.width | 0; cv.height = r.height | 0; } gl.viewport(0, 0, cv.width, cv.height); gl.uniform2f(gl.getUniformLocation(pr, 'R'), cv.width, cv.height); gl.uniform1f(gl.getUniformLocation(pr, 't'), t); for (const [k, v] of Object.entries(uniforms)) { const l = gl.getUniformLocation(pr, k); Array.isArray(v) ? gl['uniform' + v.length + 'fv'](l, v) : gl.uniform1f(l, v); } gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4); } }; }
const hex3 = (c) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16) / 255);
V['neato-marble-shader-desk'] = (root, T) => {
  theme(root, T, { bg: '#1e1e1e', fg: '#ccc', panel: '#252525', ac: '#fff', acfg: '#000', dark: true });
  const U = { warp: 4, scale: 1.2, speed: 0.15, c1: hex3('#f4f1dc'), c2: hex3('#9ccf9a'), c3: hex3('#2f7d6d'), c4: hex3('#e7d88f') };
  const G = glCanvas(`float hs(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hs(i),hs(i+vec2(1,0)),f.x),mix(hs(i+vec2(0,1)),hs(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<6;i++){v+=a*n(p);p*=2.;a*=.5;}return v;}void main(){vec2 uv=gl_FragCoord.xy/R.y*scale;float T=t*speed;vec2 q=vec2(fbm(uv+T),fbm(uv+vec2(5.2,1.3)));vec2 r=vec2(fbm(uv+warp*q+vec2(1.7,9.2)+T*.5),fbm(uv+warp*q+vec2(8.3,2.8)));float f=fbm(uv+warp*r);vec3 c=mix(c1,c2,smoothstep(.2,.6,f));c=mix(c,c3,smoothstep(.55,.9,length(q)*f));c=mix(c,c4,smoothstep(.6,1.,r.x));c=mix(c,c1,smoothstep(.75,.95,f));gl_FragColor=vec4(c,1);}`, U);
  const sw = (k) => h('input', { type: 'color', value: '#' + U[k].map((x) => Math.round(x * 255).toString(16).padStart(2, '0')).join(''), oninput: (e) => (U[k] = hex3(e.target.value)), style: { width: '40px', height: '22px', border: 0 } });
  root.style.display = 'grid'; root.style.gridTemplateColumns = '280px 1fr 60px';
  root.append(h('div', { style: { padding: '12px', display: 'grid', gap: '10px', alignContent: 'start', fontSize: '12px' } }, h('div.k-row', {}, h('b', { style: { fontSize: '15px' } }, 'Marble-ish'), h('span', { style: { flex: 1 } }), select(['Neato', 'Agate', 'Ink'], 'Neato', (v) => { const P2 = { Neato: ['#f4f1dc', '#9ccf9a', '#2f7d6d', '#e7d88f'], Agate: ['#f8efe6', '#d98a5f', '#6b2d3a', '#f2c46d'], Ink: ['#f2f2f2', '#6a8fd6', '#1c2a55', '#c7d6ff'] }[v]; ['c1', 'c2', 'c3', 'c4'].forEach((k, i) => (U[k] = hex3(P2[i]))); })), h('div.k-h', {}, 'Colours'), ...['c1', 'c2', 'c3', 'c4'].map((k, i) => h('div.k-row', {}, h('span', { style: { flex: 1 } }, ['Base', 'Vein', 'Deep', 'Accent'][i]), sw(k))), h('div.k-h', {}, 'Shape'), slider('Warp', 0, 10, U.warp, 0.1, (v) => (U.warp = v)), slider('Scale', 0.5, 6, U.scale, 0.1, (v) => (U.scale = v)), slider('Speed', 0, 1, U.speed, 0.01, (v) => (U.speed = v)), h('div.k-h', {}, 'Export'), btn('Download PNG', () => { const a = h('a', { download: 'marble.png', href: G.cv.toDataURL() }); a.click(); }, 'pri'), btn('Randomise', () => { U.warp = 2 + Math.random() * 6; U.scale = 1 + Math.random() * 3; })), h('div', { style: { position: 'relative' } }, G.cv), h('div', { style: { background: '#000' } }));
  const t0 = performance.now(); const loop = () => { G.draw((performance.now() - t0) / 1000 + 10); requestAnimationFrame(loop); }; loop();
  window.__demoProof = async () => { U.warp = 4.6; return 'domain-warped marble shader live'; };
};
// ---------- signal garden
V['constellation-signal-garden'] = (root, T) => {
  theme(root, T, { bg: '#0b1633', fg: '#dfe8ff', panel: '#13224a', ac: '#7dd3fc', dark: true });
  const cv = h('canvas', { style: { position: 'absolute', inset: 0 } }); root.append(cv);
  const st = { mode: 'signal', lines: true, twinkle: true, cursor: 'attract', count: 90 };
  let stars = []; const R = rng(7); const mk = () => (stars = Array.from({ length: st.count }, () => ({ x: R(), y: R(), r: R() * 1.6 + 0.4, p: R() * 6 }))); mk(); let mouse = { x: 0.5, y: 0.5 }; let t = 0;
  root.addEventListener('pointermove', (e) => { const p = localPos(e, cv); mouse = { x: p.x / cv.W, y: p.y / cv.H }; });
  const loop = () => { fitCanvas(cv, root); const g = cv.g, W = cv.W, H = cv.H; t += 0.016; g.fillStyle = '#0b1633'; g.fillRect(0, 0, W, H); const grad = g.createRadialGradient(W * 0.3, H * 0.2, 0, W * 0.3, H * 0.2, W * 0.8); grad.addColorStop(0, '#1b2e66'); grad.addColorStop(1, '#0b163300'); g.fillStyle = grad; g.fillRect(0, 0, W, H); stars.forEach((sr) => { if (st.cursor === 'attract') { sr.x += (mouse.x - sr.x) * 0.0006; sr.y += (mouse.y - sr.y) * 0.0006; } }); if (st.lines) { g.strokeStyle = '#7dd3fc33'; g.lineWidth = 1; for (let i = 0; i < stars.length; i++) for (let j = i + 1; j < stars.length; j++) { const a = stars[i], b = stars[j]; const d = Math.hypot((a.x - b.x) * W, (a.y - b.y) * H); if (d < 110) { g.globalAlpha = 1 - d / 110; g.beginPath(); g.moveTo(a.x * W, a.y * H); g.lineTo(b.x * W, b.y * H); g.stroke(); } } g.globalAlpha = 1; } stars.forEach((sr) => { const tw = st.twinkle ? 0.6 + 0.4 * Math.sin(t * 2 + sr.p) : 1; g.fillStyle = `rgba(220,235,255,${tw})`; g.beginPath(); g.arc(sr.x * W, sr.y * H, sr.r * (st.mode === 'signal' ? 1.4 : 1), 0, 7); g.fill(); }); requestAnimationFrame(loop); };
  const chip = (l, on) => h('button', { style: { background: on ? '#7dd3fc22' : '#ffffff08', border: '1px solid ' + (on ? '#7dd3fc' : '#ffffff22'), color: '#dfe8ff', padding: '6px 12px', borderRadius: '99px', fontSize: '12px' }, onclick: (e) => { const b = e.currentTarget; const now = b.style.borderColor.includes('125') ? false : true; b.style.borderColor = now ? '#7dd3fc' : '#ffffff22'; b.style.background = now ? '#7dd3fc22' : '#ffffff08'; if (l.startsWith('lines')) st.lines = now; if (l.startsWith('twinkle')) st.twinkle = now; if (l.startsWith('cursor')) st.cursor = now ? 'attract' : 'off'; if (l.startsWith('respawn')) mk(); } }, l);
  const stat = (k, v) => h('div', { style: { background: '#13224acc', border: '1px solid #ffffff18', borderRadius: '8px', padding: '8px 10px', fontSize: '11px' } }, h('div', { style: { opacity: .6, letterSpacing: '.1em', fontSize: '9px' } }, k), h('b', {}, v));
  const card = h('div', { style: { position: 'absolute', left: '50%', top: '40px', transform: 'translateX(-50%)', width: '900px', background: '#13224add', border: '1px solid #ffffff22', borderRadius: '14px', padding: '24px', display: 'grid', gridTemplateColumns: '1fr 1.2fr', gap: '24px', backdropFilter: 'blur(6px)' } }, h('div', {}, h('div', { style: { fontSize: '10px', letterSpacing: '.2em', opacity: .6 } }, 'CONSTELLATION · INTERACTIVE'), h('div', { style: { font: "700 48px/1 'Inter Variable'", margin: '10px 0' } }, '✧ Signal', h('br'), 'Garden'), h('p', { style: { fontSize: '13px', opacity: .8, lineHeight: 1.6 } }, 'A living constellation you can nudge: stars drift toward your cursor, link up with neighbours and twinkle in response to the signal mode.')), h('div', { style: { display: 'grid', gap: '12px', alignContent: 'start' } }, h('div', { style: { fontSize: '10px', letterSpacing: '.2em', opacity: .6 } }, 'FIELD MODE'), seg(['quiet', 'signal', 'storm'], 'signal', (v) => { st.mode = v; }), h('div', { style: { fontSize: '10px', letterSpacing: '.2em', opacity: .6 } }, 'LAYERS'), h('div.k-row', { style: { flexWrap: 'wrap' } }, chip('lines: on', true), chip('twinkle: on', true), chip('cursor attract', true), chip('respawn', false)), slider('Density', 20, 200, st.count, 5, (v) => { st.count = v; mk(); }))); const stats = h('div', { style: { position: 'absolute', left: '50%', bottom: '40px', transform: 'translateX(-50%)', width: '900px', display: 'grid', gridTemplateColumns: 'repeat(6,1fr)', gap: '8px' } }, stat('STARS', '90'), stat('MODE', 'signal'), stat('LINKS', 'on'), stat('TWINKLE', 'on'), stat('CURSOR', 'attract'), stat('FPS', '60'));
  root.append(card, stats); loop();
  window.__demoProof = async () => 'constellation live with lines/twinkle';
};
// ---------- hand-drawn physics
V['handdrawn-physics-sandbox'] = (root, T) => {
  theme(root, T, { bg: '#fdf6e3', fg: '#333', ac: '#333', dark: false }); root.style.fontFamily = "'Comic Sans MS','Chalkboard SE',cursive";
  const cv = h('canvas', { style: { width: '100%', height: '100%', cursor: 'crosshair' } }); const wrap = h('div', { style: { position: 'absolute', left: '110px', right: '170px', top: '20px', bottom: '20px', border: '2px solid #333', borderRadius: '4px', background: '#fffdf5' } }, cv);
  const segs = [[60, 120, 380, 180], [420, 260, 120, 330], [160, 420, 520, 470], [560, 500, 700, 440], [300, 560, 720, 600], [700, 120, 900, 90], [860, 250, 640, 300]]; let balls = []; let tool = 'ball', g0 = 0.25, st = null;
  const jit = (x, k) => x + Math.sin(x * 12.9898 + k) * 1.2;
  const loop = () => { fitCanvas(cv, wrap); const g = cv.g; g.clearRect(0, 0, cv.W, cv.H); g.strokeStyle = '#0001'; for (let x = 0; x < cv.W; x += 24) { g.beginPath(); g.moveTo(x, 0); g.lineTo(x, cv.H); g.stroke(); } g.lineCap = 'round'; for (const b of balls) { b.vy += g0; b.x += b.vx; b.y += b.vy; for (const [x1, y1, x2, y2] of segs) { const dx = x2 - x1, dy = y2 - y1; const L = dx * dx + dy * dy; const tt = clamp(((b.x - x1) * dx + (b.y - y1) * dy) / L, 0, 1); const px = x1 + tt * dx, py = y1 + tt * dy; const d = Math.hypot(b.x - px, b.y - py); if (d < b.r) { const nx = (b.x - px) / d, ny = (b.y - py) / d; b.x = px + nx * b.r; b.y = py + ny * b.r; const vn = b.vx * nx + b.vy * ny; if (vn < 0) { b.vx -= 1.5 * vn * nx; b.vy -= 1.5 * vn * ny; } b.vx *= 0.995; } } b.a += b.vx / b.r; } balls = balls.filter((b) => b.y < cv.H + 50); g.strokeStyle = '#333'; g.lineWidth = 2.5; for (const [x1, y1, x2, y2] of segs) { for (let k = 0; k < 2; k++) { g.beginPath(); g.moveTo(jit(x1, k), jit(y1, k + 1)); g.lineTo(jit(x2, k + 2), jit(y2, k + 3)); g.stroke(); } } for (const b of balls) { g.beginPath(); g.arc(b.x, b.y, b.r, 0, 7); g.fillStyle = b.c; g.fill(); g.stroke(); g.beginPath(); g.moveTo(b.x, b.y); g.lineTo(b.x + Math.cos(b.a) * b.r, b.y + Math.sin(b.a) * b.r); g.stroke(); } if (st && st.cur) { g.setLineDash([6, 6]); g.beginPath(); g.moveTo(st.x, st.y); g.lineTo(st.cur.x, st.cur.y); g.stroke(); g.setLineDash([]); } g.font = '22px Comic Sans MS'; g.fillStyle = '#333'; g.fillText('Welcome to Scribble Physics! ↓ draw ramps, drop balls', 60, 60); requestAnimationFrame(loop); };
  drag(cv, { start: (e) => { const p = localPos(e, cv); if (tool === 'ball') { balls.push({ x: p.x, y: p.y, vx: 0, vy: 0, r: 14 + Math.random() * 10, a: 0, c: pick(['#f6c', '#fc6', '#6cf', '#9e9', '#fff']) }); return false; } st = { x: p.x, y: p.y }; }, move: (e) => { if (st) st.cur = localPos(e, cv); }, end: () => { if (st?.cur) segs.push([st.x, st.y, st.cur.x, st.cur.y]); st = null; } });
  const tb = h('div', { style: { position: 'absolute', left: '14px', top: '20px', width: '80px', display: 'grid', gap: '14px', justifyItems: 'center', fontSize: '12px' } }, ...[['ball', '◯', 'Ball'], ['line', '╱', 'Ramp'], ['box', '▭', 'Box'], ['text', 'Aa', 'Text'], ['erase', '⌫', 'Erase']].map(([t, ic, l]) => h('div', { style: { textAlign: 'center', cursor: 'pointer' }, onclick: (e) => { tool = t === 'box' || t === 'text' ? 'line' : t; if (t === 'erase') segs.length = 0; tb.querySelectorAll('div').forEach((d) => (d.style.fontWeight = 400)); e.currentTarget.style.fontWeight = 700; } }, h('div', { style: { fontSize: '26px', border: '2px solid #333', borderRadius: '50%', width: '44px', height: '44px', display: 'grid', placeItems: 'center' } }, ic), l)));
  root.append(tb, wrap, h('div', { style: { position: 'absolute', right: '14px', top: '20px', width: '140px', border: '2px solid #333', padding: '10px', display: 'grid', gap: '8px', background: '#fff', fontSize: '13px' } }, h('b', {}, 'Gravity'), slider('', 0, 1, g0, 0.01, (v) => (g0 = v)), toggle('Sketchy lines', true, () => {}), toggle('Bounce', true, () => {}), btn('Drop 5 balls', () => { for (let i = 0; i < 5; i++) balls.push({ x: 100 + i * 60, y: 90, vx: 1, vy: 0, r: 16, a: 0, c: pick(['#f6c', '#fc6', '#6cf', '#9e9']) }); }), btn('Clear balls', () => (balls = []))));
  loop();
  window.__demoProof = async () => { for (let i = 0; i < 6; i++) balls.push({ x: 100 + i * 50, y: 80 + i * 30, vx: 1, vy: 0, r: 16, a: 0, c: ['#f6c', '#fc6', '#6cf', '#9e9', '#fff', '#fc6'][i] }); await sleep(900); return 'balls rolling on sketched ramps'; };
};
// ---------- mondrian
V['mondrian-partition-canvas'] = (root, T) => {
  theme(root, T, { bg: '#e8e8e8', fg: '#111', ac: '#d40920', dark: false });
  const PAL = ['#f2f2f2', '#d40920', '#1356a2', '#f7d842', '#111']; let rects = [{ x: 0, y: 0, w: 1, h: 1, c: 0 }]; let color = 0; let line = 8;
  const board = h('div', { style: { position: 'absolute', left: '20px', top: '20px', right: '20px', bottom: '60px', background: '#111', border: '2px solid #111' } });
  const draw = () => { board.replaceChildren(...rects.map((r, i) => h('div', { style: { position: 'absolute', left: `calc(${r.x * 100}% + ${line / 2}px)`, top: `calc(${r.y * 100}% + ${line / 2}px)`, width: `calc(${r.w * 100}% - ${line}px)`, height: `calc(${r.h * 100}% - ${line}px)`, background: PAL[r.c], cursor: 'crosshair' }, onclick: (e) => { const rr = e.currentTarget.getBoundingClientRect(); const fx = (e.clientX - rr.left) / rr.width, fy = (e.clientY - rr.top) / rr.height; if (e.altKey || color) { if (color) { r.c = color; draw(); return; } } if (e.shiftKey || rr.height > rr.width) { rects.splice(i, 1, { ...r, h: r.h * fy }, { ...r, y: r.y + r.h * fy, h: r.h * (1 - fy) }); } else rects.splice(i, 1, { ...r, w: r.w * fx }, { ...r, x: r.x + r.w * fx, w: r.w * (1 - fx) }); draw(); } }))); };
  const bar = h('div.k-row', { style: { position: 'absolute', left: '20px', right: '20px', bottom: '14px', fontSize: '11px', letterSpacing: '.08em', textTransform: 'uppercase' } }, h('b', {}, 'Composition with click · '), 'click = split · shift = horizontal · pick a colour to fill', h('span', { style: { flex: 1 } }), ...PAL.map((c, i) => h('span', { style: { width: '18px', height: '18px', background: c, border: i === 0 ? '2px solid #111' : '1px solid #111', cursor: 'pointer' }, onclick: (e) => { color = i; bar.querySelectorAll('span[style*="18px"]').forEach((x) => (x.style.border = '1px solid #111')); e.target.style.border = '2px solid #111'; } })), btn('Undo all', () => { rects = [{ x: 0, y: 0, w: 1, h: 1, c: 0 }]; draw(); }), btn('Random', () => { rects = [{ x: 0, y: 0, w: 1, h: 1, c: 0 }]; for (let k = 0; k < 9; k++) { const i = (Math.random() * rects.length) | 0; const r = rects[i]; const f = 0.3 + Math.random() * 0.4; if (r.w > r.h) rects.splice(i, 1, { ...r, w: r.w * f }, { ...r, x: r.x + r.w * f, w: r.w * (1 - f) }); else rects.splice(i, 1, { ...r, h: r.h * f }, { ...r, y: r.y + r.h * f, h: r.h * (1 - f) }); } rects.forEach((r) => (r.c = Math.random() < 0.25 ? 1 + ((Math.random() * 3) | 0) : 0)); draw(); }), btn('PNG', () => toast('mondrian.png')));
  root.append(board, bar); draw();
  window.__demoProof = async () => { rects = [{ x: 0, y: 0, w: 1, h: 1, c: 0 }]; draw(); return 'blank canvas awaiting click-to-split (initial state)'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['falling-sand-particle-sandbox'])(root, T); }
