import { h, s, css, drag, localPos, clamp, copy, toast, sleep, rng, hsl, pick, randHex, gesture } from '../lib.js';
import { theme, slider, seg, select, btn, panel, toggle, codebox } from '../kit.js';
const ser = (el) => new XMLSerializer().serializeToString(el);
const dl = (name, text) => { const a = h('a', { download: name, href: 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(text) }); a.click(); toast(`${name} downloaded`); };
function wavePath(w, hh, n, amp, seed, base) { const R = rng(seed); const pts = Array.from({ length: n + 1 }, (_, i) => [(i / n) * w, base + (R() - 0.5) * amp]); let d = `M0 ${hh}L0 ${pts[0][1]}`; for (let i = 0; i < n; i++) { const [x0, y0] = pts[i], [x1, y1] = pts[i + 1]; const mx = (x0 + x1) / 2; d += `C${mx} ${y0},${mx} ${y1},${x1} ${y1}`; } return d + `L${w} ${hh}Z`; }
function blobPath(n, contrast, seed, r = 180, cx = 250, cy = 250) { const R = rng(seed); const pts = Array.from({ length: n }, (_, i) => { const a = (i / n) * Math.PI * 2; const rr = r * (1 - contrast * 0.1 * R() * 4 + contrast * 0.05); return [cx + Math.cos(a) * rr, cy + Math.sin(a) * rr]; }); let d = ''; for (let i = 0; i < n; i++) { const p0 = pts[(i - 1 + n) % n], p1 = pts[i], p2 = pts[(i + 1) % n], p3 = pts[(i + 2) % n]; if (!i) d = `M${p1[0].toFixed(1)} ${p1[1].toFixed(1)}`; d += `C${(p1[0] + (p2[0] - p0[0]) / 6).toFixed(1)} ${(p1[1] + (p2[1] - p0[1]) / 6).toFixed(1)},${(p2[0] - (p3[0] - p1[0]) / 6).toFixed(1)} ${(p2[1] - (p3[1] - p1[1]) / 6).toFixed(1)},${p2[0].toFixed(1)} ${p2[1].toFixed(1)}`; } return d + 'Z'; }
const V = {};
V['shapedivider-preview-export'] = (root, T) => {
  theme(root, T, { bg: '#f4f7fb', fg: '#1d2939', panel: '#fff', ac: '#16a34a', dark: false });
  const SH = { Waves: (w, hh) => `M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z`, Tilt: () => 'M1200 120L0 16.48 0 0 1200 0 1200 120z', Triangle: () => 'M1200 0L0 0 598.97 114.72 1200 0z', Curve: () => 'M0,0V7.23C0,65.52,268.63,112.77,600,112.77S1200,65.52,1200,7.23V0Z', Arrow: () => 'M649.97 0L550.03 0 599.91 54.12 649.97 0z', Book: () => 'M602.45,3.86h0S572.9,116.24,281.94,120H923C632,116.24,602.45,3.86,602.45,3.86Z', Split: () => 'M0,0V3.6H580.08c11,0,19.92,5.09,19.92,13.2,0-8.14,8.88-13.2,19.92-13.2H1200V0Z' };
  const P = { shape: 'Waves', flip: false, invert: false, pos: 'bottom', height: 150, width: 100, color: '#16a34a' };
  const prev = h('div', { style: { position: 'relative', height: '460px', background: '#fff', borderRadius: '14px', overflow: 'hidden', boxShadow: '0 10px 40px #0001' } }, h('div', { style: { padding: '70px', textAlign: 'center' } }, h('h1', { style: { fontSize: '44px', margin: 0 } }, 'Section heading'), h('p', { style: { opacity: .6 } }, 'Your content above the divider')));
  const div = h('div', { style: { position: 'absolute', left: 0, width: '100%', lineHeight: 0 } }); prev.append(div);
  const code = h('pre.k-code', { style: { display: 'none' } });
  const draw = () => { const svg = s('svg', { viewBox: '0 0 1200 120', preserveAspectRatio: 'none', style: `width:${P.width}%;height:${P.height}px;display:block;transform:${P.flip ? 'scaleX(-1)' : ''} ${P.invert ? 'scaleY(-1)' : ''}` }, s('path', { d: SH[P.shape](), fill: P.color })); div.replaceChildren(svg); Object.assign(div.style, P.pos === 'bottom' ? { bottom: 0, top: '', transform: 'rotate(180deg)' } : { top: 0, bottom: '', transform: '' }); code.textContent = `<div class="custom-shape-divider-${P.pos}">\n  ${ser(svg)}\n</div>\n\n.custom-shape-divider-${P.pos} svg { height: ${P.height}px; width: calc(${P.width}% + 1.3px); }\n.custom-shape-divider-${P.pos} .shape-fill { fill: ${P.color}; }`; };
  const picker = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: '6px' } }, Object.keys(SH).map((k) => h('button', { onclick: () => { P.shape = k; draw(); }, style: { border: '1px solid #e4e7ec', background: '#fff', borderRadius: '8px', padding: '6px' } }, s('svg', { viewBox: '0 0 1200 120', preserveAspectRatio: 'none', style: 'width:100%;height:30px' }, s('path', { d: SH[k](), fill: '#16a34a' })), h('div', { style: { fontSize: '11px' } }, k))));
  root.append(h('div.k-row', { style: { height: '56px', padding: '0 30px', background: '#16a34a', color: '#fff' } }, h('b', { style: { fontSize: '18px' } }, 'Shape Divider-ish'), h('span', { style: { flex: 1 } }), 'Generate SVG section dividers'), h('div', { style: { display: 'grid', gridTemplateColumns: '300px 1fr', gap: '20px', padding: '20px 30px' } }, panel('Shape', picker, h('div.k-row', {}, toggle('Flip', false, (v) => { P.flip = v; draw(); }), toggle('Invert', false, (v) => { P.invert = v; draw(); })), seg([['top', 'Top'], ['bottom', 'Bottom']], 'bottom', (v) => { P.pos = v; draw(); }), slider('Height', 20, 400, P.height, 1, (v) => { P.height = v; draw(); }, (v) => v + 'px'), slider('Width', 100, 300, P.width, 1, (v) => { P.width = v; draw(); }, (v) => v + '%'), h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); } }), btn('Get Code', () => { code.style.display = code.style.display ? '' : 'none'; copy(code.textContent, 'Code copied'); }, 'pri')), h('div', {}, prev, code)));
  draw();
  window.__demoProof = async () => { P.shape = 'Curve'; P.flip = true; P.height = 180; draw(); code.style.display = ''; return 'Curve divider, flipped, height 180, code shown'; };
};
V['svg-wave-floating-control-bar'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#0099ff', dark: false });
  const P = { color: '#0099ff', op: 1, cx: 10, layers: 1, seed: 7, curve: 'smooth' };
  const svg = s('svg', { viewBox: '0 0 1440 320', preserveAspectRatio: 'none', style: 'position:absolute;left:0;bottom:0;width:100%;height:45%' });
  const draw = () => { svg.replaceChildren(...Array.from({ length: P.layers }, (_, i) => s('path', { d: P.curve === 'step' ? stepPath(i) : wavePath(1440, 320, P.cx, 140, P.seed + i * 13, 150 + i * 40), fill: P.color, 'fill-opacity': P.layers > 1 ? 0.3 + (i / P.layers) * 0.7 : P.op }))); };
  const stepPath = (i) => { const R = rng(P.seed + i); let d = 'M0 320'; for (let k = 0; k <= P.cx; k++) { const y = 100 + R() * 150; d += `V${y}H${(k + 1) * (1440 / P.cx)}`; } return d + 'V320Z'; };
  const bar = h('div.k-row', { style: { position: 'absolute', top: '180px', left: '50%', transform: 'translateX(-50%)', background: '#fff', padding: '10px 16px', borderRadius: '12px', boxShadow: '0 6px 24px #0002', gap: '16px', zIndex: 2 } }, seg([['smooth', '∿'], ['step', '⎍'], ['peak', '⋀']], 'smooth', (v) => { P.curve = v; draw(); }), h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); } }), h('div', { style: { width: '120px' } }, slider('Opacity', 0, 1, 1, 0.05, (v) => { P.op = v; draw(); })), h('div', { style: { width: '120px' } }, slider('Complexity', 3, 30, P.cx, 1, (v) => { P.cx = v; draw(); })), select([[1, '1 layer'], [2, '2 layers'], [3, '3 layers']], 1, (v) => { P.layers = +v; draw(); }), btn('🎲', () => { P.seed = Math.floor(Math.random() * 1e5); draw(); }), btn('⬇', () => dl('wave.svg', ser(svg)), 'pri'));
  root.append(h('div', { style: { background: '#0f1b2d', color: '#fff', textAlign: 'center', padding: '8px', fontSize: '13px' } }, 'Get Waves-ish · Make some waves!'), h('div', { style: { position: 'absolute', top: '90px', width: '100%', textAlign: 'center', font: '800 44px Inter Variable' } }, 'Make some waves!'), bar, svg);
  draw();
  window.__demoProof = async () => { P.seed = 42; P.cx = 12; P.layers = 2; draw(); return 'randomized 2-layer wave, complexity 12'; };
};
V['blobmaker-organic-svg-desk'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', ac: '#fa4d56', dark: false });
  const P = { n: 6, c: 0.5, color: '#ff0066', seed: 3 };
  const svg = s('svg', { viewBox: '0 0 500 500', width: 420, height: 420 });
  const draw = () => svg.replaceChildren(s('path', { d: blobPath(P.n, P.c, P.seed), fill: P.color }));
  root.append(h('div', { style: { background: '#fa4d56', color: '#fff', textAlign: 'center', padding: '6px', fontSize: '12px' } }, 'Make organic SVG shapes for your next design'), h('div.k-row', { style: { padding: '14px 40px' } }, h('b', { style: { background: '#ff6600', color: '#fff', borderRadius: '8px', padding: '4px 8px' } }, 'b'), h('span', {}, 'blobmaker-ish'), h('span', { style: { flex: 1 } }), 'Share ♥'), h('div', { style: { display: 'grid', placeItems: 'center', height: '520px' } }, svg),
    h('div.k-row', { style: { position: 'absolute', bottom: '40px', left: '50%', transform: 'translateX(-50%)', background: '#fff', borderRadius: '99px', padding: '12px 22px', boxShadow: '0 8px 30px #0002', gap: '20px' } }, h('input', { type: 'color', value: P.color, oninput: (e) => { P.color = e.target.value; draw(); }, style: { width: '34px', height: '34px', border: 0, borderRadius: '50%' } }), h('div', { style: { width: '140px' } }, slider('Complexity', 3, 12, P.n, 1, (v) => { P.n = v; draw(); })), h('div', { style: { width: '140px' } }, slider('Contrast', 0, 1, P.c, 0.05, (v) => { P.c = v; draw(); })), h('button', { style: { width: '48px', height: '48px', borderRadius: '50%', border: 0, background: '#fa4d56', color: '#fff', fontSize: '22px' }, onclick: () => { P.seed = Math.floor(Math.random() * 1e5); draw(); } }, '🎲'), btn('⬇ SVG', () => dl('blob.svg', ser(svg))), btn('</>', () => copy(ser(svg), 'SVG code copied'))));
  draw();
  window.__demoProof = async () => { P.seed = 99; P.n = 8; draw(); return 'dice re-roll, complexity 8'; };
};
V['svg-generator-studio'] = (root, T) => {
  theme(root, T, { bg: '#1b1b2f', fg: '#e6e6ff', panel: '#23233b', ac: '#fe5d9f', dark: true });
  const GENS = ['Layered Waves', 'Blob Scene', 'Stacked Waves', 'Low Poly Grid', 'Circle Scatter', 'Layered Peaks'];
  const P = { gen: 'Layered Waves', layers: 5, cx: 8, seed: 1, c1: '#fa7268', c2: '#c62368', bg: '#001220' };
  const svg = s('svg', { viewBox: '0 0 900 600', style: 'width:100%;height:100%;border-radius:6px' });
  const mix = (a, b, t) => { const A = a.match(/\w\w/g).map((x) => parseInt(x, 16)), B = b.match(/\w\w/g).map((x) => parseInt(x, 16)); return '#' + A.map((v, i) => Math.round(v + (B[i] - v) * t).toString(16).padStart(2, '0')).join(''); };
  const draw = () => { svg.replaceChildren(s('rect', { width: 900, height: 600, fill: P.bg })); const R = rng(P.seed);
    if (P.gen === 'Blob Scene') for (let i = 0; i < P.layers; i++) svg.append(s('path', { d: blobPath(P.cx, 0.6, P.seed + i, 90 + R() * 60, R() * 900, R() * 600), fill: mix(P.c1, P.c2, i / P.layers) }));
    else if (P.gen === 'Circle Scatter') for (let i = 0; i < P.layers * 8; i++) svg.append(s('circle', { cx: R() * 900, cy: R() * 600, r: 10 + R() * 60, fill: mix(P.c1, P.c2, R()) }));
    else if (P.gen === 'Low Poly Grid') { for (let y = 0; y < 6; y++) for (let x = 0; x < 9; x++) svg.append(s('path', { d: `M${x * 100} ${y * 100}l100 0l-${R() * 100} 100z`, fill: mix(P.c1, P.c2, (x + y) / 14 + R() * 0.1) }), s('path', { d: `M${x * 100 + 100} ${y * 100}l0 100l-100 0z`, fill: mix(P.c2, P.c1, (x + y) / 14) })); }
    else for (let i = 0; i < P.layers; i++) svg.append(s('path', { d: P.gen === 'Layered Peaks' ? `M0 600L0 ${300 + i * 50}` + Array.from({ length: P.cx }, (_, k) => `L${((k + 0.5) / P.cx) * 900} ${250 + i * 50 - R() * 120}L${((k + 1) / P.cx) * 900} ${300 + i * 50}`).join('') + 'L900 600Z' : wavePath(900, 600, P.cx, 80, P.seed + i * 7, 280 + i * (300 / P.layers)), fill: mix(P.c1, P.c2, i / (P.layers - 1 || 1)) })); };
  const list = h('div', { style: { display: 'grid', gap: '10px' } }, GENS.map((g) => h('button', { onclick: () => { P.gen = g; draw(); list.querySelectorAll('button').forEach((b) => (b.style.outline = b.textContent === g ? '2px solid #fe5d9f' : '')); }, style: { height: '92px', border: 0, borderRadius: '8px', color: '#fff', fontWeight: 700, background: `linear-gradient(160deg,${P.c1},${P.c2} 60%,#001220)`, outline: g === P.gen ? '2px solid #fe5d9f' : '' } }, g)));
  root.style.display = 'grid'; root.style.gridTemplateColumns = '180px 1fr 280px'; root.style.gap = '16px'; root.style.padding = '16px';
  root.append(h('div', { style: { overflow: 'auto' } }, h('b', { style: { color: '#fe5d9f', fontSize: '18px' } }, 'haikei-ish'), list), h('div', { style: { display: 'grid', placeItems: 'center' } }, h('div', { style: { width: '100%', aspectRatio: '3/2' } }, svg)), panel(P.gen, slider('Layers', 2, 10, P.layers, 1, (v) => { P.layers = v; draw(); }), slider('Complexity', 2, 20, P.cx, 1, (v) => { P.cx = v; draw(); }), h('div.k-row', {}, ['c1', 'c2', 'bg'].map((k) => h('input', { type: 'color', value: P[k], oninput: (e) => { P[k] = e.target.value; draw(); } }))), btn('🎲 Randomize', () => { P.seed = Math.floor(Math.random() * 1e5); draw(); }), seg(['SVG', 'PNG'], 'SVG', () => {}), btn('Download', () => dl('haikei.svg', ser(svg)), 'pri')));
  draw();
  window.__demoProof = async () => { P.seed = 11; P.layers = 6; draw(); return 'regenerated 6 layered waves'; };
};
V['fffuel-organic-leaf-svg'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fff', ac: '#d946ef', dark: false });
  const P = { hue: 300, sat: 70, light: 60, op: 0.8, blur: 0, density: 60, prob: 0.8, reg: 0.4, fill: 'solid', seed: 5 };
  const svg = s('svg', { viewBox: '0 0 800 600', style: 'width:100%;height:100%' });
  const leaf = 'M0 -20C12 -10 12 10 0 20C-12 10 -12 -10 0 -20Z';
  const draw = () => { const R = rng(P.seed); svg.replaceChildren(s('defs', {}, s('filter', { id: 'bl' }, s('feGaussianBlur', { stdDeviation: P.blur })), s('linearGradient', { id: 'lg', x1: 0, y1: 0, x2: 0, y2: 1 }, s('stop', { offset: 0, 'stop-color': hsl(P.hue, P.sat, P.light + 15) }), s('stop', { offset: 1, 'stop-color': hsl(P.hue + 30, P.sat, P.light - 15) }))), s('rect', { width: 800, height: 600, fill: '#fff' }));
    const g = s('g', { filter: P.blur ? 'url(#bl)' : null }); const n = Math.round(P.density / 5); for (let y = 0; y < n; y++) for (let x = 0; x < n * 1.3; x++) { if (R() > P.prob) continue; const jx = (R() - 0.5) * 60 * (1 - P.reg), jy = (R() - 0.5) * 60 * (1 - P.reg); g.append(s('path', { d: leaf, transform: `translate(${(x + 0.5) * (800 / (n * 1.3)) + jx} ${(y + 0.5) * (600 / n) + jy}) rotate(${R() * 360 * (1 - P.reg) + 30}) scale(${0.6 + R() * 0.6})`, fill: P.fill === 'gradient' ? 'url(#lg)' : P.fill === 'outline' ? 'none' : hsl(P.hue + (R() - 0.5) * 30, P.sat, P.light), stroke: P.fill === 'outline' ? hsl(P.hue, P.sat, P.light) : 'none', opacity: P.op })); } svg.append(g); };
  const ctl = panel(null, h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' } }, slider('Hue', 0, 360, P.hue, 1, (v) => { P.hue = v; draw(); }), slider('Saturation', 0, 100, P.sat, 1, (v) => { P.sat = v; draw(); }), slider('Lightness', 10, 90, P.light, 1, (v) => { P.light = v; draw(); }), slider('Opacity', 0.1, 1, P.op, 0.05, (v) => { P.op = v; draw(); }), slider('Blur', 0, 8, P.blur, 0.5, (v) => { P.blur = v; draw(); }), slider('Density', 20, 120, P.density, 1, (v) => { P.density = v; draw(); }), slider('Probability', 0.1, 1, P.prob, 0.05, (v) => { P.prob = v; draw(); }), slider('Regularity', 0, 1, P.reg, 0.05, (v) => { P.reg = v; draw(); })), seg(['solid', 'gradient', 'outline'], 'solid', (v) => { P.fill = v; draw(); }), h('div.k-row', {}, btn('🎲', () => { P.seed++; P.hue = Math.random() * 360; draw(); }), btn('Copy SVG', () => copy(ser(svg), 'SVG copied'), 'pri'), btn('Save SVG', () => dl('llleaves.svg', ser(svg)))));
  Object.assign(ctl.style, { position: 'absolute', right: '20px', bottom: '20px', width: '380px', boxShadow: '0 10px 40px #0002' });
  root.append(h('div', { style: { position: 'absolute', left: '20px', top: '10px', writingMode: 'vertical-rl', transform: 'rotate(180deg)', font: '800 44px Inter Variable', color: '#d946ef' } }, 'llleaves-ish'), h('div', { style: { position: 'absolute', left: '100px', right: '420px', top: '20px', bottom: '20px' } }, svg), ctl);
  draw();
  window.__demoProof = async () => { P.seed = 8; P.fill = 'gradient'; draw(); return 'gradient fill leaves re-seeded'; };
};
V['seamless-pattern-generator'] = (root, T) => {
  theme(root, T, { bg: '#f2e6c9', fg: '#2b2118', panel: '#fbf3e0', ac: '#e0633a', dark: false });
  const P = { motif: 'squiggle', size: 60, spacing: 20, rot: 0, fg: '#e0a93a', bg: '#1e2a4a', stroke: 6 };
  const M = { squiggle: 'M-20 0C-10 -15 0 15 10 0S20 -15 30 0', dot: 'M0 -8a8 8 0 1 0 0.1 0', cross: 'M-10 0H10M0 -10V10', zig: 'M-20 5L-10 -5L0 5L10 -5L20 5', ring: 'M0 -12a12 12 0 1 0 0.1 0' };
  const tile = h('div', { style: { width: '420px', height: '420px', border: '3px solid #2b2118', boxShadow: '6px 6px 0 #2b2118' } });
  const code = h('pre.k-code');
  const draw = () => { const t = P.size + P.spacing; const sv = `<svg xmlns='http://www.w3.org/2000/svg' width='${t}' height='${t}'><rect width='100%' height='100%' fill='${P.bg}'/><path d='${M[P.motif]}' transform='translate(${t / 2} ${t / 2}) rotate(${P.rot}) scale(${P.size / 40})' fill='${P.motif === 'dot' ? P.fg : 'none'}' stroke='${P.fg}' stroke-width='${P.stroke / (P.size / 40)}' stroke-linecap='round'/></svg>`; const url = `url("data:image/svg+xml,${encodeURIComponent(sv)}")`; tile.style.background = url; code.textContent = `background-color: ${P.bg};\nbackground-image: ${url.slice(0, 90)}…;`; };
  const win = (title, ...kids) => h('div', { style: { border: '3px solid #2b2118', background: '#fbf3e0', boxShadow: '5px 5px 0 #2b2118' } }, h('div', { style: { background: '#e0633a', color: '#fff', padding: '4px 8px', fontWeight: 800, borderBottom: '3px solid #2b2118', fontFamily: 'Courier New,monospace' } }, title), h('div', { style: { padding: '12px', display: 'grid', gap: '10px' } }, ...kids));
  root.style.fontFamily = 'Courier New,monospace';
  root.append(h('div', { style: { position: 'absolute', inset: 0, display: 'grid', gridTemplateColumns: '320px 1fr 320px', gap: '24px', padding: '24px' } }, h('div', { style: { display: 'grid', gap: '18px', alignContent: 'start' } }, win('MOTIF.EXE', h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: '4px' } }, Object.keys(M).map((k) => btn(k.slice(0, 4), () => { P.motif = k; draw(); }))), slider('Size', 20, 120, P.size, 1, (v) => { P.size = v; draw(); }), slider('Spacing', 0, 80, P.spacing, 1, (v) => { P.spacing = v; draw(); }), slider('Rotate', 0, 180, P.rot, 1, (v) => { P.rot = v; draw(); }), slider('Stroke', 1, 14, P.stroke, 1, (v) => { P.stroke = v; draw(); })), win('COLORS', h('div.k-row', {}, h('input', { type: 'color', value: P.fg, oninput: (e) => { P.fg = e.target.value; draw(); } }), h('input', { type: 'color', value: P.bg, oninput: (e) => { P.bg = e.target.value; draw(); } }), btn('🎲', () => { P.fg = randHex(); P.bg = randHex(); draw(); })))), h('div', { style: { display: 'grid', placeItems: 'center' } }, win('PATTERN PREVIEW — seamless', tile)), h('div', { style: { display: 'grid', gap: '18px', alignContent: 'start' } }, win('EXPORT', code, btn('COPY CSS', () => copy(code.textContent), 'pri'), btn('DOWNLOAD SVG', () => toast('tile.svg saved'))))));
  draw();
  window.__demoProof = async () => { P.motif = 'squiggle'; P.rot = 45; P.size = 50; draw(); return 'rotated squiggle tile 45°'; };
};
V['svg-path-command-studio'] = (root, T) => {
  theme(root, T, { bg: '#1d1f24', fg: '#ddd', panel: '#25282e', ac: '#60a5fa', dark: true });
  let cmds = [['M', 120, 380], ['L', 170, 330], ['L', 380, 120], ['L', 440, 100], ['L', 420, 160], ['L', 210, 370], ['L', 250, 410], ['L', 220, 430], ['L', 180, 400], ['L', 140, 440], ['L', 110, 430], ['Z']];
  const svg = s('svg', { style: 'width:100%;height:100%;background:#2a2d33' }); const ta = h('textarea', { spellcheck: false, style: { width: '100%', height: '90px', background: '#15171b', color: '#9fd3ff', border: '1px solid #333', fontFamily: 'monospace', padding: '6px' } });
  const list = h('div', { style: { display: 'grid', gap: '3px', fontFamily: 'monospace', fontSize: '12px', maxHeight: '420px', overflow: 'auto' } });
  const dstr = () => cmds.map((c) => c[0] + (c.length > 1 ? ' ' + c.slice(1).map((v) => Math.round(v)).join(' ') : '')).join(' ');
  const draw = () => { svg.replaceChildren(s('path', { d: dstr(), fill: '#ffffff22', stroke: '#fff', 'stroke-width': 2 })); cmds.forEach((c, i) => { if (c.length < 3) return; const k = s('circle', { cx: c[1], cy: c[2], r: 6, fill: '#60a5fa', stroke: '#fff', style: 'cursor:grab' }); drag(k, { move: (e) => { const p = localPos(e, svg); c[1] = p.x; c[2] = p.y; draw(); } }); svg.append(k); }); ta.value = dstr(); list.replaceChildren(...cmds.map((c, i) => h('div', { style: { display: 'flex', gap: '6px', background: '#2f333a', padding: '3px 6px', borderRadius: '4px' } }, h('b', { style: { color: '#60a5fa', width: '14px' } }, c[0]), ...c.slice(1).map((v) => h('span', {}, Math.round(v)))))); };
  ta.onchange = () => { const toks = ta.value.match(/[MLZ]|-?\d+\.?\d*/gi) || []; const out = []; let cur; for (const t of toks) { if (/[MLZ]/i.test(t)) { cur = [t.toUpperCase()]; out.push(cur); } else cur?.push(+t); } cmds = out; draw(); };
  root.style.display = 'grid'; root.style.gridTemplateColumns = '300px 1fr'; root.style.gap = '0';
  root.append(panel('Path', ta, h('div.k-row', {}, btn('Scale ×1.1', () => { cmds.forEach((c) => { if (c[1] != null) { c[1] *= 1.1; c[2] *= 1.1; } }); draw(); }), btn('Translate →', () => { cmds.forEach((c) => { if (c[1] != null) c[1] += 20; }); draw(); })), h('div.k-row', {}, btn('To absolute', () => {}), btn('To relative', () => toast('Converted (demo)')), btn('Optimize', () => toast('Optimized'))), h('div.k-h', {}, 'Commands'), list), h('div', { style: { position: 'relative' } }, svg));
  draw();
  window.__demoProof = async () => { cmds[3][1] = 470; cmds[3][2] = 70; draw(); return 'dragged tip point → d-string updated'; };
};
V['svg-optimize-toggle-studio'] = (root, T) => {
  theme(root, T, { bg: '#e8e8e8', fg: '#222', panel: '#303030', ac: '#00bcd4', dark: false });
  const PL = ['Remove doctype', 'Remove XML instructions', 'Remove comments', 'Remove metadata', 'Remove editor data', 'Cleanup IDs', 'Collapse groups', 'Round/rewrite numbers', 'Merge paths', 'Minify colors', 'Remove hidden elements', 'Prefer viewBox to width/height', 'Sort attrs'];
  const on = new Set(PL.filter((_, i) => i % 4 !== 3)); let prec = 3;
  const art = s('svg', { viewBox: '0 0 200 200', width: 380, height: 380 }, s('circle', { cx: 100, cy: 100, r: 80, fill: '#00bcd4' }), s('path', { d: 'M60 120q40-80 80 0', stroke: '#fff', 'stroke-width': 12, fill: 'none', 'stroke-linecap': 'round' }), s('circle', { cx: 75, cy: 80, r: 10, fill: '#fff' }), s('circle', { cx: 125, cy: 80, r: 10, fill: '#fff' }));
  const stat = h('div', { style: { position: 'absolute', right: '20px', bottom: '20px', background: '#fff', padding: '12px 18px', borderRadius: '6px', boxShadow: '0 4px 20px #0002', fontFamily: 'monospace' } });
  const draw = () => { const orig = 4820; const pct = 0.08 * on.size + (6 - prec) * 0.02; const sz = Math.round(orig * (1 - pct)); stat.replaceChildren(h('div', {}, `${(orig / 1024).toFixed(2)}k → `, h('b', { style: { color: '#00897b' } }, `${(sz / 1024).toFixed(2)}k`)), h('div', { style: { fontSize: '22px', fontWeight: 800 } }, `−${Math.round(pct * 100)}%`)); drawer.querySelectorAll('input[type=checkbox]').forEach((c) => (c.checked = on.has(c.dataset.n))); };
  const drawer = h('div', { style: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '320px', background: '#303030', color: '#eee', padding: '16px', overflow: 'auto', display: 'grid', gap: '6px', alignContent: 'start' } }, h('b', {}, 'Global settings'), slider('Precision', 0, 8, prec, 1, (v) => { prec = v; draw(); }), h('b', { style: { marginTop: '10px' } }, 'Features'), ...PL.map((n) => h('label.k-row', { style: { fontSize: '13px', cursor: 'pointer' } }, h('input', { type: 'checkbox', 'data-n': n, onchange: (e) => { e.target.checked ? on.add(n) : on.delete(n); draw(); } }), n)));
  const menu = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: '220px', background: '#fff', boxShadow: '2px 0 10px #0002', padding: '10px 0' } }, h('div', { style: { background: '#00bcd4', color: '#fff', padding: '14px' } }, h('b', {}, 'SVGOMG-ish'), h('div', { style: { fontSize: '11px' } }, 'Powered by SVGO')), ...['📂 Open SVG', '📋 Paste markup', '🖼 Demo', '📄 Contribute'].map((x) => h('div', { style: { padding: '12px 16px' } }, x)));
  root.append(h('div', { style: { position: 'absolute', left: '220px', right: '320px', top: 0, bottom: 0, display: 'grid', placeItems: 'center', background: 'repeating-conic-gradient(#ddd 0 25%,#f5f5f5 0 50%) 0 0/20px 20px' } }, art), menu, drawer, h('div.k-row', { style: { position: 'absolute', right: '340px', top: '14px' } }, seg(['Image', 'Markup'], 'Image', () => {}), btn('⬇ Download', () => dl('optimized.svg', ser(art)), 'pri')), stat);
  stat.style.right = '340px'; draw();
  window.__demoProof = async () => { on.add('Merge paths'); on.add('Sort attrs'); prec = 1; draw(); return 'toggled plugins, precision 1 → size delta'; };
};
V['maskable-pwa-icon-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#fff', ac: '#4285f4', dark: false });
  const MASK = { Circle: '50%', Square: '0', Rounded: '22%', Squircle: '34%', Drop: '50% 50% 0 50%', Cylinder: '50% / 20%' }; let mask = 'Circle', pad = 10, bg = '#4285f4', showSafe = true;
  const icon = h('div', { style: { position: 'relative', width: '320px', height: '320px', overflow: 'hidden', margin: '0 auto', transition: '.2s' } });
  const safe = h('div', { style: { position: 'absolute', inset: '10%', borderRadius: '50%', border: '2px dashed #fff', pointerEvents: 'none' } });
  const draw = () => { icon.style.borderRadius = MASK[mask]; icon.style.background = bg; icon.replaceChildren(h('div', { style: { position: 'absolute', inset: pad + '%', display: 'grid', placeItems: 'center', fontSize: '120px' } }, '⚡'), showSafe ? safe : ''); layerList.replaceChildren(h('div.k-row', { style: { padding: '8px', background: '#e8f0fe', borderRadius: '6px' } }, h('span.k-sw', { style: { background: bg, borderRadius: '4px' } }), 'Background'), h('div.k-row', { style: { padding: '8px', border: '1px solid #eee', borderRadius: '6px' } }, '⚡', 'Emoji layer', h('span', { style: { flex: 1 } }), `pad ${pad}%`)); };
  const layerList = h('div', { style: { display: 'grid', gap: '6px' } });
  root.style.display = 'grid'; root.style.gridTemplateColumns = '1fr 300px';
  root.append(h('div', { style: { padding: '30px' } }, h('div.k-row', {}, h('b', { style: { fontSize: '20px' } }, '◐ Maskable-ish'), h('span', { style: { flex: 1 } }), seg(['Viewer', 'Editor'], 'Editor', () => {})), h('div', { style: { margin: '40px 0' } }, icon), h('div.k-row', { style: { justifyContent: 'center', flexWrap: 'wrap' } }, Object.keys(MASK).map((m) => h('label.k-row', { style: { cursor: 'pointer' } }, h('input', { type: 'radio', name: 'm', checked: m === mask, onchange: () => { mask = m; draw(); } }), m))), h('div', { style: { textAlign: 'center', marginTop: '14px' } }, toggle('Show safe area (minimum 80% circle)', true, (v) => { showSafe = v; draw(); }))),
    panel('Layers', btn('+ Add layer', () => toast('Layer added'), 'pri'), layerList, slider('Padding', 0, 40, pad, 1, (v) => { pad = v; draw(); }, (v) => v + '%'), h('input', { type: 'color', value: bg, oninput: (e) => { bg = e.target.value; draw(); } }), btn('Export icon (512/192/48)', () => toast('icon-512.png exported (demo)'))));
  draw();
  window.__demoProof = async () => { mask = 'Squircle'; pad = 18; draw(); return 'squircle mask + safe-zone overlay, padding 18%'; };
};
V['styled-qr-param-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#222', panel: '#f4f4f4', ac: '#9d2f84', dark: false });
  const P = { data: 'https://qr-code-styling.com', dots: 'rounded', corners: 'extra-rounded', c1: '#4267b2', c2: '#9d2f84', grad: true, logo: true, size: 300 };
  const N = 29; const qr = s('svg', { viewBox: `0 0 ${N} ${N}`, width: 300, height: 300 });
  const draw = () => { let hs = 0; for (const ch of P.data) hs = (hs * 31 + ch.charCodeAt(0)) >>> 0; const R = rng(hs || 1); qr.replaceChildren(s('defs', {}, s('linearGradient', { id: 'qg', x1: 0, y1: 0, x2: 1, y2: 1 }, s('stop', { offset: 0, 'stop-color': P.c1 }), s('stop', { offset: 1, 'stop-color': P.grad ? P.c2 : P.c1 }))));
    const finder = (x, y) => qr.append(s('rect', { x: x + 0.5, y: y + 0.5, width: 6, height: 6, rx: P.corners === 'square' ? 0 : P.corners === 'dot' ? 3 : 1.6, fill: 'none', stroke: 'url(#qg)', 'stroke-width': 1 }), s('rect', { x: x + 2, y: y + 2, width: 3, height: 3, rx: P.corners === 'square' ? 0 : 1.5, fill: 'url(#qg)' }));
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const inF = (x < 8 && y < 8) || (x > N - 9 && y < 8) || (x < 8 && y > N - 9); const inLogo = P.logo && Math.abs(x - N / 2) < 4 && Math.abs(y - N / 2) < 4; if (inF || inLogo || R() < 0.5) continue; qr.append(P.dots === 'dots' ? s('circle', { cx: x + 0.5, cy: y + 0.5, r: 0.45, fill: 'url(#qg)' }) : s('rect', { x: x + 0.05, y: y + 0.05, width: 0.9, height: 0.9, rx: P.dots === 'rounded' ? 0.35 : P.dots === 'classy' ? 0.15 : 0, fill: 'url(#qg)' })); }
    finder(0, 0); finder(N - 7, 0); finder(0, N - 7); if (P.logo) qr.append(s('text', { x: N / 2, y: N / 2 + 1.3, 'text-anchor': 'middle', 'font-size': 4, 'font-weight': 900, fill: P.c2 }, 'QR')); };
  const acc = (t, ...k) => h('details', { open: t === 'Main Options', style: { background: '#fff', borderRadius: '4px', padding: '8px 10px' } }, h('summary', { style: { fontWeight: 700, cursor: 'pointer' } }, t), h('div', { style: { display: 'grid', gap: '8px', marginTop: '8px' } }, ...k));
  root.append(h('div', { style: { background: 'linear-gradient(90deg,#1e1e1e,#6d1d59 60%,#c63b8f)', color: '#fff', padding: '26px 60px' } }, h('div', { style: { fontSize: '30px', fontWeight: 800 } }, 'QR Code Styling-ish'), h('div', { style: { opacity: .8 } }, 'An open source JS library · For generating styled QR codes')),
    h('div', { style: { display: 'grid', gridTemplateColumns: '1fr 360px', gap: '30px', padding: '24px 60px' } }, h('div', { style: { display: 'grid', gap: '8px', background: '#f4f4f4', padding: '12px', borderRadius: '6px', alignContent: 'start' } }, acc('Main Options', h('input', { value: P.data, oninput: (e) => { P.data = e.target.value; draw(); }, style: { padding: '8px' } }), slider('Width', 100, 500, 300, 10, () => {})), acc('Dots Options', select(['rounded', 'dots', 'classy', 'square'], P.dots, (v) => { P.dots = v; draw(); }), h('div.k-row', {}, h('input', { type: 'color', value: P.c1, oninput: (e) => { P.c1 = e.target.value; draw(); } }), toggle('Gradient', true, (v) => { P.grad = v; draw(); }), h('input', { type: 'color', value: P.c2, oninput: (e) => { P.c2 = e.target.value; draw(); } }))), acc('Corners Square Options', select(['extra-rounded', 'square', 'dot'], P.corners, (v) => { P.corners = v; draw(); })), acc('Image Options', toggle('Center logo', true, (v) => { P.logo = v; draw(); })), acc('QR Options', select(['Error correction: Q', 'H', 'M', 'L'], 'Q', () => {}))), h('div', { style: { textAlign: 'center' } }, qr, h('div.k-row', { style: { justifyContent: 'center' } }, select(['PNG', 'SVG', 'JPEG', 'WEBP'], 'PNG', () => {}), btn('Download', () => dl('qr.svg', ser(qr)), 'pri')), h('div', { style: { fontSize: '11px', opacity: .5, marginTop: '8px' } }, 'Styled preview (demo encoder)'))));
  draw();
  window.__demoProof = async () => { P.dots = 'dots'; P.data = 'https://ux-gallery.example'; draw(); return 'dot style + data change → QR re-rendered'; };
};
function avatarSVG(o) {
  const skin = o.skin, g = s('svg', { viewBox: '0 0 200 200', width: o.size || 240, height: o.size || 240 });
  g.append(s('circle', { cx: 100, cy: 100, r: 96, fill: o.bg }));
  g.append(s('path', { d: 'M40 200c0-40 28-60 60-60s60 20 60 60z', fill: o.shirt }));
  g.append(s('rect', { x: 88, y: 120, width: 24, height: 26, fill: skin }), s('ellipse', { cx: 100, cy: 92, rx: 38, ry: 44, fill: skin }));
  const HAIR = { short: 'M60 85c0-35 20-50 40-50s42 12 42 50c-6-18-20-26-42-26s-34 8-40 26z', long: 'M56 90c0-40 22-56 44-56s44 16 44 56v60h-14v-60c-6-18-20-26-30-26s-24 8-30 26v60H56z', bun: 'M62 80c0-30 18-44 38-44s38 14 38 44c-8-14-20-22-38-22s-30 8-38 22zM88 22a14 14 0 1 0 24 0a14 14 0 1 0-24 0', none: '' };
  if (HAIR[o.hair]) g.append(s('path', { d: HAIR[o.hair], fill: o.hairColor }));
  const EYES = { default: [s('circle', { cx: 86, cy: 92, r: 4, fill: '#222' }), s('circle', { cx: 114, cy: 92, r: 4, fill: '#222' })], happy: [s('path', { d: 'M80 94q6-7 12 0M108 94q6-7 12 0', stroke: '#222', 'stroke-width': 3, fill: 'none' })], wink: [s('circle', { cx: 86, cy: 92, r: 4, fill: '#222' }), s('path', { d: 'M108 93h12', stroke: '#222', 'stroke-width': 3 })] };
  g.append(...(EYES[o.eyes] || EYES.default));
  const MOUTH = { smile: 'M86 110q14 12 28 0', open: 'M88 108q12 16 24 0z', serious: 'M88 112h24' }; g.append(s('path', { d: MOUTH[o.mouth] || MOUTH.smile, stroke: '#7a2b2b', 'stroke-width': 3, fill: o.mouth === 'open' ? '#7a2b2b' : 'none', 'stroke-linecap': 'round' }));
  if (o.glasses) g.append(s('path', { d: 'M74 92a12 10 0 1 0 24 0a12 10 0 1 0-24 0M102 92a12 10 0 1 0 24 0a12 10 0 1 0-24 0M98 92h4', stroke: '#222', 'stroke-width': 2.5, fill: '#ffffff33' }));
  return g;
}
V['personas-svg-avatar-composer'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#111', panel: '#fff', ac: '#5a4bff', dark: false });
  const o = { skin: '#f2c7a5', hair: 'long', hairColor: '#6b3e26', eyes: 'happy', mouth: 'smile', bg: '#ffd9c7', shirt: '#5a4bff', glasses: false, size: 220 };
  const q = new URLSearchParams(location.search); for (const k of Object.keys(o)) if (q.get(k)) o[k] = q.get(k);
  const card = h('div', { style: { width: '460px', margin: '0 auto', borderRadius: '24px', boxShadow: '0 20px 60px #0002', padding: '26px', background: '#fff', textAlign: 'center' } });
  const CATS = { skin: ['#f2c7a5', '#e0a878', '#b67b52', '#8d5a3b', '#5c3a23'], hairColor: ['#2b1b10', '#6b3e26', '#c98a3a', '#e8d27a', '#b33a3a', '#8a8fa0'], bg: ['#ffd9c7', '#c7e6ff', '#d9f7c7', '#f1d9ff', '#fff3b8', '#e5e5e5'], shirt: ['#5a4bff', '#ff5a7a', '#1bb57a', '#222', '#ffb020'] };
  const draw = () => { history.replaceState(null, '', '?' + new URLSearchParams(o).toString()); card.replaceChildren(avatarSVG(o), h('div', { style: { fontWeight: 700, margin: '10px 0' } }, 'Randomize ↻'), h('div.k-row', { style: { justifyContent: 'center', gap: '10px', flexWrap: 'wrap' } }, ...['hair', 'eyes', 'mouth'].map((k) => select({ hair: ['long', 'short', 'bun', 'none'], eyes: ['default', 'happy', 'wink'], mouth: ['smile', 'open', 'serious'] }[k], o[k], (v) => { o[k] = v; draw(); }))), ...Object.entries(CATS).map(([k, cs]) => h('div.k-row', { style: { justifyContent: 'center', margin: '8px 0' } }, h('span', { style: { width: '80px', fontSize: '12px', textAlign: 'right', opacity: .6 } }, k), ...cs.map((c) => h('span.k-sw', { class: o[k] === c ? 'k-sw on' : 'k-sw', style: { background: c, width: '22px', height: '22px' }, onclick: () => { o[k] = c; draw(); } })))), h('div.k-row', { style: { justifyContent: 'center', marginTop: '10px' } }, btn('PNG', () => toast('avatar.png saved')), btn('SVG', () => copy(ser(card.querySelector('svg')), 'SVG copied'), 'pri'))); };
  root.append(h('div', { style: { position: 'absolute', left: '60px', top: '120px', width: '320px' } }, h('div', { style: { fontSize: '14px', color: '#5a4bff', fontWeight: 700 } }, '◆ draftbit-ish'), h('div', { style: { font: '400 72px/1 Inter Variable', margin: '14px 0' } }, 'Personas'), h('div', { style: { opacity: .6 } }, 'A playful avatar generator for the modern age.')), h('div', { style: { position: 'absolute', left: '380px', right: '40px', top: '50px' } }, card));
  draw();
  window.__demoProof = async () => { o.hair = 'bun'; o.glasses = true; o.bg = '#c7e6ff'; draw(); return 'hair→bun, glasses, bg chip; URL synced'; };
};
V['avatar-part-composer'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#333', panel: '#fff', ac: '#6a39ca', dark: false });
  const o = { skin: '#edb98a', hair: 'long', hairColor: '#4a312c', eyes: 'default', mouth: 'smile', bg: '#65c9ff', shirt: '#3c4f5c', glasses: false, size: 240 };
  const prev = h('div', { style: { textAlign: 'center', margin: '20px 0' } });
  const OPTS = { 'Avatar Style': ['Circle', 'Transparent'], Top: ['long', 'short', 'bun', 'none'], '↳ Hair Color': ['#4a312c', '#2c1b18', '#b58143', '#d6b370', '#c93305'], Accessories: ['Blank', 'Glasses'], 'Eyes': ['default', 'happy', 'wink'], 'Mouth': ['smile', 'open', 'serious'], 'Skin': ['#edb98a', '#fd9841', '#d08b5b', '#ae5d29', '#614335'], 'Clothes color': ['#3c4f5c', '#65c9ff', '#ff5c5c', '#929598'] };
  const map = { Top: 'hair', '↳ Hair Color': 'hairColor', Eyes: 'eyes', Mouth: 'mouth', Skin: 'skin', 'Clothes color': 'shirt' };
  const form = h('div', { style: { display: 'grid', gridTemplateColumns: '160px 1fr', gap: '10px 16px', maxWidth: '620px', margin: '0 auto', alignItems: 'center' } });
  const draw = () => { prev.replaceChildren(avatarSVG(o)); form.replaceChildren(...Object.entries(OPTS).flatMap(([k, vs]) => [h('label', { style: { textAlign: 'right', fontSize: '14px' } }, k), select(vs, map[k] ? o[map[k]] : k === 'Accessories' ? (o.glasses ? 'Glasses' : 'Blank') : vs[0], (v) => { if (map[k]) o[map[k]] = v; if (k === 'Accessories') o.glasses = v === 'Glasses'; if (k === 'Avatar Style') o.bg = v === 'Circle' ? '#65c9ff' : 'transparent'; draw(); })])); };
  root.style.overflow = 'auto';
  root.append(h('div', { style: { maxWidth: '760px', margin: '0 auto', padding: '30px' } }, h('div.k-row', {}, h('b', { style: { color: '#6a39ca', fontSize: '26px' } }, 'avataaars generator-ish'), h('span', { style: { flex: 1 } }), btn('🎲 Random', () => { o.hair = pick(['long', 'short', 'bun']); o.eyes = pick(['default', 'happy', 'wink']); o.mouth = pick(['smile', 'open']); o.skin = pick(OPTS.Skin); o.hairColor = pick(OPTS['↳ Hair Color']); draw(); }, 'pri')), prev, form, h('div.k-row', { style: { justifyContent: 'center', marginTop: '20px' } }, btn('⬇ Download PNG', () => toast('avataaar.png')), btn('⬇ Download SVG', () => copy(ser(prev.firstChild), 'SVG copied')), btn('</> Show React', () => copy(`<Avatar topType='${o.hair}' eyeType='${o.eyes}' mouthType='${o.mouth}' />`)))));
  draw();
  window.__demoProof = async () => { o.glasses = true; o.eyes = 'happy'; draw(); return 'accessory + eyes changed → live SVG'; };
};
V['social-meta-preview-studio'] = (root, T) => {
  theme(root, T, { bg: '#fff', fg: '#1d2129', panel: '#fff', ac: '#2d70f6', dark: false });
  const M = { title: 'Meta Tags — Preview, Edit and Generate', desc: 'With Meta Tags you can edit and experiment with your content then preview how your webpage will look on Google, Facebook, Twitter and more!', url: 'https://metatags.io', img: 'linear-gradient(135deg,#2d70f6,#6aa3ff)' };
  const pv = h('div', { style: { display: 'grid', gap: '22px' } }); const code = h('pre.k-code');
  const host = () => new URL(M.url).host;
  const draw = () => { pv.replaceChildren(h('div', {}, h('div.k-h', {}, 'Google'), h('div', { style: { color: '#1a0dab', fontSize: '19px' } }, M.title), h('div', { style: { color: '#006621', fontSize: '13px' } }, M.url), h('div', { style: { fontSize: '13px', color: '#545454' } }, M.desc.slice(0, 150))), h('div', {}, h('div.k-h', {}, 'Facebook'), h('div', { style: { border: '1px solid #dadde1', maxWidth: '520px' } }, h('div', { style: { height: '250px', background: M.img, display: 'grid', placeItems: 'center', color: '#fff', fontSize: '30px', fontWeight: 800 } }, '◧ Meta Tags'), h('div', { style: { background: '#f2f3f5', padding: '10px 12px' } }, h('div', { style: { fontSize: '12px', color: '#606770', textTransform: 'uppercase' } }, host()), h('div', { style: { fontWeight: 700 } }, M.title), h('div', { style: { fontSize: '13px', color: '#606770' } }, M.desc.slice(0, 90))))), h('div', {}, h('div.k-h', {}, 'Twitter / X'), h('div', { style: { border: '1px solid #e1e8ed', borderRadius: '14px', overflow: 'hidden', maxWidth: '520px' } }, h('div', { style: { height: '180px', background: M.img } }), h('div', { style: { padding: '10px' } }, h('b', {}, M.title), h('div', { style: { color: '#8899a6', fontSize: '13px' } }, host())))));
    code.textContent = `<title>${M.title}</title>\n<meta name="description" content="${M.desc}" />\n<meta property="og:type" content="website" />\n<meta property="og:url" content="${M.url}" />\n<meta property="og:title" content="${M.title}" />\n<meta property="og:image" content="${M.url}/og.png" />\n<meta property="twitter:card" content="summary_large_image" />`; };
  const f = (k, area) => h(area ? 'textarea' : 'input', { value: M[k], oninput: (e) => { M[k] = e.target.value; try { draw(); } catch {} }, style: { width: '100%', padding: '8px', border: '1px solid #dde', borderRadius: '6px', minHeight: area ? '80px' : '' } });
  const ta = f('desc', true); ta.value = M.desc;
  root.append(h('div.k-row', { style: { height: '54px', padding: '0 30px', borderBottom: '1px solid #eee' } }, h('b', { style: { color: '#2d70f6' } }, '◧ Meta Tags-ish'), h('span', { style: { flex: 1 } }), 'Meta Tags Toolkit'), h('div', { style: { position: 'absolute', inset: '54px 0 0 0', display: 'grid', gridTemplateColumns: '360px 1fr', gap: '30px', padding: '20px 30px', overflow: 'auto' } }, h('div', { style: { display: 'grid', gap: '10px', alignContent: 'start' } }, h('div.k-h', {}, 'Metadata'), f('url'), h('div', { style: { height: '140px', borderRadius: '8px', background: M.img } }), f('title'), ta, btn('Copy meta HTML', () => copy(code.textContent, 'Meta tags copied'), 'pri'), code), h('div', {}, h('b', {}, 'Preview'), pv)));
  draw();
  window.__demoProof = async () => { M.title = 'UX Technique Gallery — 217 interactive clones'; draw(); return 'title edited → all previews + meta HTML updated'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['blobmaker-organic-svg-desk'])(root, T); }
