import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { h, drag, clamp, toast, sleep, noise2 } from '../lib.js';
import { theme, slider, seg, select, btn, toggle } from '../kit.js';
const V = {};
function stage(el, { bg = null, ortho = false, alpha = false } = {}) {
  const r = new THREE.WebGLRenderer({ antialias: true, alpha, preserveDrawingBuffer: true }); r.setPixelRatio(Math.min(2, devicePixelRatio)); el.append(r.domElement); Object.assign(r.domElement.style, { position: 'absolute', inset: 0, width: '100%', height: '100%', display: 'block' });
  const scene = new THREE.Scene(); if (bg) scene.background = new THREE.Color(bg);
  const cam = ortho ? new THREE.OrthographicCamera(-1, 1, 1, -1, 0.1, 200) : new THREE.PerspectiveCamera(45, 1, 0.1, 500);
  const fit = () => { const w = el.clientWidth || 800, hh = el.clientHeight || 600; r.setSize(w, hh, false); if (ortho) { const a = w / hh, z = cam.userData.zoom || 8; Object.assign(cam, { left: -z * a, right: z * a, top: z, bottom: -z }); } else cam.aspect = w / hh; cam.updateProjectionMatrix(); };
  fit(); new ResizeObserver(fit).observe(el); const fns = []; const loop = (t) => { fns.forEach((f) => f(t / 1000)); r.render(scene, cam); requestAnimationFrame(loop); }; requestAnimationFrame(loop);
  return { r, scene, cam, fit, on: (f) => fns.push(f) };
}
const lights = (scene, k = 1) => { scene.add(new THREE.HemisphereLight(0xffffff, 0x444466, 0.9 * k)); const d = new THREE.DirectionalLight(0xffffff, 1.6 * k); d.position.set(5, 10, 7); d.castShadow = true; d.shadow.mapSize.set(1024, 1024); scene.add(d); return d; };
V['3d-blob-param-mixer'] = (root, T) => {
  theme(root, T, { bg: '#40686a', fg: '#e8f2f0', ac: '#fff', dark: true });
  const S = stage(root, { bg: '#40686a' }); S.cam.position.set(0, 0, 9); lights(S.scene);
  const P = { speed: 0.4, spikes: 1.2, amp: 0.35, hue: 250 }; const geo = new THREE.IcosahedronGeometry(1, 48); const base = geo.attributes.position.array.slice(); const nz = noise2(3);
  const mat = new THREE.MeshPhysicalMaterial({ color: 0x5b4bd6, roughness: 0.15, metalness: 0.1, clearcoat: 1, iridescence: 1, iridescenceIOR: 1.6 }); const m = new THREE.Mesh(geo, mat); S.scene.add(m);
  S.on((t) => { const a = geo.attributes.position.array; for (let i = 0; i < a.length; i += 3) { const x = base[i], y = base[i + 1], z = base[i + 2]; const n = nz(x * P.spikes + t * P.speed, y * P.spikes + z * P.spikes - t * P.speed); const k = 1 + (n - 0.5) * 2 * P.amp; a[i] = x * k; a[i + 1] = y * k; a[i + 2] = z * k; } geo.attributes.position.needsUpdate = true; geo.computeVertexNormals(); m.rotation.y = t * 0.2; mat.color.setHSL(P.hue / 360, 0.6, 0.5); });
  const top = h('div.k-row', { style: { position: 'absolute', top: '14px', left: '20px', right: '20px', fontSize: '12px', letterSpacing: '.05em', zIndex: 2 } }, h('span', {}, 'Blobmixer-ish'), h('span', { style: { flex: 1, textAlign: 'center', cursor: 'pointer' }, onclick: () => { P.speed = Math.random(); P.spikes = 0.5 + Math.random() * 3; P.amp = 0.1 + Math.random() * 0.6; P.hue = Math.random() * 360; } }, 'Shuffle ✦'), h('span', { style: { cursor: 'pointer' }, onclick: () => (panel.style.display = panel.style.display === 'none' ? 'grid' : 'none') }, 'Tweak'));
  const panel = h('div.k-panel', { style: { position: 'absolute', right: '20px', top: '50px', width: '240px', zIndex: 2, background: '#0003', padding: '12px', borderRadius: '10px', display: 'none', gap: '6px' } }, slider('Speed', 0, 2, P.speed, 0.01, (v) => (P.speed = v)), slider('Spikes', 0.2, 5, P.spikes, 0.01, (v) => (P.spikes = v)), slider('Amplitude', 0, 1, P.amp, 0.01, (v) => (P.amp = v)), slider('Hue', 0, 360, P.hue, 1, (v) => (P.hue = v)));
  const joy = h('div', { style: { position: 'absolute', left: '50%', bottom: '70px', width: '110px', height: '110px', marginLeft: '-55px', borderRadius: '50%', border: '1px solid #ffffff55', display: 'grid', placeItems: 'center', zIndex: 2, cursor: 'grab' } }, h('div', { style: { width: '26px', height: '26px', border: '1px solid #fff9', transform: 'rotate(45deg)' } }));
  drag(joy, { move: (e) => { P.spikes = clamp(P.spikes + e.movementX * 0.01, 0.2, 5); P.amp = clamp(P.amp - e.movementY * 0.004, 0, 1); } });
  root.append(top, panel, joy, h('div', { style: { position: 'absolute', left: '20px', bottom: '16px', fontSize: '11px', opacity: .6, zIndex: 2 } }, 'drag the dial to mix · Tweak for params'));
  S.cam.position.z = 17;
  window.__demoProof = async () => { P.amp = 0.5; await sleep(200); return 'blob displaced by noise params'; };
};
V['3d-drivable-portfolio-world'] = (root, T) => {
  theme(root, T, { bg: '#f09b54', fg: '#fff', ac: '#fff', dark: true });
  const S = stage(root, { bg: '#f5a35f' }); S.r.shadowMap.enabled = true; const d = lights(S.scene, 0.9); d.shadow.camera.left = d.shadow.camera.bottom = -30; d.shadow.camera.right = d.shadow.camera.top = 30;
  const ground = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshStandardMaterial({ color: 0xf3a15a })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; S.scene.add(ground);
  const box = (w, hh, dd, c, x, y, z) => { const m = new THREE.Mesh(new THREE.BoxGeometry(w, hh, dd), new THREE.MeshStandardMaterial({ color: c })); m.position.set(x, y, z); m.castShadow = m.receiveShadow = true; S.scene.add(m); return m; };
  const car = new THREE.Group(); const body = new THREE.Mesh(new THREE.BoxGeometry(2, 0.6, 1.2), new THREE.MeshStandardMaterial({ color: 0xffffff })); body.position.y = 0.6; body.castShadow = true; car.add(body); const cab = new THREE.Mesh(new THREE.BoxGeometry(1, 0.5, 1), new THREE.MeshStandardMaterial({ color: 0x333333 })); cab.position.set(-0.2, 1.1, 0); car.add(cab); [[-0.7, 0.6], [0.7, 0.6], [-0.7, -0.6], [0.7, -0.6]].forEach(([x, z]) => { const w = new THREE.Mesh(new THREE.CylinderGeometry(0.3, 0.3, 0.25, 16), new THREE.MeshStandardMaterial({ color: 0x222 })); w.rotation.x = Math.PI / 2; w.position.set(x, 0.3, z); car.add(w); }); S.scene.add(car);
  const props = []; for (let i = 0; i < 30; i++) { const b = box(1, 1, 1, [0xffffff, 0xe0664a, 0x4a7de0][i % 3], (Math.random() - 0.5) * 60, 0.5, (Math.random() - 0.5) * 60); b.userData.v = new THREE.Vector3(); props.push(b); }
  const txt = (s, x, z) => { const c = document.createElement('canvas'); c.width = 512; c.height = 128; const g = c.getContext('2d'); g.fillStyle = '#fff'; g.font = '900 90px Inter,sans-serif'; g.fillText(s, 10, 100); const m = new THREE.Mesh(new THREE.PlaneGeometry(8, 2), new THREE.MeshBasicMaterial({ map: new THREE.CanvasTexture(c), transparent: true })); m.rotation.x = -Math.PI / 2; m.position.set(x, 0.02, z); S.scene.add(m); };
  txt('PORTFOLIO-ish', -3, -6); txt('PROJECTS', 10, 4); txt('CONTACT', -12, 8);
  const K = {}; addEventListener('keydown', (e) => (K[e.key.toLowerCase()] = true)); addEventListener('keyup', (e) => (K[e.key.toLowerCase()] = false)); let sp = 0, ang = 0;
  S.on(() => { const f = (K.w || K.arrowup ? 1 : 0) - (K.s || K.arrowdown ? 1 : 0); sp = sp * 0.95 + f * 0.02; if (Math.abs(sp) > 0.01) ang += ((K.a || K.arrowleft ? 1 : 0) - (K.d || K.arrowright ? 1 : 0)) * 0.04 * Math.sign(sp); car.rotation.y = ang; car.position.x += Math.cos(ang) * sp; car.position.z -= Math.sin(ang) * sp; props.forEach((p) => { const dx = p.position.x - car.position.x, dz = p.position.z - car.position.z; if (dx * dx + dz * dz < 2.2) p.userData.v.set(dx * Math.abs(sp) * 2, 0.2, dz * Math.abs(sp) * 2); p.position.add(p.userData.v); p.userData.v.multiplyScalar(0.9); p.rotation.y += p.userData.v.length(); }); S.cam.position.set(car.position.x + 10, 12, car.position.z + 10); S.cam.lookAt(car.position); });
  root.append(h('div', { style: { position: 'absolute', left: '20px', bottom: '20px', zIndex: 2, fontSize: '13px', fontWeight: 700 } }, 'WASD / ↑↓←→ to drive · bump the crates'), h('div.k-row', { style: { position: 'absolute', right: '20px', bottom: '20px', zIndex: 2, gap: '6px' } }, ...[['▲', 'w'], ['◀', 'a'], ['▼', 's'], ['▶', 'd']].map(([l, k]) => h('button', { style: { width: '42px', height: '42px', borderRadius: '8px', border: '2px solid #fff', background: '#fff3', color: '#fff' }, onpointerdown: () => (K[k] = true), onpointerup: () => (K[k] = false), onpointerleave: () => (K[k] = false) }, l))));
  window.__demoProof = async () => { K.w = true; await sleep(500); K.w = false; return 'car drove to x=' + car.position.x.toFixed(1); };
};
V['voxel-model-editor-workspace'] = (root, T) => {
  theme(root, T, { bg: '#21252b', fg: '#cdd3de', ac: '#3e90ff', dark: true });
  const menu = h('div.k-row', { style: { height: '28px', background: '#1b1e23', fontSize: '12px', padding: '0 10px', gap: '14px' } }, h('b', { style: { color: '#3e90ff' } }, '⬛ Blockbench-ish'), '파일', '편집', '보기', '도구', '도움말');
  const tabs = h('div.k-row', { style: { height: '28px', background: '#282c34', fontSize: '12px', padding: '0 10px' } }, h('span', { style: { background: '#21252b', padding: '6px 12px' } }, '🏠 시작 화면'));
  const body = h('div', { style: { position: 'absolute', top: '56px', left: 0, right: 0, bottom: 0, overflow: 'auto' } });
  const start = h('div', { style: { maxWidth: '1000px', margin: '0 auto', padding: '0 20px' } }, h('div', { style: { height: '300px', background: 'linear-gradient(135deg,#4d3a2a,#8b5a3a 40%,#2e4b5e)', position: 'relative', overflow: 'hidden', borderRadius: '2px' } }, ...Array.from({ length: 40 }, (_, i) => h('div', { style: { position: 'absolute', left: (i * 97) % 1000 + 'px', top: (i * 53) % 280 + 'px', width: 20 + (i % 5) * 14 + 'px', height: 20 + (i % 4) * 16 + 'px', background: ['#c4874f', '#6fb3b8', '#e8c07a', '#7b4b2a', '#d65f4a'][i % 5], opacity: .8 } })), h('div', { style: { position: 'absolute', right: '10px', bottom: '8px', fontSize: '11px', background: '#0008', padding: '2px 6px' } }, 'Splash art: voxel tavern')), h('div', { style: { background: '#282c34', padding: '16px', marginTop: '8px' } }, h('h3', { style: { margin: '0 0 12px' } }, '빠른 설정'), h('div.k-row', { style: { gap: '20px', fontSize: '12px' } }, '키 배열', select(['기본 (QWERTY)', 'AZERTY'], '기본 (QWERTY)', () => {}), '언어', select(['한국어', 'English'], '한국어', () => {}))), h('div', { style: { background: '#282c34', padding: '16px', marginTop: '8px' } }, h('h3', { style: { margin: '0 0 12px' } }, '새 모델'), h('div.k-row', { style: { gap: '10px' } }, ...['Generic Model', 'Java Block/Item', 'Bedrock Model', 'Voxel Sculpt'].map((n) => h('button', { style: { background: '#3a3f4b', color: '#cdd3de', border: 0, padding: '14px 18px', cursor: 'pointer' }, onclick: () => editor(n) }, '＋ ' + n)))));
  body.append(start); root.append(menu, tabs, body);
  const editor = (n) => { tabs.append(h('span', { style: { background: '#21252b', padding: '6px 12px', color: '#fff' } }, '🧊 ' + n)); body.replaceChildren(); const vp = h('div', { style: { position: 'absolute', left: '200px', right: '240px', top: 0, bottom: 0 } }); const tools = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, width: '200px', background: '#282c34', padding: '10px', fontSize: '12px', display: 'grid', alignContent: 'start', gap: '8px' } }, h('b', {}, '도구'), seg([['add', '＋ 추가'], ['del', '－ 삭제'], ['paint', '🖌 칠하기']], 'add', (v) => (mode = v))); const pal = ['#e8c07a', '#c4874f', '#6fb3b8', '#d65f4a', '#7bc96f', '#ffffff', '#3a3a3a']; let col = pal[0], mode = 'add'; tools.append(h('div.k-row', { style: { flexWrap: 'wrap', gap: '4px' } }, ...pal.map((c) => h('span', { style: { width: '22px', height: '22px', background: c, cursor: 'pointer', outline: '1px solid #000' }, onclick: () => (col = c) })))); const out = h('div', { style: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '240px', background: '#282c34', padding: '10px', fontSize: '12px' } }, h('b', {}, '아웃라이너')); const list = h('div'); out.append(list); body.append(tools, vp, out);
    const S = stage(vp, { bg: '#1e2127' }); lights(S.scene); S.cam.position.set(10, 10, 12); const oc = new OrbitControls(S.cam, S.r.domElement); S.scene.add(new THREE.GridHelper(16, 16, 0x555555, 0x333333)); const vox = []; const g1 = new THREE.BoxGeometry(1, 1, 1);
    const add = (x, y, z, c) => { const m = new THREE.Mesh(g1, new THREE.MeshStandardMaterial({ color: c })); m.position.set(x + 0.5, y + 0.5, z + 0.5); S.scene.add(m); vox.push(m); list.textContent = `cubes: ${vox.length}`; };
    for (let x = -2; x < 2; x++) for (let z = -2; z < 2; z++) add(x, 0, z, pal[(x + z + 8) % 3]); add(0, 1, 0, pal[3]);
    const ray = new THREE.Raycaster(); const plane = new THREE.Mesh(new THREE.PlaneGeometry(16, 16).rotateX(-Math.PI / 2), new THREE.MeshBasicMaterial({ visible: false })); S.scene.add(plane);
    S.r.domElement.addEventListener('click', (e) => { const b = S.r.domElement.getBoundingClientRect(); ray.setFromCamera({ x: ((e.clientX - b.left) / b.width) * 2 - 1, y: -((e.clientY - b.top) / b.height) * 2 + 1 }, S.cam); const hit = ray.intersectObjects([...vox, plane])[0]; if (!hit) return; if (hit.object === plane) { if (mode === 'add') add(Math.floor(hit.point.x), 0, Math.floor(hit.point.z), col); return; } if (mode === 'del') { S.scene.remove(hit.object); vox.splice(vox.indexOf(hit.object), 1); } else if (mode === 'paint') hit.object.material.color.set(col); else { const p = hit.object.position.clone().add(hit.face.normal); add(p.x - 0.5, p.y - 0.5, p.z - 0.5, col); } list.textContent = `cubes: ${vox.length}`; });
    window.__voxCount = () => vox.length; };
  window.__demoProof = async () => 'start screen with 새 모델 → voxel editor';
};
V['gltf-material-lighting-studio'] = (root, T) => {
  theme(root, T, { bg: '#f0f0f0', fg: '#222', ac: '#3a7bd5', dark: false });
  const vp = h('div', { style: { position: 'absolute', left: 0, top: 0, bottom: 0, right: '300px' } }); const S = stage(vp, { bg: '#f0f0f0' }); lights(S.scene); S.cam.position.set(3, 2, 4); new OrbitControls(S.cam, S.r.domElement);
  const hint = h('div', { style: { position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', textAlign: 'center', pointerEvents: 'none', zIndex: 2 } }, h('div', {}, h('div', { style: { fontSize: '20px' } }, 'Drag a glTF or GLB here!'), h('div', { style: { fontSize: '12px', opacity: .7, marginTop: '6px' } }, 'Drop an HDR for lighting · or "Load sample" →')));
  vp.append(hint); let model = null; const mat = new THREE.MeshStandardMaterial({ color: 0xc0a080, metalness: 0.5, roughness: 0.3 });
  const setModel = (o) => { if (model) S.scene.remove(model); model = o; S.scene.add(o); hint.hidden = true; code.textContent = `<model-viewer-ish src="model.glb"\n  exposure="${P.exp}" shadow-intensity="1"\n  camera-controls auto-rotate>\n</model-viewer-ish>`; };
  const P = { exp: 1, rough: 0.3, metal: 0.5, rot: true }; S.on((t) => { S.r.toneMappingExposure = P.exp; if (model && P.rot) model.rotation.y = t * 0.4; });
  S.r.toneMapping = THREE.ACESFilmicToneMapping;
  vp.addEventListener('dragover', (e) => e.preventDefault()); vp.addEventListener('drop', (e) => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (!f) return; new GLTFLoader().load(URL.createObjectURL(f), (g) => setModel(g.scene), undefined, () => toast('Could not load file')); });
  const sec = (t, ...c) => h('div', { style: { borderBottom: '1px solid #333' } }, h('div.k-row', { style: { padding: '8px 12px', fontSize: '12px', fontWeight: 700, background: '#2a2a2a' } }, t, h('span', { style: { flex: 1 } }), '▾'), h('div', { style: { padding: '10px 12px', display: 'grid', gap: '8px' } }, ...c));
  const code = h('pre', { style: { background: '#fff', color: '#222', fontSize: '10px', padding: '8px', margin: 0, whiteSpace: 'pre-wrap' } }, '<model-viewer-ish src="">\n</model-viewer-ish>');
  const side = h('div', { style: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '300px', background: '#1f1f1f', color: '#ddd', overflow: 'auto', fontSize: '12px' } }, h('div.k-row', { style: { padding: '12px', justifyContent: 'center', gap: '8px', fontSize: '14px' } }, '◉', h('b', {}, '<model-viewer-ish>')), h('div.k-row', { style: { justifyContent: 'space-around', padding: '6px', background: '#2a2a2a' } }, '✎', '▣', '◈', '⚲'), sec('Model-viewer snippet', code, btn('Copy code', () => toast('copied'), 'pri')), sec('File manager', btn('Load sample', () => setModel(new THREE.Mesh(new THREE.TorusKnotGeometry(0.8, 0.28, 200, 32), mat)), 'pri'), h('div', { style: { opacity: .7 } }, 'Or drag a .glb onto the viewport')), sec('Lighting', slider('Exposure', 0, 3, 1, 0.01, (v) => (P.exp = v)), slider('Roughness', 0, 1, 0.3, 0.01, (v) => (mat.roughness = v)), slider('Metalness', 0, 1, 0.5, 0.01, (v) => (mat.metalness = v))), sec('Edit Properties', toggle('Auto-rotate', true, (v) => (P.rot = v))));
  root.append(vp, side);
  window.__demoProof = async () => 'empty viewport with drop target; Load sample shows PBR model';
};
V['origami-crease-fold-studio'] = (root, T) => {
  theme(root, T, { bg: '#ffffff', fg: '#222', ac: '#e0187f', dark: false });
  root.append(h('div.k-row', { style: { position: 'absolute', top: 0, left: 0, right: 0, height: '30px', background: '#333', color: '#fff', fontSize: '12px', padding: '0 12px', gap: '18px', zIndex: 2 } }, h('b', {}, '🦢'), 'File ▾', 'Examples ▾', 'View ▾', 'Folders', h('span', { style: { background: '#666', padding: '4px 8px' } }, 'Animation'), 'About', h('span', { style: { flex: 1 } }), h('span', { style: { opacity: .8 } }, 'Origami Simulator-ish')));
  const vp = h('div', { style: { position: 'absolute', top: '30px', left: 0, right: 0, bottom: '90px' } }); root.append(vp);
  const S = stage(vp, { bg: '#ffffff' }); lights(S.scene); S.cam.position.set(-2, 6, 8); new OrbitControls(S.cam, S.r.domElement);
  const N = 24, M = 18; let fold = 0.6, pattern = 'miura';
  const geo = new THREE.BufferGeometry(); const pos = new Float32Array(N * M * 6 * 3); geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  const mesh = new THREE.Mesh(geo, new THREE.MeshStandardMaterial({ color: 0xe0187f, side: THREE.DoubleSide, flatShading: true, roughness: 0.6 })); S.scene.add(mesh); const edges = new THREE.LineSegments(new THREE.EdgesGeometry(geo), new THREE.LineBasicMaterial({ color: 0x7a0a45 })); S.scene.add(edges);
  const vert = (i, j) => { const f = fold * Math.PI / 2.2; const a = 0.45, b = 0.4; const x = (i - N / 2) * a * Math.cos(f * 0.6); const z = (j - M / 2) * b + (pattern === 'miura' && i % 2 ? 0.2 * Math.cos(f) : 0); const y = (pattern === 'miura' ? (j % 2 ? 1 : -1) * (i % 2 ? 1 : 0) : (i + j) % 2 ? 1 : -1) * 0.25 * Math.sin(f) - (x * x + (z * z) * 0.6) * 0.07 * fold; return [x, y, z]; };
  const upd = () => { let k = 0; for (let i = 0; i < N; i++) for (let j = 0; j < M; j++) { const A = vert(i, j), B = vert(i + 1, j), C = vert(i + 1, j + 1), D = vert(i, j + 1); for (const p of [A, B, C, A, C, D]) { pos[k++] = p[0]; pos[k++] = p[1]; pos[k++] = p[2]; } } geo.attributes.position.needsUpdate = true; geo.computeVertexNormals(); edges.geometry.dispose(); edges.geometry = new THREE.EdgesGeometry(geo, 1); };
  upd();
  const lbl = h('output', {}, Math.round(fold * 100) + '%');
  root.append(h('div.k-row', { style: { position: 'absolute', bottom: '14px', left: '50%', transform: 'translateX(-50%)', gap: '30px', fontSize: '11px', textAlign: 'center' } }, h('div', {}, seg([['miura', 'Miura-ori'], ['water', 'Waterbomb']], 'miura', (v) => { pattern = v; upd(); }), h('div', {}, 'Crease Pattern')), h('div', {}, h('div.k-row', {}, 'Flat', h('input', { type: 'range', min: 0, max: 100, value: fold * 100, style: { width: '240px' }, oninput: (e) => { fold = e.target.value / 100; lbl.textContent = e.target.value + '%'; upd(); } }), 'Folded', lbl), h('div', {}, 'Fold Percent')), h('div', {}, btn('Reset', () => { S.cam.position.set(0, 7, 9); S.cam.lookAt(0, 0, 0); }), h('div', {}, 'Camera'))));
  window.__demoProof = async () => { fold = 0.8; upd(); return 'mesh folded 80%'; };
};
V['isometric-cutaway-room-studio'] = (root, T) => {
  theme(root, T, { bg: '#0a0a0a', fg: '#eee', ac: '#e8751a', dark: true });
  const vp = h('div', { style: { position: 'absolute', inset: 0 } }); root.append(vp);
  const S = stage(vp, { bg: '#0a0a0a', ortho: true }); S.cam.userData.zoom = 6; S.fit(); S.cam.position.set(10, 9, 10); S.cam.lookAt(0, 1.2, 0); S.r.shadowMap.enabled = true;
  S.scene.add(new THREE.AmbientLight(0xffe0c0, 1.1)); const lamp = new THREE.PointLight(0xffb060, 30, 12); lamp.position.set(-1, 2.6, 1); lamp.castShadow = true; S.scene.add(lamp); const d = new THREE.DirectionalLight(0xffffff, 0.4); d.position.set(5, 8, 3); S.scene.add(d);
  const M = (c) => new THREE.MeshStandardMaterial({ color: c, roughness: 0.8 }); const W = { floor: M(0x6b4a2e), wall: M(0x4a3020) };
  const box = (w, hh, dd, m, x, y, z, g = S.scene) => { const o = new THREE.Mesh(new THREE.BoxGeometry(w, hh, dd), m); o.position.set(x, y, z); o.castShadow = o.receiveShadow = true; g.add(o); return o; };
  box(6, 0.2, 6, W.floor, 0, -0.1, 0); box(6, 3.5, 0.2, W.wall, 0, 1.75, -3); box(0.2, 3.5, 6, W.wall, -3, 1.75, 0);
  for (let i = 0; i < 14; i++) box(0.05, 3.5, 0.02, M(0x2a1a10), -2.8 + i * 0.42, 1.75, -2.88);
  const furn = new THREE.Group(); S.scene.add(furn);
  const SETS = { cozy: () => { box(2.4, 0.5, 1, M(0x3a3a3a), 0, 0.25, -1.8, furn); box(2.4, 0.6, 0.3, M(0x333333), 0, 0.7, -2.2, furn); box(1.2, 0.3, 0.7, M(0x5a3a22), 0, 0.15, -0.2, furn); box(1.6, 0.9, 0.05, M(0x111111), -2.85, 1.6, 0, furn); box(1.5, 0.8, 0.02, new THREE.MeshBasicMaterial({ color: 0x3aa0e8 }), -2.82, 1.6, 0, furn); box(0.2, 2.2, 0.2, M(0x222222), -2, 1.1, 1.5, furn); box(0.6, 0.4, 0.6, M(0xffcc77), -2, 2.3, 1.5, furn); box(0.4, 2.4, 1.2, M(0x3a2618), 2.5, 1.2, -2.5, furn); box(0.5, 0.9, 0.5, M(0x2d6a3a), 2.2, 0.45, 1.8, furn); box(3, 0.02, 2, M(0x8a7a6a), 0, 0.02, -0.5, furn); }, office: () => { box(2, 0.1, 1, M(0xdddddd), 0, 1, -2.2, furn); box(0.8, 0.9, 0.8, M(0x222222), 0, 0.45, -1.2, furn); box(1, 0.6, 0.05, M(0x111111), 0, 1.45, -2.5, furn); box(0.4, 2.4, 1.2, M(0x999999), 2.5, 1.2, -2.5, furn); }, empty: () => {} };
  let cur = 'cozy'; const set = (k) => { cur = k; furn.clear(); SETS[k](); }; set('cozy');
  const sw = (cs, on) => h('div.k-row', { style: { gap: '6px' } }, ...cs.map((c) => h('span', { style: { width: '22px', height: '22px', borderRadius: '4px', background: c, cursor: 'pointer', border: '1px solid #444' }, onclick: () => on(c) })));
  root.append(h('div', { style: { position: 'absolute', left: '20px', top: '16px', fontSize: '12px', opacity: .7, zIndex: 2 } }, 'Room Studio-ish'), h('div', { style: { position: 'absolute', right: '30px', top: '130px', width: '230px', background: '#1a1a1a', borderRadius: '10px', padding: '14px', display: 'grid', gap: '10px', fontSize: '12px', zIndex: 2 } }, h('div.k-row', {}, h('b', {}, 'Theme'), h('span', { style: { flex: 1 } }), h('span', { style: { background: '#e8751a', padding: '2px 8px', borderRadius: '99px' } }, 'Night')), sw(['#1a1a1a', '#555', '#999', '#ddd', '#fff'], (c) => (S.scene.background = new THREE.Color(c))), 'Walls', sw(['#4a3020', '#8a6a4a', '#d8d0c0', '#2e3e5a', '#6a2a2a'], (c) => W.wall.color.set(c)), 'Floor', sw(['#6b4a2e', '#a07850', '#444', '#ccc'], (c) => W.floor.color.set(c)), 'Furniture', seg([['cozy', 'Cozy'], ['office', 'Office'], ['empty', 'Empty']], 'cozy', set), 'Lamp', h('input', { type: 'range', min: 0, max: 60, value: 30, oninput: (e) => (lamp.intensity = +e.target.value) }), btn('Toggle day / night', () => { const n = lamp.intensity > 0; lamp.intensity = n ? 0 : 30; d.intensity = n ? 1.6 : 0.4; }, 'pri')));
  window.__demoProof = async () => { set('office'); await sleep(100); set('cozy'); return 'room furniture sets swap'; };
};
export function mount(root, variant, opts, T) { (V[variant] || V['3d-blob-param-mixer'])(root, T); }
